<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<p><?=$this->description?></p>

<b><?= $this->message ?></b>

<?= $this->settingsForm ?>

<h5><?=$this->text('consultants_heading')?></h5>
<?= $this->consultantsEdit ?>

<p><?=$this->text('list_autoreplies')?></p>
<?= $this->autoRepliesNotifications ?>

<p><?=$this->text('list_replies')?></p>
<?= $this->repliesNotifications ?>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>
