<?=$this->render('top.phtml')?>
<?$this->cfg = $this->config->general->category?>
<div id="kategorie">
			
<?/*
<h1>Vydání: 
    <!--<a href="<?=$this->url(array('name' => $this->bul_url_name), 'bulletin', true)?>">-->
        <span><?=$this->bulletin_name?></span>
    <!--</a>-->
</h1>
*/?>
<h1><?=$this->category['name']?></h1>

<? if (!empty($this->category['annotation'])) { ?>
    <div class="perex">
    <p><?=$this->category['annotation']?></p>
    </div>
<?}?>

<?/* ------ Obrazek kategorie (hozny zpusob - zkousime pro kadou priponu) ------ */?>
<?if(file_exists($this->config->categories_admin->img_basepath.'/'.$this->category['id'].'.jpg')){?>
    <?$cat_img = $this->config->categories_admin->img_basepath.'/'.$this->category['id'].'.jpg';?>
<?}elseif(file_exists($this->config->categories_admin->img_basepath.'/'.$this->category['id'].'.png')){?>
    <?$cat_img = $this->config->categories_admin->img_basepath.'/'.$this->category['id'].'.png';?>
<?}elseif(file_exists($this->config->categories_admin->img_basepath.'/'.$this->category['id'].'.gif')){?>
    <?$cat_img = $this->config->categories_admin->img_basepath.'/'.$this->category['id'].'.gif';?>
<?}?>


<form action="" method="post" class="tridit" id="filterform">
  <fieldset>
    <?if(!empty($cat_img)){?>
        <img src="<?=$cat_img?>" alt="Obrázek kategorie" class="cat_img"/>
    <?}?>
    
    <table border="0" cellspacing="0" cellpadding="0" rules="none" class="mar">
      <tr>
        <th>Řadit podle:</th>
        <td><input type="radio" name="order" id="order1" value="1" 
        <?=$this->order_num == 1 ? 'checked="checked"' : ''?>/></td>
        <td><label for="order1">Datum vydání </label></td>
        <td><input type="radio" name="order" id="order2" value="2" 
        <?=$this->order_num == 2 ? 'checked="checked"' : ''?>/></td>
        <td><label for="order2">Název </label></td>
        <td><input type="radio" name="order" id="order3" value="3" 
        <?=$this->order_num == 3 ? 'checked="checked"' : ''?>/></td>
        <td><label for="order3">Autor </label></td>
      </tr>
    </table>
    <table border="0" cellspacing="0" cellpadding="0" rules="none" class="table3">
      <tr>
        <th><label for="author">Autor:</label></th>
        <td><select name="fauthor" id="fauthor">
             <?foreach($this->authors_sel as $key => $name){?>
                 <option value="<?=$key?>"
                 <?= $key == $this->filter_author ? 'selected=""' : ''?>>
                 <?=$name?></option>
             <?}?>
        </select></td>
        <td><input type="submit" value="Odeslat" id="filtersubmit"/></td>
      </tr>
    </table>
  </fieldset>
</form>
   
<?/* Pro vypis nazvu kategorie jako podnadpis
<h2><?=$this->category['name']?></h2>
*/?>
   
        <!-- <div id="clanek">-->
            <?/* Pro vypis anotace kategorie
            <? if (!empty($this->category['annotation'])) { ?>
                <p><?=$this->category['annotation']?></p>
            <?}?>
            
            <?if(empty($this->showing_whole_category)){?>
                <div class="reset"></div>
            <?}?>
            */?>
            
            <? if(empty($this->annotations) && $this->filter_author == 'default' 
                  && !empty($this->config->general->show_only_current_bulletin_in_category)){ ?>
                <br/>
                <strong>V tomto čísle není žádný článek v kategorii 
                    "<?=$this->category['name']?>".</strong>
            <? }elseif(empty($this->annotations) && $this->filter_author == 'default' 
                  && empty($this->config->general->show_only_current_bulletin_in_category)){ ?>
                <strong>V kategorii "<?=$this->category['name']?>" zatím není žádný článek.</strong>
            <? }elseif(empty($this->annotations) && $this->filter_author != 'default'){ ?>
                <strong>Zadanému filtru neodpovídá žádný článek.</strong>
            <?}?>
        
        <!-- <div class="clanek">-->
        
        <? $last_bul_url = '' ?>
        <? reset($this->annotations); $first_annotation_key = key($this->annotations);?>
        <?foreach($this->annotations as $current_key => $annotation){?>
            <? if(!empty($this->showing_whole_category) && $last_bul_url != $annotation['bulletin_url_name']){ ?>
                <!-- </div><div class="clanek">-->
                <? $last_bul_url = $annotation['bulletin_url_name'] ?>
                
                <?if($first_annotation_key != $current_key){?>
                    <div class="reset"></div>
                <?}?>
                
                <?/*
                <h3>
                    <a href="<?=$this->url(array('name' => $annotation['bulletin_url_name']), 'bulletin')?>">
                    <?=$annotation['bulletin_name']?>
                    </a>
                </h3>
                */?>
            <? } ?>
            <h4>
                <a href="<?=$this->url($annotation['url']['params'], $annotation['url']['route'])?>"><?=$annotation['name']?></a>
            </h4> 
            <p><?=$annotation['annotation']?> 
            <?/*<a href="<?=$this->url($annotation['url']['params'], $annotation['url']['route'])?>">číst celý článek</a></p>*/?>
            <p class="cist">
                <a href="<?=$this->url($annotation['url']['params'], $annotation['url']['route'])?>">
                    číst celý článek
                </a>
                <?$info_array = array($annotation['author'], $annotation['created'],)?>
                <?$info_array = array_filter($info_array, create_function('$elem','return empty($elem) ? false : true;'))?>
                <strong><?=join(' | ', $info_array)?></strong>
            </p>
        <?}?>
            
        <!-- </div> -->
    
        <? if(empty($this->showing_whole_category) && $this->articles_in_other_bulletins){ ?>
            <br/>
            <p><a href="<?=$this->url(array('all' => $this->all))?>">Zobrazit všechny články...</a></p>
        <? } ?>
        <? if(!empty($this->showing_whole_category) && !empty($this->show_only_current_bulletin)){ ?>
            <br/>
            <p><a href="<?=$this->url(array('bulletin' => $this->bul_url_name, 'name' => $this->category['url_name']), 'categorybulletin', true)?>">Zobrazit jen články čísla &bdquo;<?=$this->bulletin_name?>&ldquo;...</a></p>
        <? } ?>
        
        <?if(isset($this->paginator)){?>
            <?= $this->paginationControl($this->paginator, 'Sliding', 'pagination_control.phtml'); ?>
            <div class="clear"></div>
        <?}?>
        
        
        <!-- </div> -->
</div>

<?=$this->render('bottom.phtml')?>

