<?=$this->render('top.phtml')?>
<div id="archiv">

<h1>Vydání: 
    <!--<a href="<?=$this->url(array('name' => $this->bul_url_name), 'bulletin', true)?>">-->
        <span><?=$this->bulletin_name?></span>
    <!--</a>-->
</h1>
			
    <h2>Archiv vydaných čísel</h2>
    
    <?foreach($this->bulletin_list as $bulletin){?>
        <h4>
            <a href="<?=$this->url(array('name' => $bulletin['url_name']), 'bulletin', true)?>"><?=$bulletin['name']?></a>
            <? if(isset($bulletin['pdfUrl'])): ?>
            <span class="archiv-pdf">
              | <a href="<?=$bulletin['pdfUrl']?>" rel="external">(stáhnout v PDF)</a>
            </span>
            <? endif; ?>
        </h4>
    <?}?>
</div>

<?=$this->render('bottom.phtml')?>
