<?/* box used for spam score result */?>
<?if($this->spam){?>
<div id="spam_score">	
	<h3><?=$this->text('spam_title')?>
	<span style="font-weight:bold; <?=$this->spam->isSpam?'color:red':'color:green'?>"><?=$this->spam->score?></span>
	<!-- <span style="float:right;color:gray;font-size:smaller"></span>-->
	</h3>
	<span><?=$this->text('spam_created')?><?=date('d.m.Y H:m:s',strtotime($this->spam->created))?></span>	
	<?if(!is_array($this->spam->scorelist)){?>
		<pre style="overflow-y:hidden"><?=$this->spam->scorelist?></pre>
	<?}else{?>
		<table class="tablesorter">
		<thead>
			<th><?=$this->text('spam_points')?></th>	
			<th style="width:100%"><?=$this->text('spam_desc')?></th>
		</thead>
		<tbody>
		<?foreach($this->spam->scorelist as $item){?>
		<tr <?=floatval($item['points']) > 0 ? 'style="font-weight:bold"':''?>>
			<td><?=$item['points']?></td>
			<td title="<?=$item['desc']?>"><?=$item['name']?></td>		
		</tr>
		<?}?>
		</tbody>
		</table>
	<?}?>
</div>		
<?}?>