<div id="preview_links">    
       <? if (isset($this->preview_links)): ?>
        <a class="btn tip" data-original-title="<?=$this->preview_links_tooltip?>"
           href='<?=$this->preview_links ?>' rel="external">
            <i class="icon-eye-open"></i>&nbsp;<?=$this->text('admin.preview_links.main.title')?></a>	
       <? else: ?>
         <button data-placement="right" data-original-title="<?=$this->text('admin.preview_links.tooltip.empty');?>" class="btn tip disabled"><i class="icon-eye-open"></i>&nbsp;<?=$this->text('admin.preview_links.main.title')?></button>	
       <?endif;?>
</div>