<? 
    $text = Ibulletin_Texts::getSet('admin');
    $act = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
?>
<? if ($this->contextMenu): ?>
    <div class="btn-group">
        <? foreach ($this->contextMenu as $key => $menu): ?>
            <? if (is_array($menu['route'])): ?>        
                <a class='btn' href="<?= $this->url($menu['route'],null,true) ?>">
                <?/*Jestli je zaznam textech controlleru pouzije se, jinak se pouzije globalni text */?>
                <?=(isset($this->texts->$act->context->$key->title) && $this->texts->$act->context->$key->title) ?
                    $this->texts->$act->context->$key->title : $text->module_names->$menu['route']['controller']?>
                </a>
            <? endif; ?>
        <? endforeach; ?>  
    </div>
<? endif; ?>
