<ul <?=$this->pager->getHtmlId() ? 'id="'.$this->pager->getHtmlId().'"' : ''?>>

    <?/* previous page */?>
    <? if($this->pager->getOnPage() != 1){ ?>
        <li title="<?=$this->text('datagrid.paginator.prev')?>" class=" link prev">
            <a href="<?=$this->pager->getLink((($this->pager->getOnPage() - 2) * $this->pager->getLimit()))?>"><span>&laquo;</span></a>
        </li>
    <? } else {?>
        <li title="<?=$this->text('datagrid.paginator.prev')?>" class=" disabled link prev off">
            <span>&laquo;</span>
        </li>
    <? } ?>

    <?/* first page */?>
    <? if($this->pager->getOnPage() == 1){ ?>
    <li title="<?=$this->pager->getTitle(1)?>"class=" active link first"><span>1</span></li>
    <? } else { ?>
    <li title="<?=$this->pager->getTitle(1)?>"class=" link first"><a href="<?=$this->pager->getLink(0)?>">1</a></li>
    <? } ?>

    <?/* more pages in range */ ?>
    <? if($this->pager->getNumberPages() > $this->pager->getRange()){ ?>

        <? if($this->pager->getRangeStart() > 1){ ?>
            <li class="disabled range"><span>...</span></li>
        <? } ?>

        <? for ($i = $this->pager->getRangeStart() + 1; $i < $this->pager->getRangeEnd(); $i++){ ?>
            <? if($this->pager->getOnPage() == $i){ ?>
                <li title="<?=$this->pager->getTitle($i)?>" class=" link active"><span><?=$i?></span></li>
            <? } else { ?>
                <li title="<?=$this->pager->getTitle($i)?>" class=" link"><a href="<?=$this->pager->getLink((($i - 1) * $this->pager->getLimit()))?>"><?=$i?></a></li>
            <? } ?>
        <? } ?>

        <? if($this->pager->getRangeEnd() < $this->pager->getNumberPages() ){ ?>
            <li class="disabled range"><span>...</span></li>
        <? }?>
    <?/* less pages in range  */ ?>
    <? }else{ ?>

        <? for($i = 2; $i < $this->pager->getNumberPages(); $i++){ ?>

            <? if($this->pager->getOnPage() == $i){ ?>
                <li title="<?=$this->pager->getTitle($i)?>" class=" link active"><span><?=$i?></span></li>
            <? }else{ ?>
                <li title="<?=$this->pager->getTitle($i)?>" class=" link"><a href="<?=$this->pager->getLink((($i - 1) * $this->pager->getLimit()))?>"><?=$i?></a></li>
            <? } ?>
        <? } ?>
    <? } ?>

    <?/* last page */?>
    <? if($this->pager->getOnPage() == $this->pager->getNumberPages()){ ?>
        <li title="<?=$this->pager->getTitle($this->pager->getNumberPages())?>" class="link active last"><span><?=$this->pager->getNumberPages()?></span></li>
    <? }else{ ?>
        <li title="<?=$this->pager->getTitle($this->pager->getNumberPages())?>" class=" link last"><a href="<?=$this->pager->getLink((($this->pager->getNumberPages() - 1) * $this->pager->getLimit()))?>"><?=$this->pager->getNumberPages()?></a></li>
    <? } ?>

    <?/* next page */?>
    <? if($this->pager->getOnPage() != $this->pager->getNumberPages()){ ?>
        <li title="<?=$this->text('datagrid.paginator.next')?>" class=" link next"><a href="<?=$this->pager->getLink(($this->pager->getOnPage() * $this->pager->getLimit()))?>"><span>&raquo;</span></a></li>
    <? } else {?>
    <li title="<?=$this->text('datagrid.paginator.next')?>" class=" disabled link next off"><span>&raquo;</span></li>
    <? } ?>

    <?/* input for page number
    <li class="page-no">
        <script>
            function is_number(v) {
                if (typeof v == 'number') {
                    return true;
                } else if (typeof v == 'string') {
                    a = v.match(new RegExp('^[0-9]+$','i')) ? true : false;
                    return a;
                }
                return false;
            }
        </script>
        <form method="get"  onsubmit="return is_number(p.value)">
            <input type="number" name="p" title="Page number" placeholder="#" min="1" max="<?=$this->pager->getNumberPages()?>" autocomplete="off" />
        </form>
    </li>
    */?>

</ul>
<?/*<?=$this->pager->getOnPage()?>*/?>
<?/*=$this->pager->getNumberRecords()*/?>
