<? $pager = $this->grid->getPager('Standard') ?>
<? /** @var $columns Ibulletin_DataGrid_Column[] */ ?>
<? $columns = $this->grid->getColumns() ?>
<? $actions = array() ?>
<? $customFilters = $this->grid->getCustomFilters() ?>
<? foreach ($columns as $_column) { ?>
    <? if ($_column->getAction()) { ?>
        <? $actions[] = $_column;
        continue; ?>
    <? } ?>
    <?/*<col <?= $_column->getHtmlProperty() ?> />*/?>
<? } ?>
<? $action_count = count($actions) ?>
<? $action_width = max(80, max(2, $action_count) * 36) ?>

<form class="datagridForm" method="post">

    <? /* custom filters */?>
    <? if ($customFilters){ ?>
        <? $submitOnChange = false ?>
        <? $i=0; foreach ($customFilters as $key => $filter){ ?>
    
            <?
                if ($filter->getSubmitOnChange() && !$submitOnChange) {
                    $submitOnChange = true;
                }
            ?>
            <? if (($i % 3 == 0) || $filter->getNewLineForm()) {?>
                <?if ($i != 0){?>
                    </div>
                </fieldset>
                <?}?>
                <?if($filter->getNewLineForm()) $i = 0;?>
                <fieldset class="inline">
                <div class="control control-rows">
            <? } $i++?>
            <?if($filter->getFormtype() == 'checkbox'):?>
               <div class="span">
                  <label for="f_<?=$key?>" class="checkbox">
                  <input value="" name="f_<?=$key?>" type="hidden"/>
                  <input id ="f_<?=$key?>" value="<?=($o=$filter->getOptions())? $o[0]:"1"?>" name="f_<?=$key?>" type="checkbox"<?=($filter->getValue()) ? " CHECKED" : ""?>/><?=$filter->getLabel()?>
                  </label>
               </div>
            <?else:?>
            <? if ($opts = $filter->getOptions()) { // select combobox?>
                <div class="span">
                    <label for="f_<?=$key?>"><?=$filter->getLabel()?></label>
                    <select name="f_<?=$key . ($filter->getMultiple()?'[]':'')?>"
                            class="selectpicker"
                            <?=$filter->getMultiple()?'multiple':''?>
                            title="<?=$this->escape($filter->getTitle() ? $filter->getTitle() : $filter->getEmptyText())?>">

                        <?if(is_null($filter->getDefault()) && !$filter->getMultiple()):?>
                            <option <?=is_null($filter->getValue()) ? 'selected' : ''?> value=""><?=$filter->getEmptyText()?></option>
                        <?endif;?>

                        <? foreach ($opts as $o_key => $o_val){ ?>
                        <option <?=(($filter->getMultiple() && is_array($filter->getValue()) && in_array(strval($o_key), $filter->getValue()))
                                 || ($filter->getValue() === strval($o_key))) ? 'selected' : ''?> value="<?=$o_key?>">
                            <?=$this->truncate($this->escape($o_val))?></option>
                        <? } ?>
                    </select>
                </div>
            <? } else { ?>
                <div class="span"><label for="f_<?=$key?>"><?$filter->getLabel()?></label>
                    <input type="text" title="<?=$this->escape($filter->getTitle())?>" name="f_<?=$key?>"
                           value="<?=$this->escape($filter->getValue())?>" />
                </div>
            <? } ?>
            <?endif;?>
        <? } ?>
        </div>
        </fieldset>

         <? if(!$submitOnChange):?>       
            <fieldset class="span">
                 <input class="btn btn-primary" type="submit" name="filter" value="filter" title="Filter" />
            </fieldset>
         <?else:?>
            <input type="hidden" name="filter" value="filter" />
            <script type="text/javascript">
                $('.datagridForm :input').on('change',function() {
                    $('.datagridForm').submit();
                });
            </script>
         <?endif;?>
        
    <? } ?>

    <table class="table table-bordered table-hover table-striped table-condensed datagrid">
    <? /* table colgroup */ ?>

    <? /* table header */ ?>
    <thead>
        <tr class="rowHead">
            <? $i=0;foreach ($columns as $_column){ ?>
                <? if (!$_column->getAction()) { ?>
                    <th title="<?=sprintf($this->text('datagrid.grid.column_title'),$_column->getHeader())?>" class="<?=$_column->getDir() ? 'active': ''?>
                        <?=$_column->getHeaderCssClass()?>"><?=$_column->getHeaderHtml() ?></th>
                <? } ?>
            <? } ?>
            <th class="no-link"><span class="title"><?=$this->text('datagrid.grid.actions')?></span></th>
 		</tr>
        <? if ($this->grid->hasColumnFilters() || $this->grid->getCustomFilters()){ ?>
        <tr class="rowFilters">
            <? $i=0;foreach ($columns as $key => $_column){ $i++; ?>

            <? if ($filter = $this->grid->getFilter($key)) { // we have filter ?>
                    <? if ($opts = $filter->getOptions()) { // select combobox?>
                        <td>
                            <select name="f_<?=$key?>" class="selectpicker">
                            <option <?=is_null($filter->getValue()) ? 'selected' : ''?> value="">&nbsp;</option>
                            <? foreach ($opts as $o_key => $o_val){ ?>
                                <option <?=$filter->getValue() === strval($o_key) ? 'selected' : ''?> value="<?=$o_key?>">
                                    <?=$this->escape($o_val)?></option>
                            <? } ?>
                            </select>
                        </td>
                    <? } else { ?>
                        <? if ($filter->getAutocomplete()) { // text autocomplete ?>
                            <td><div class="autocomplete">
                                <input title="<?=$this->text('datagrid.grid.filter_title')?>" type="text" id="<?=$key?>" name="f_<?=$key?>"
                                       value="<?=$this->escape($filter->getValue())?>" />
                            </div></td>
                        <? } else { // text ?>
                            <td>
                                <input title="<?=$this->text('datagrid.grid.filter_title')?>" type="text" name="f_<?=$key?>"
                                       value="<?=$this->escape($filter->getValue())?>" />
                            </td>
                        <? } ?>
                    <? } ?>
                <? } elseif (!$_column->getAction()) { /* no filter => blank cell, render actions at the end */?>
                    <td class="empty">&nbsp;</td>
                <? } ?>
            <? } ?>

            <?if ($this->grid->hasColumnFilters()){ ?>
                <td class="filter_action">
                    <div class="btn-toolbar">
                    <div class="btn-group pull-right">
                        <button class="btn btn-small" type="submit" id="destroy_filter" name="filter" value="destroy" title="Reset">
                            <i class="icon icon-ban-circle"></i>
                        </button>
                        <button class="btn btn-small default-action-button" type="submit" id="set_filter" name="filter" value="filter" title="Filter" >
                            <i class="icon icon-filter"></i>
                        </button>
                    </div>
                    </div>
                </td>
            <? } elseif ($action_count) { ?>
                <td>&nbsp;</td>
            <? } ?>
        </tr>
        <? } ?>

    </thead>
    <? /* table body */ ?>
	<? if (($this->grid->count())){ ?>
        <?foreach ($this->grid->getIterator() as $_index=>$_item){ ?>
            <tr>
                <? foreach ($columns as $_column){ ?>
                    <? if (!$_column->getAction()){ /* not action */?>
                        <td <?=$_column->getStyleProperty() ?> class="<?=$_column->getCssProperty() ?>">
                            <?=($_html = $_column->getRowField($_item)) !== '' ? $_html : '&nbsp;' ?>
                        </td>
                    <? } ?>
                <? } ?>
                <? /* row actions */ ?>
                <td>
                    <div class="btn-toolbar">
                    <div class="btn-group pull-right">
                    <? foreach ($actions as $_column){ /* actions */?>
                            <?=($_html = $_column->getRowField($_item)) !== '' ? $_html : '&nbsp;' ?>
                        <? } ?>
                    </div>
                    </div>
                </td>
            </tr>
        <? } ?>
    <? } elseif ($text = ($this->grid->getEmptyText() ?: $this->text('datagrid.grid.empty'))){ ?>
    	<tr>
    		<td class=" <?=$this->grid->getEmptyTextClass() ?>" colspan="<?=$this->grid->getColumnCount()?>"><?=$text?></td>
    	</tr>
    <? } ?>

    <? /* table footer */ ?>
    <tfoot>
        <tr class="rowFoot">

            <td colspan="<?= $this->grid->getColumnCount() - $action_count ?>">
                <div class="pagination">
                    <div style="float:left;padding:0px 5px 0px 10px;font-weight:bold;"><?= $this->grid->getNumberRecords() ?><?= $this->text('datagrid.paginator.records') ?></div>
                    <?= $pager ?>
                </div>
            </td>

            <td>
            <? if ($this->grid->getExportable()) { ?>
                <div class="btn-toolbar">
                <div class="btn-group pull-right">
                    <a class="btn btn-small" href="<?= $this->url(array('export' => 'csv')) ?>" id="export-csv" title="CSV export">csv</a>
                    <a class="btn btn-small" href="<?= $this->url(array('export' => 'xlsx')) ?>" id="export-xlsx" title="XLSX export">xlsx</a>
                </div>
                </div>
            <? } ?>
            </td>

        </tr>
    </tfoot>
</table>
</form>


