<?= $this->doctype('XHTML1_STRICT') ?> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
<head>
<?$title=$this->project_name . (!empty($this->page_title) ? ' - '.$this->page_title : '') ?>
<?/* title */?>
    <title><?=$title?></title>
<?/* encoding */?>
    <meta http-equiv="Content-language" content="cs" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-script-type" content="text/javascript" />
    <meta http-equiv="content-style-type" content="text/css" />
<?/* cache */?>
<?/*    <meta http-equiv="Cache-control" content="no-cache" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
*/?>
<?/* keywords & categories */?>
    <meta name="description" xml:lang="cs" lang="cs" content="<?=$this->page_title?>" />
    <meta name="keywords" xml:lang="cs" lang="cs" content="" />
    <meta name="category" content="<?=$this->project_name?>" /> 
<?/* author */?>
    <meta name="author" content="Pears Health Cyber s.r.o. (http://www&#45;pearshealthcyber&#45;com) | <?=date("Y")?> | info&#64;pearshealthcyber&#45;com" />
    <meta name="webmaster" content="Pears Health Cyber s.r.o. (http://www&#45;pearshealthcyber&#45;com) | <?=date("Y")?> | info&#64;pearshealthcyber&#45;com" /> 
    <meta name="copyright" content="©<?=date("Y")?> Pears Health Cyber s.r.o." />
<?/* robots */?>
    <meta name="robots" content="noindex, nofollow" />
    <meta name="googlebot" content="noindex, nofollow" />
    <meta name="msnbot" content="noindex, nofollow" />
<?/* browser specific features */?>
<?/* msie */?><?/*
    <meta http-equiv="imagetoolbar" content="no" /> 
    <meta http-equiv="MSThemeCompatible" content="no" /> 
    <meta name="MS.LOCALE" content="cs" /> 
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
*/?>
<?/* opera */?>
    <meta name="autosize" content="off" />
<?/* favicon */?>
    <link rel="shortcut icon" type="image/x-icon" href="<?=$this->baseUrl('pub/img/favicon.ico')?>" />
<?/* JS & CSS */?>
<?=Ibulletin_HtmlHead::render()?>
</head>
