
<div>
    <div><?php echo $this->formLabel($this->element->getName(), $this->element->getLabel())?></div>
    <?php
    $this->element->setAttrib('id', $this->element->getAttrib('class') . $this->rank);
    echo $this->{$this->element->helper}(
            $this->element->getName(), $this->element->getValue(), $this->element->getAttribs()
    )
    ?>
   <? //pro users kteri nemaji pravo zobrazit vsechny editory zobrazi pouze wysiwig
   if(!Ibulletin_AdminAuth::hasPermission('privilege_allow_all_editors')):?>
        <?if($this->wysiwig):?>
            <script type="text/javascript">CKEDITOR.replace('editarea');</script>
             <div class="row ace-foot"></div>
         <?else:?>
             <!--zobrazeni textarea, neni-li k dispozice zadny editor -->
             <script type="text/javascript">$('.editarea').css('display','block');</script>
        <?endif;?>
   
   <?else:?>
    <div class="ace-wrap <?=$this->element->getAttrib('ace_class')?>" id="ace-wrap<?= $this->rank ?>">        
        <div class="ace-toolbar btn-toolbar">
            <div class="btn-group">
                <a href="#" data-placement='bottom' data-original-title="<?= $this->text('ace.tooltip.fullscreen'); ?>" class="btn ace-fullscreen tip"><i class="icon-fullscreen"></i></a>
                <a href="#" data-placement='bottom' data-original-title="<?= $this->text('ace.tooltip.search'); ?>" class="tip btn ace-search"><i class="icon-search"></i></a>
                <a href="#" data-placement='bottom' data-original-title="<?= $this->text('ace.tooltip.replace'); ?>" class="tip btn ace-replace"><i class="icon-random"></i></a>                
            </div>
            <div class="btn-group">
                <a href="#" data-placement='bottom' data-original-title="<?= $this->text('ace.tooltip.undo'); ?>" class="tip btn ace-undo"><i class="icon-arrow-left"></i></a>
                <a href="#" data-placement='bottom' data-original-title="<?= $this->text('ace.tooltip.redo'); ?>" class="tip btn ace-redo"><i class="icon-arrow-right"></i></a> 
            </div>  
            <? if ($this->templates): ?>
            <? if ($this->templates->ico_tpls): ?>
                <div class="btn-group">
                    <? foreach ($this->templates->ico_tpls as $tpl): ?>
                        <a href="#" data-placement='bottom' data-original-title="<?= $tpl['tooltip'] ?>" data-placement='bottom' class="tip btn ace-tpl"><i class="<?= $tpl['icon'] ?>"></i>
                            <div style="display:none;" class="ace-tpl-code"><?= $this->escape($tpl['template']) ?></div>
                        </a>
                    <? endforeach; ?>
                </div>
            <? endif; ?>
            <? if ($this->templates->list_tpls): ?>
                <div class="btn-group">
                    <a class="tags btn dropdown-toggle" data-toggle="dropdown"><?= $this->text('ace.editor.tpls'); ?>&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <? foreach ($this->templates->list_tpls as $tpl): ?>
                            <li><a class="ace-tpl tip" data-placement='right' data-original-title="<?= $tpl['tooltip'] ?>" href="#"><?= $tpl['title'] ?>
                                    <div style="display:none;" class="ace-tpl-code"><?= $this->escape($tpl['template']) ?></div></a></li>
                        <? endforeach; ?>
                    </ul>
                </div>
            <? endif; ?>
            <? if ($this->templates->tags): ?>
                <div class="btn-group">
                    <a class="tags btn dropdown-toggle" data-toggle="dropdown"><?= $this->text('ace.editor.tags'); ?>&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <? foreach ($this->templates->tags as $tag): ?>
                            <li><a class="ace-tag tip" data-placement='right' data-original-title="<?= $tag['tooltip'] ?>" href="#" tag='<?= $this->escape($tag['tag']) ?>'><?= $tag['title'] ?></a></li>
                        <? endforeach; ?>
                    </ul>
                </div>
            <? endif; ?>
            <? endif; ?>
            <?if($this->links):?>
                <div class="btn-group">
                    <a href="#linkpicker<?=$this->rank?>" data-toggle="modal" data-placement='bottom' data-original-title="<?= $this->text('ace.tooltip.addlink'); ?>" class="tip btn"><i class="glyphicon glyphicon-link"></i></a>
                </div>
            <?endif;?>
            <div class="btn-group">
                <a href="#" data-placement='bottom' data-original-title="<?= $this->text('ace.tooltip.settings'); ?>" class="tip btn ace-settings"><i class="icon-wrench"></i></a>                                       
            </div>
        </div>
        <div mode="<?= $this->templates ? $this->templates->mode : '' ?>" id="ace-editor<?= $this->rank ?>">
        </div>       
    </div>
    <div class="row ace-foot">
        <?if($this->wysiwig):?>
        <div class="span1">
            <a class="btn tip wysiwigSwitch" data-placement="top" data-rank="<?=$this->rank?>" class="pom" data-original-title="Wysiwig editor" href="#">
                <i class="icon-edit"></i>
            </a>        
        </div>
        <?endif;?>
        <div class="span2 ace-check" id="ace-check<?=$this->rank?>">
            <label class="checkbox"><input id="ace-show<?= $this->rank ?>" type="checkbox" checked="checked"/>ACE editor</label>
        </div>
    </div> 
    <?endif;?>
</div>
<?if($this->links):?>
 <?=$this->render('linkpicker.phtml',$this->links,$this->rank)?>
<?endif;?>
