<?/* vypis info zprav */?>
<?if(!empty($this->info_messages)):?>
<div>
	<?foreach($this->info_messages as $msg):?> 
		<?if(!is_string($msg)):?>
			<div class="alert alert-<?=$msg['type']?>">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?=$msg['message']?>
                <?if($msg['detailedList']):?>
                    <?
                        $type = $msg['type'];
                        if ($type == 'error') {
                            $type = 'danger';
                        }
                    ?>
                    <button class="btn btn-<?=$type?> btn-mini imShowDetailedList"><?=$this->text('infoMessages.im.more')?></button>
                    <div style="display:none;"><?=implode('<br>',$msg['detailedList'])?></div>
                <?endif;?>
            </div>
		<?else:?>
			<div class="alert alert-info">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?=$msg?>
            </div>
		<?endif?>		
	<?endforeach;?>
    <script type="text/javascript">
        $('.imShowDetailedList').click(function(){
            $(this).next('div').show();
            $(this).hide();
        });
    </script>
</div>
<?endif?>
