<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<h3>Statistiky -> Mailová kampaň</h3>

<div class="statistics">

<!--?=$this->render('statsmenu.phtml')?-->

<td>
    <?php 
/*    echo "<br>";
    $mm=  get_object_vars($this->moduleMenu);
    $parametrik = $mm[specific][returnrate][returnrateindex][params][parametrik];
//    echo $parametrik;
//    print_r(get_object_vars($this));
    echo "<br>";
    */
    ?>

</td>
</tr>

<?php
if ( !empty($this->overview) ) {

            // toto vypise prislusny view script
            //ale nejak to nefunguje
            echo $this->layout()->content;

        
$areasCount = $this->areasCount+1;
$overview = $this->overview;
?>

<tr>
<td></td>
<td colspan="2">

    <table class="stat">

        <th>vydání</th>
        <?php        
        
        /**
         * nadpisy tabulky
         */
        for ($i = 0; $i < $areasCount; $i++) {                      
            echo '<th>'.$overview[$i]['name'].'</th>';
        }
        ?>
        <th>všechny segmenty</th>
        
        <?php 
        /**
         * data
         */
       $counter = 0;
       $i = 0;
       $cols = $areasCount + 2;       
       
       //pocet uzivatelu celkem
       $totalUsers = array();
       $_tu = 0;       
       $totalResponse = array();
       $_tr = 0;       
       
       foreach ($overview as $line) {           
           $_tu += $line['send'];           
           $_tr += $line['response'];           
           $counter++;                     
           if ( ($counter == $areasCount) ) {                  
                array_push($totalUsers, $_tu);
                array_push($totalResponse, $_tr);
                $counter = 0;
                $_tu = 0;               
                $_tr = 0;               
           }                      
       }

       // vypis data 
       for ($i = 0; $i < $this->bulletinsCount; $i++) {
           echo '<tr>';
           echo '<td>'.$overview[$i*$areasCount]['bulletin'].'</td>';
           $from = $i*$areasCount;           
           $to = $i*$areasCount+$areasCount;
           
           for ($ii = $from; $ii < $to; $ii++) {               
               $division = $overview[$ii]['send']==0?'-':intval(bcdiv($overview[$ii]['response'], $overview[$ii]['send'])*100);
               echo '<td>';
               echo $overview[$ii]['response'];
               echo ' ('.$division.'%)';                              
               echo '</td>';                 
           };
           $totalDiv = $totalUsers[$i]==0?'-':round(100*$totalResponse[$i]/$totalUsers[$i]).'%';
           echo '<td>'.$totalDiv.'</td>';
           echo '</tr>';       
       }                     
       ?>

    </table>



</td>
</tr>
<?php
    
}
?>

</table>

</div>


<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>
