<?
// Nacteme module menu a specific menu
$moduleMenuData = $this->moduleMenu->getRenderData("forAll");
$specificMenu = $this->moduleMenu->getRenderData("specific");
//pro kazde module menu
$mmenu = "";
$smenu = "";
foreach ($moduleMenuData as $item) {
    // nastavime url
    $url = isset($item['url']) ? $item['url'] : $this->url($item['params'], 'default', !(isset($item['noreset']) && $item['noreset']));
    // zjistime jestli je aktivni
    $active = (isset($item['active']) && $item['active']) ? ' class=" active"' : "";
    $mmenu .= '<li' . $active . '><a href="' . $url . '">' . $item['title'] . '</a></li>' . PHP_EOL;
    // pokud ma submenu jeste specific menu tak ho vygenerujeme, ale pouze pokud je aktivni
    if (!empty($specificMenu) && $active) {
        $smenu = "";
        foreach ($specificMenu as $sitem) {
            // zjistime jestli je aktivni
            $sactive = (isset($sitem['active']) && $sitem['active']) ? ' class=" active"' : "";
            $surl = isset($sitem['url']) ? $sitem['url'] : $this->url($sitem['params'], 'default', !(isset($sitem['noreset']) && $sitem['noreset']));
            $smenu .= '<li' . $sactive . '><a href="' . $surl . '">' . $sitem['title'] . '</a></li>' . PHP_EOL;
        }
    }
}
?> 
<ul class="nav nav-tabs">
    <?= $mmenu ?>
</ul>
<? if ($smenu): ?> 
    <ul class="nav nav-pills">
        <?= $smenu ?>   
    </ul>
<?endif;?>
