<div class="row pmaker">
    <div class="span12">
        <iframe data-wysiwyg-toolbar="<?=$this->wysiwyg_toolbar?>" id="presentation" class="span11" src="<?= $this->pres_index ?>"></iframe>
    </div>

    <?if($this->tpl_index):?><iframe id="pmaker-template" src="<?= $this->tpl_index ?>"></iframe><?endif;?>

    <div class="slides span10">
        <div class="slides-line"><ul id="sortable" class="slides-line-list"></ul></div>
        <div class="slides-template"><strong><?= $this->texts->pmaker->template_slides?></strong><ul id="draggable" class="slides-template-list"></ul></div>
    </div>
    <div class="span2 slides-control">
        <div>
            <span style="font-size:12px;" class="glyphicon glyphicon-search"></span>
            <span style="font-size:20px;display:block;float:right;" class="glyphicon glyphicon-search"></span>
            <div style="margin:5px 2px 15px 2px;" id="pslider"></div>
        </div>
        <a id="slides-save" class="btn btn-large btn-info tip" data-original-title="<?= Ibulletin_Texts::get('pmaker.editor.save_presentation_tooltip') ?>" href="<?= $this->url(array('action' => 'pmakersave')) ?>"><span class="glyphicon glyphicon-floppy-save"></span></a>
         <?if($this->tpl_index):?>
            <a id="slides-settings-show" class="btn btn-large btn-info tip" data-original-title="<?=Ibulletin_Texts::get('pmaker.editor.settings_tooltip')?>" href="#"><span class="glyphicon glyphicon-cog"></span></a>
            <a id="slides-preview" class="btn btn-large btn-info tip" data-original-title="<?=Ibulletin_Texts::get('pmaker.editor.preview_tooltip')?>" href="#"><span class="glyphicon glyphicon-play-circle"></span></a>
         <?endif;?>
         <?if(!$this->tpl_index):?>
            <a id="slides-select-editable" class="btn btn-large btn-info tip" data-original-title="<?=Ibulletin_Texts::get('pmaker.editor.selecteditable_tooltip')?>" href="#"><span class="glyphicon glyphicon-screenshot"></span></a>
            <a id="slides-edit-template" class="btn btn-large btn-info tip" data-original-title="<?=Ibulletin_Texts::get('pmaker.editor.edittemplate_tooltip')?>" href="#"><span class="glyphicon glyphicon-pencil"></span></a>
       <?endif;?>
    </div>  
    <script type="text/javascript">
        var TEXTS = <?=json_encode(Ibulletin_Texts::getSet('admin.pmaker.editor')->toArray());?>;
        <?if($this->json_texts_tpl_name):?>var TEXTS_TPL_NAME = <?= $this->json_texts_tpl_name ?>;<?endif;?>
    </script>
</div>

<?= $this->render('linkpicker.phtml', $this->links); ?>
