<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<h3>Statistiky -> Celkové statistiky</h3>

<?=isset($this->message) ? "<b>$this->message</b>" : '' ?>

<b><a
	href="<?=$this->url(array('controller' => 'statsold',
'action' => 'general'));?>">Celkové statistiky</a></b>

|

<a
	href="<?= $this->url(array('controller' => 'statsold',
'action' => 'bulletins')); ?>">Statistiky pro jednotlivá vydání</a>

<!--
|
<a href="<?= $this->url(array('controller' => 'statsold',
'action' => 'users')); ?>">Jmenný seznam</a>
-->

<br />
&nbsp;

<table>
	<tr>
		<td class="blue"><b>Target</b></td>
		<td class="blue"><?=$this->targetValue?></td>
		<td class="blue">100,00%</td>
		<td></td>
		<td class="blue"><b>Unsubscribed</b></td>
		<td class="blue"><?=$this->unsubscribed?></td>
		<td class="blue"><?=$this->unsubscribedExport?></td>
	</tr>
	<tr>
		<td class="blue"><b>Subscribers</b></td>
		<td class="blue"><?=$this->subscribers?></td>
		<td class="blue"><?=$this->subscribersPercent?>%</td>
		<td class="blue"><?=$this->subscribersExport?></td>
		<td class="blue"><b>Selfregistered</b></td>
		<td class="blue"><?=$this->selfregistered?></td>
		<td class="blue"><?=$this->selfregisteredExport?></td>
	</tr>
</table>

<br />

<div>

<table align="left" style="margin-left: 20px; margin-right: 20px">
	<caption><b>Skupiny</b></caption>
	<?
	//	print_r($group);
	foreach ($this->groups as $group)
	{?>
	<tr>
		<td class="blue"><?=empty($group->group) ? 'nezadáno' : $group->group?></td>
		<td class="blue"><?=$group->users?></td>

		<td class="blue"><a
			href="<?=$this->url(array(
					'controller' => 'statsold',
					'action' => 'export',
					'what' => Admin_StatsoldController::GROUPS_USERS,
					'group' => $group->group
				))?>"><img src="pub/img/admin/icon-xls.png" style="border: none" /></a></td>


	</tr>
	<?}?>
</table>

<table align="left">
	<caption><b>Reprezentanti</b></caption>
	<tr>
		<th></th>
		<th></th>
	</tr>
	<?
	foreach ($this->reps as $rep)
	{?>
	<tr>
		<td class="blue"><?=empty($rep->rep) ? 'nezadáno' : $rep->name.' '.$rep->surname?></td>
		<td class="blue"><?=$rep->users?></td>
		<td class="blue"><?=$this->repsExport?></td>

	</tr>
	<?}?>
</table>
</div>

<br clear=left>
<br>
<table>
	<tr>
		<td class="blue"><b>Readers</b></td>
		<td class="blue"><?=$this->readers?></td>
		<td class="blue"><?=$this->readersPercent?>%</td>
		<td class="blue"><?=$this->readersExport?></td>
	</tr>
</table>





	<?php
	/**
	 echo 'Grafy zde:';
	 //require_once("../../lekarnik/php-include2/phpchartdir.php");
	 require_once("/home/lekarnik/php-include2/phpchartdir.php");

	 #The data for the bar chart
	 $data = array(85, 156, 179.5, 211, 123);

	 #The labels for the bar chart
	 $labels = array($rep->name, "Tue", "Wed", "Thu", "Fri");

	 #Create a XYChart object of size 250 x 250 pixels
	 $c = new XYChart(250, 250);

	 #Set the plotarea at (30, 20) and of size 200 x 200 pixels
	 $c->setPlotArea(30, 20, 200, 200);

	 #Add a bar chart layer using the given data
	 $c->addBarLayer($data);

	 #Set the x axis labels using the given labels
	 $c->xAxis->setLabels($labels);

	 #output the chart
	 //header("Content-type: image/png");
	 //print($c->makeChart2(PNG));
	 $graf1URL = $c->makeSession("chart1");
	 //print_r($this->reps['id']);
	 echo $graf1URL;
	 */
	?>

<!--
<IMG src="/getchart.php?<?php echo $graf1URL ?>">
<IMG src="/graf1.php"> 

<br />
-->

<br />
<br />

<table>
	<tr>
		<td class="blue"><b>Response rate</b></td>
		<!--		<td class="blue">
			<?=isset($this->responseRate) ? $this->responseRate.'%' : '-' ?>
		</td>
-->
		<td class="blue"><?=isset($this->responseRateAvg) ?
		$this->responseRateAvg.'%' : '-' ?></td>
	</tr>
	<tr>
		<td class="blue"><b>Return rate</b></td>
		<!--		<td class="blue">
			<?=isset($this->returnRate) ? $this->returnRate : '-' ?>
		</td>
-->
		<td class="blue"><?=isset($this->returnRateAvg) ?  100*$this->returnRateAvg.'%' : '-' ?>
		</td>
	</tr>
	<tr>
		<td class="blue"><b>Articles</b></td>
		<!--		<td class="blue">
			Průměr přečtených článků: <?=$this->articles?>%
		</td>
-->
		<td class="blue"><?=isset($this->articlesAvg) ? $this->articlesAvg : '-' ?>
		</td>
	</tr>
</table>

<br />

<table>
	<caption><b>Rubriky</b></caption>
	<?
	foreach ($this->categories as $category)
	{?>
	<tr>
		<td class="blue"><?=$category['name']?></td>
		<td class="blue"><?=$category['percent']?>%</td>
	</tr>
	<?}?>
</table>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
	<?=$this->render('admin_bottom.phtml')?>
