<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<h3>Statistiky -> Celkové statistiky</h3>


<?php
require_once("/home/lekarnik/php-include2/phpchartdir.php");

if (isset($this->bulletinsStats) && !empty($this->bulletinsStats)){

    foreach ($this->bulletinsStats as $id => $bulletin){
        $jmeno[] = $bulletin['name'];
        $ctenaru[] = $bulletin['readers'];
    }
    krsort($jmeno);
    krsort($ctenaru);

    #The data for the bar chart
    $data = $ctenaru;

    #The labels for the bar chart
    $labels = $jmeno;

    #Create a XYChart object of size 250 x 250 pixels
    $c = new XYChart(250, 250);

    #Set the plotarea at (40, 20) and of size 200 x 200 pixels
    $c->setPlotArea(40, 20, 200, 200);

    //		$c->setDefaultFonts("times.ttf");
    //		$c->setFontTable(0, "times.ttf");

    # Add a title to the chart using 14 points Times Bold Itatic font
    //		$c->addTitle("Počet čtenářů jednotlivých vydání", "arial.ttf", 12);

    #Add a bar chart layer using the given data
    $c->addBarLayer($data);

    # Add axis title
    $c->yAxis->setTitle("[Počet čtenářů]");

    #Set the x axis labels using the given labels
    $c->xAxis->setLabelStyle("bold");
    $c->xAxis->setLabels($labels);

    $c->setColor(DataColor, 0x3333ff);
    //		$c->setFontTable(0, "arial.ttf");

    $query1 = $c->makeSession("chart1");
}


if (isset($this->DayReaders) && !empty($this->DayReaders)){
    unset($ctenaru);
    foreach ($this->DayReaders as $dayreader){
        $datum[] = date("j.n.", strtotime($dayreader['dates']));
        $ctenaru[] = $dayreader['readers'];
        $rozdil[] = $dayreader['diff'];
    }

    //	ksort($datum);
    //	ksort($ctenaru);

    #The data for the bar chart
    $data = $ctenaru;

    #The labels for the bar chart
    $labels = $datum;

    #Create a XYChart object of size 850x 250 pixels
    $d = new XYChart(850, 250);

    #Set the plotarea at (40, 20) and of size 800 x 200 pixels
    $d->setPlotArea(40, 20, 800, 200);

    # Add a title to the chart using 14 points Times Bold Itatic font
    //	$d->addTitle("Počet čtenářů za 30 dnů", "arial.ttf", 14);

    # Add axis title
    $d->yAxis->setTitle("[Počet čtenářů]");

    #Add a bar chart layer using the given data
    $d->addBarLayer($data);

    #Set the x axis labels using the given labels
    $d->xAxis->setLabels($labels);

    #graf bude modry
    $d->setColor(DataColor, 0x3333ff);

    $query2 = $d->makeSession("chart2");

    #The data for the bar chart
    $data = $rozdil;

    #The labels for the bar chart
    $labels = $datum;

    #Create a XYChart object of size 850x 250 pixels
    $e = new XYChart(850, 250);

    #Set the plotarea at (40, 20) and of size 800 x 200 pixels
    $e->setPlotArea(40, 20, 800, 200);

    # Add a title to the chart using 14 points Times Bold Itatic font
    //	$e->addTitle("Změna počtu čtenářů od minulého dne", "arial.ttf", 14);

    #Add a bar chart layer using the given data
    $e->addBarLayer($data);

    # Add axis title
    $e->yAxis->setTitle("[Počet čtenářů]");

    #Set the x axis labels using the given labels
    $e->xAxis->setLabels($labels);

    #graf bude modry
    $e->setColor(DataColor, 0x3333ff);

    $query3 = $e->makeSession("chart3");
}
?>

<IMG
	SRC="<?=$this->url(array('action' => 'getchart', 'controller' => 'service', 'module' => 'default'))?>?<?php echo $query1 ?>">
<BR />
<IMG
	SRC="<?=$this->url(array('action' => 'getchart', 'controller' => 'service', 'module' => 'default'))?>?<?php echo $query2 ?>">
<BR />
<IMG
	SRC="<?=$this->url(array('action' => 'getchart', 'controller' => 'service', 'module' => 'default'))?>?<?php echo $query3 ?>">



<!--
//graf1.php;
//print $this->graf1;
//Admin_StatsoldController::Graf1();
 -->

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>
