<?=$this->render('head.phtml')?>

<body id="info" class="incampaign">

    <div id="page">

        <div id="head">
            <h3><?=$this->text('title')?></h3>
        </div><!--end.head-->


        <div id="content">
			<p class="s3">
            <?if(empty($this->message)){?>
                <?=sprintf($this->nps ?
                    $this->text('deregisternps.index.confirmation') :
                    $this->text('deregister.index.confirmation'), $this->p2->project_name)?>
            <?}else{?>
                <?=$this->message?>
            <?}?>
            </p>
          <form action="" method="post">
          <fieldset>
          <?if(empty($this->message)){?>
                <button type="submit" class="button w140" name="deregister" value="<?=$this->text('deregister.index.submit')?>" title="<?=
                $this->nps ? $this->text('deregisternps.index.submit') : $this->text('deregister.index.submit')?>"><?=$this->text('deregister.index.submit')?></button>
          <?}?>
             <?if(isset($this->tip)){?>
                <div class="tip">
                <strong>Tip:</strong> <a href="
                    <?=$this->url(array_merge(array(
                                                    'controller' => $this->tip['controller'],
                                                    'action' => $this->tip['action']),
                                              $this->tip['params']),
                                  'default', true)?>">
                                              <?=$this->tip['text']?>
                                      </a>
                </div>
            <?}?>
		</fieldset>
		</form>

            <br><p><small>Pokud se chcete odhlásit z ostatních konkrétních projektů, prosím napište e-mail na <a href="mailto:deregistrace@pearshealthcyber.com">deregistrace@pearshealthcyber.com</a></small></p>

        </div>


        <?=$this->render('bottom_login.phtml')?>
