<?= $this->render('admin_top.phtml') ?>
<div class="row">
    <div class="span8">
        <?= $this->form ?>

        <h3><?= $this->text('category_img') ?></h3>

        <? if (!empty($this->fileUploader)) { ?>
            <?= $this->render('contentFilesUploader.phtml') ?>	
        <? } ?>

        <? if (!empty($this->category_img)) { ?>
            <img src="<?= $this->category_img ?>" alt="category image" />
            <form method="post" action="<?= $this->url(array('controller' => 'categoryadm', 'action' => 'deleteimg', 'module' => 'admin', 'id' => $this->category_id), null, true) ?>">
                <input type="hidden" name="id" value="<?= $this->category_id ?>" /> 
                <input type="submit" name="submit" value="Smazat" />
            </form>
        <? } else { ?>
            <img src="pub/img/admin/noimage.gif" alt="no image" />
        <? } ?>
    </div>
    <div class="span4">
        <?=
        $this->collapse($this->text('help'),null,array(1))
        ?>   
    </div>
</div>
<?= $this->render('admin_bottom.phtml') ?>
