<?=$this->render('admin_top.phtml')?>
<!-- id=submenu -->
<div class="row">
    <div class="span8">
<?=$this->form?>

<?/* Vypis uzivatelu, kteri jsou upozorneni pri pridani noveho prispevku */?>
<h5><?=$this->description?></h5>
<?foreach($this->notifiedUsers as $uid => $name){?>
    <?=$name?> | <a href="<?=$this->url(array('action' => 'removenotified', 'userid'=>$uid))?>" 
        onclick="return confirm('<?=sprintf($this->text('confirm_removenotified'),$name)?>');"><?=$this->text('delete')?></a><br/>
<?}?>
    </div>
    <div class="span4">
        <?= $this->render('contentPreviewLinks.phtml') ?>
        <?=$this->collapse($this->text('help'))?>  
    </div>
</div>
<?=$this->render('admin_bottom.phtml')?>