<? $this->ctexts = Ibulletin_Texts::getInstance('content'); ?>
<h3><?= $this->ctexts->get('description') ?></h3>
<table id="bp_sortable">  
    <thead>
        <tr><th><?= $this->ctexts->get('id') ?></th><th style="width:400px;"><?= $this->ctexts->get('name') ?></th><th><?= $this->ctexts->get('changed') ?></th>
            <th><?= $this->ctexts->get('type') ?></th></tr>
    </thead>
    <tbody>
        <? if ($this->contents): ?>
            <? foreach ($this->contents as $c): ?>
                <tr class="item">
                    <? $obj = $c['content_object'] ?>
                    <td class="desc"><?= $obj->id ?></td>
                    <td><?= $obj->name ?></td>
                    <td><?= date('d. m. Y H:m:s', strtotime($c['changed'])) ?></td>
                    <td><?= preg_replace('/^Ibulletin_Content_/', '', $c['class_name']) ?></td>
                    <td><input type="hidden" name="cont[<?= $obj->id ?>]" value="<?= $obj->id ?>" /></td>
                    <td><a class="delcont" id="<?= $obj->id ?>" href="#"><img src="pub/img/admin/cross.png" alt="<?= $this->ctexts->get('action_remove') ?>" /></a></td>
                </tr>
            <? endforeach; ?>
        <? endif; ?>
    </tbody>
</table>