<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?= $this->render('admin_top.phtml') ?>
<div class="row">
    <div class="span8">
        <?= $this->form ?>
        <h3><?=$this->texts->content->description_available?></h3>
        <?=$this->content_grid?>
    </div>
    <div class="span4">
        <?= $this->render('contentPreviewLinks.phtml') ?>
        <?=$this->collapse($this->text('edit.help'),null,array(1))?>   
    </div>
</div>
<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?= $this->render('admin_bottom.phtml') ?>
