<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<p><?=$this->description?></p>

<?=$this->form?>

<?=$this->grid?>

<div id="edit-dialog" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <h3 id="myModalLabel"><?= $this->texts->edit->heading ?></h3>
    </div>
    <div id="modal-form">
        
    </div>  
</div>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>


