<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<?=$this->chooseBulletinForm?>

<table class="tablesorter">
    <thead>
    <tr>
        <th><?=$this->text('id')?></th>
        <th><?=$this->text('content_id')?></th>
        <th><?=$this->text('name')?></th>
        <th><?=$this->text('thumbnail')?></th>
        <th colspan="1"><?=$this->texts->action?></th>
    </tr>
    </thead>
    <tbody>
    <?foreach($this->pages as $page){?>
        <tr>
            <td><?=$page['page_id']?></td>
            <td><?=$page['content_id']?></td>
            <td><?=$page['page_name']?></td>
            <td><?if(!empty($page['pictogram'])){?><img src="<?=$page['pictogram'].'?t='.time()?>" alt="pictogram" /><?}?></td>
            <td><?if(!empty($page['pictogram'])){?><a href="<?=$this->url(array('contentId' => $page['content_id'], 'regeneratePictogr' => 1))
                ?>"><?=$this->text('action_regenerate')?></a><?}?></td>
        </tr>
    <?}?>
    </tbody>
</table>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>