<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?= $this->render('admin_top.phtml') ?>
<div class="row">
    <div class="span8">
        <div id="players">
            <div id="divswfAVPlayer">
                <h4>Video</h4>
                <? if ($this->videoReady) { ?>
                    <div id="swfAVPlayer"><!--
                                        INSERT NOTIFICATION THE JAVASCRIPT AND FLASH
                                        NEED TO BE ENABLED TO RUN THE PAGE PROPERLY.
                                        NOTIFICATION SHOULD BE HTML SNIPPET OF CODE!
                        -->
                        <p>Pro správnou funkci přehrávače musí váš prohlížeč podporovat
                            JavaScript a Flash.</p>
                        <p><a href="http://www.adobe.com/go/getflashplayer"> <img
                                    src="pub/img/admin/get_flash_player.gif" alt="Get Adobe Flash player" /> </a>
                        </p>
                    </div>
                    <br />
                    <button class="syncButAdd" name="vid">Přidat -&gt; synchronizaci</button>
                    <button class="syncButAdd" name="both">Přidat &lt;-&gt; synchronizaci</button>
                <? } else { ?> <? if (isset($this->videoContents)) { ?> <? /* Vypiseme seznam dostupnych contentu */ ?>
                        <table class="std">
                            <tr>
                                <th>ID</th>
                                <th>Content</th>
                                <th>Akce</th>
                            </tr>
                            <? foreach ($this->videoContents as $content) { ?>
                                <tr>
                                    <td><?= $content['id'] ?></td>
                                    <td><?= $content['object']->name ?></td>
                                    <td><a
                                            href="<?=
                                            $this->url(array('action' => 'addsubcontent',
                                                'contentId' => $content['id']))
                                            ?>">Přidat</a></td>
                                </tr>
                            <? } ?>
        <? if (empty($this->videoContents)) { ?>
                                <tr>
                                    <td colspan=3>Není k dispozici žádný takový content.</td>
                                </tr>
                        <? } ?>
                        </table>
    <? } else { ?> Obsah není připraven k použití, prosím pokračujte editací
                        tohoto obsahu. <? } ?> <? } ?> <? /* Editace tohoto obsahu */ ?> <? if ($this->videoReady || !isset($this->videoContents)) { ?>
                    <br />
                    <a
                        href="<?=
                        $this->url(array('controller' => 'video',
                            'action' => 'edit', 'id' => $this->video_id))
                        ?>">
                        Editovat tento obsah</a> <br />
                    <a
                        href="<?= $this->url(array('action' => 'removesubcontent', 'contentId' => $this->video_id)) ?>">
                        Odebrat toto video z webcastu. </a> <? } ?></div>

            <div id="divswfPTPlayer">
                <h4>Prezentace</h4>
<? if ($this->presentationReady) { ?>
                    <div id="swfPTPlayer"><!--
                                        INSERT NOTIFICATION THE JAVASCRIPT AND FLASH
                                        NEED TO BE ENABLED TO RUN THE PAGE PROPERLY.
                                        NOTIFICATION SHOULD BE HTML SNIPPET OF CODE!
                        -->
                        <p>Pro správnou funkci přehrávače musí váš prohlížeč podporovat
                            JavaScript a Flash.</p>
                        <p><a href="http://www.adobe.com/go/getflashplayer"> <img
                                    src="pub/img/admin/get_flash_player.gif" alt="Get Adobe Flash player" /> </a>
                        </p>
                    </div>
                    <br />
                    <button class="syncButAdd" name="pres">Přidat &lt;- synchronizaci</button>
                    <button id="reloadConfBut">Znovu načíst konfiguraci</button>
<? } else { ?> <? if (isset($this->presentationContents)) { ?> <? /* Vypiseme seznam dostupnych contentu */ ?>
                        <table class="std">
                            <tr>
                                <th>ID</th>
                                <th>Content</th>
                                <th>Akce</th>
                            </tr>
        <? foreach ($this->presentationContents as $content) { ?>
                                <tr>
                                    <td><?= $content['id'] ?></td>
                                    <td><?= $content['object']->name ?></td>
                                    <td><a
                                            href="<?=
            $this->url(array('action' => 'addsubcontent',
                'contentId' => $content['id']))
            ?>">Přidat</a></td>
                                </tr>
        <? } ?>
                            <? if (empty($this->presentationContents)) { ?>
                                <tr>
                                    <td colspan=3>Není k dispozici žádný takový content.</td>
                                </tr>
        <? } ?>
                        </table>
    <? } else { ?> Obsah není připraven k použití, prosím pokračujte editací
                        tohoto obsahu. <? } ?> <? } ?> <? /* Editace tohoto obsahu */ ?> <? if ($this->presentationReady || !isset($this->presentationContents)) { ?>
                    <br />
                    <a
                        href="<?=
    $this->url(array('controller' => 'presentation',
        'action' => 'edit', 'id' => $this->presentation_id))
    ?>">
                        Editovat tento obsah</a> <br />
                    <a
                        href="<?= $this->url(array('action' => 'removesubcontent', 'contentId' => $this->presentation_id)) ?>">
                        Odebrat tuto prezentaci z webcastu </a> <? } ?></div>
        </div>
        <div class="reset"></div>
<?= $this->form ?>

<? if ($this->videoReady && $this->presentationReady) { ?>
            <div class="functionsdiv"><? /* Ovladani syncpointuu */ ?>

                <form action=""><input type="checkbox" id="connectPlayers"
                                       checked="checked" /> <label for="connectPlayers"
                                       id="connectPlayersLabel">Propojit přehrávače</label></form>

                <div id="divWorkingIndicator">
                    <div id="workingIndicator">Probíhá zpracování požadavku...</div>
                </div>

                <div class="divFunction1">
                    <h4>Synchronizace video -&gt; prezentace</h4>
                    <table id="syncTabVideo" class="std">
                        <thead>
                            <tr>
                                <th>Čas</th>
                                <th>Slide</th>
                                <th>Akce</th>
                            </tr>
                        </thead>
                        <tbody>
    <? foreach ($this->videoSyncTable as $key => $item) { ?>
                                <tr>
                                    <td><?= $item['time'] ?></td>
                                    <td><?= $item['slide'] ?></td>
                                    <td>
                                        <button class="syncButRemove" name="<?= $item['timems'] ?>">Odstranit</button>
                                    </td>
                                </tr>
    <? } ?>
                        </tbody>
                    </table>
                </div>

                <div class="divFunction2">
                    <h4>Synchronizace prezentace -&gt; video</h4>
                    <table id="syncTabPres" class="std">
                        <thead>
                            <tr>
                                <th>Čas</th>
                                <th>Slide</th>
                                <th>Akce</th>
                            </tr>
                        </thead>
                        <tbody>
    <? foreach ($this->presSyncTable as $key => $item) { ?>
                                <tr>
                                    <td><?= $item['time'] ?></td>
                                    <td><?= $item['slide'] ?></td>
                                    <td>
                                        <button class="syncButRemove" name="<?= $item['timems'] ?>">Odstranit</button>
                                    </td>
                                </tr>
    <? } ?>
                        </tbody>
                    </table>
                </div>

                <div class="reset"></div>
                <br />
                <br />
            </div>
            <? } ?>

        <div>
            <h4>Další contenty obsažené v tomto webcastu</h4>
                <? if ($this->contentHasPage) { ?>
                <div class="divFunction1">
                    <h4>Článek/dotazník</h4>
                        <? if ($this->articleIncluded) { ?> ID: <?= $this->articleIncluded['id'] ?> |
        <?= $this->articleIncluded['name'] ?> | <a
                            href="<?=
                            $this->url(array('id' => $this->articleIncluded['id'],
                                'action' => 'edit', 'controller' => $this->articleIncluded['editcontroller']))
                            ?>">
                            editovat</a> | <a
                            href="<?=
                    $this->url(array('contentId' => $this->articleIncluded['id'],
                        'action' => 'removesubcontent'))
                    ?>"> odebrat</a> <? } else { ?>
                            <? /* Vypiseme seznam dostupnych contentu */ ?>
                        <table class="std">
                            <tr>
                                <th>ID</th>
                                <th>Content</th>
                                <th>Akce</th>
                            </tr>
                                        <? foreach ($this->articleList as $content) { ?>
                                <tr>
                                    <td><?= $content['id'] ?></td>
                                    <td><?= $content['object']->name ?></td>
                                    <td><a
                                            href="<?=
                    $this->url(array('action' => 'addsubcontent',
                        'contentId' => $content['id']))
                                            ?>">Přidat</a></td>
                                </tr>
                        <? } ?>
        <? if (empty($this->articleList)) { ?>
                                <tr>
                                    <td colspan=3>Není k dispozici žádný takový content.</td>
                                </tr>
                            <? } ?>
                        </table class="std">
                        <? } ?></div>
                <div class="divFunction1">
                    <h4>Diskuze</h4>
                        <? if ($this->opinionsIncluded) { ?> ID: <?= $this->opinionsIncluded['id'] ?>
                        | <?= $this->opinionsIncluded['name'] ?> | <a
                            href="<?=
                    $this->url(array('id' => $this->opinionsIncluded['id'],
                        'action' => 'edit', 'controller' => $this->opinionsIncluded['editcontroller']))
                    ?>">
                            editovat</a> | <a
                            href="<?=
                    $this->url(array('contentId' => $this->opinionsIncluded['id'],
                        'action' => 'removesubcontent'))
                    ?>"> odebrat</a> <? } else { ?>
        <? /* Vypiseme seznam dostupnych contentu */ ?>
                        <table class="std">
                            <tr>
                                <th>ID</th>
                                <th>Content</th>
                                <th>Akce</th>
                            </tr>
                            <? foreach ($this->opinionsList as $content) { ?>
                                <tr>
                                    <td><?= $content['id'] ?></td>
                                    <td><?= $content['object']->name ?></td>
                                    <td><a
                                            href="<?=
                    $this->url(array('action' => 'addsubcontent',
                        'contentId' => $content['id']))
                                ?>">Přidat</a></td>
                                </tr>
        <? } ?>
        <? if (empty($this->opinionsList)) { ?>
                                <tr>
                                    <td colspan=3>Není k dispozici žádný takový content.</td>
                                </tr>
        <? } ?>
                        </table class="std">
    <? } ?></div>
        <? } else { ?>
                <p>Tento webcast nemá vytvořenou stránku (page), proto není možné
                    přidávat další contenty. <br />
                    <a
                        href="<?= $this->url(array('id' => $this->id, 'action' => 'createsimplepage')) ?>">
                        Vytvořit prostou stránku s tímto obsahem </a></p>
        <? } ?></div> 

        <div class="reset"></div>
        <br />

<?= $this->render('filemanager.phtml') ?>	
    </div>
    <div class="span4">
<?= $this->render('contentPreviewLinks.phtml') ?>
<?=
$this->collapse(
        $this->text('help'),null,array(1)
)
?>    
    </div>
</div>
<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?= $this->render('admin_bottom.phtml') ?>

