<?=$this->render('admin_top.phtml')?>

<h3><?=$this->moduleTitle?></h3>


<? if(!empty($this->info_messages)){?>
<b>Info:</b>
<br />
<?foreach($this->info_messages as $message){?>
<?=$message?>
<br />
<?}?>
<?}?>

<?/*Vypiseme seznam dostupnych contentu*/?>
<table class="stat">
	<tr>
		<th>ID</th>
		<th>Content</th>
		<th>Akce</th>
	</tr>
	<?foreach($this->contentList as $content){?>
	<tr>
		<td><?=$content['id']?></td>
		<td><?=$content['object']->name?></td>
		<td><?if($content['id'] != $this->currentMainContent){?> <a
			href="<?=$this->url(array('id' => $content['id']))?>">Použít</a></td>
			<?}else{?>
		Aktuálně použitý
		<?}?>
	</tr>
	<?}?>
	<?if(empty($this->contentList)){?>
	<tr>
		<td colspan=3>Není k dispozici žádný takový content.</td>
	</tr>
	<?}?>
</table>

	<?=$this->form?>

	<?=$this->render('admin_bottom.phtml')?>