<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?= $this->render('admin_top.phtml') ?>
<div class="row">
    <div class="span8">
        <p><?= $this->description ?></p>
        <?= $this->form ?>
        <?= $this->orderform ?>
        <script>
            $('#bp_sortable').sortable({
                items: 'tr.item',
                axis: 'y'
            });

            $('.delete-menu').click(function () {

                if (confirm('<?= $this->texts->menuitem_delete_confirm ?>')) {
                    return true;
                }

                return false;
            })
        </script>
        <?= $this->render('linkpicker.phtml', $this->links); ?>
    </div>
    <div class="span4">
        <?= $this->collapse($this->text('help'), null, array(1)) ?>   
    </div>
</div>
<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?= $this->render('admin_bottom.phtml') ?>
