<?= $this->render('admin_top.phtml') ?>

<div id="search-avpage"><input style="z-index:50" class="typeahead input-xlarge" type="text" placeholder="<?=$this->text('search')?>"></div>
<?if($this->detail_title):?>
<h3><?= $this->detail_title ?> <a style="font-size:12px;" href="<?=$this->detail_title_url?>"><span class="glyphicon glyphicon-edit"></span></a></h3>
<?endif;?>

<script type="text/javascript">
    var pagesdata = <?= json_encode($this->pages_all) ?>;
    var bulletinsdata = <?= json_encode($this->bulletins_all) ?>;
    var repsdata = <?= json_encode($this->reps_all) ?>;
    var segmentsdata = <?= json_encode($this->segments_all) ?>;

    var pages = new Bloodhound({
        local: $.map(pagesdata, function (page) {
            return {
                type: 'page',
                id: page['page_id'],
                name: page["name"]
            };
        }),
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name', 'id'),
        queryTokenizer: Bloodhound.tokenizers.whitespace
    });

    var bulletins = new Bloodhound({
        local: $.map(bulletinsdata, function (bulletin) {
            return {
                type: 'bulletin',
                id: bulletin['id'],
                name: bulletin["name"]
            };
        }),
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name', 'id'),
        queryTokenizer: Bloodhound.tokenizers.whitespace
    });

    var reps = new Bloodhound({
        local: $.map(repsdata, function (rep) {
            return {
                type: 'rep',
                id: rep['id'],
                name: rep["surname"] + ' ' + (rep["name"] || '')
            };
        }),
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name', 'id'),
        queryTokenizer: Bloodhound.tokenizers.whitespace
    });
    var segments = new Bloodhound({
        local: $.map(segmentsdata, function (segment) {
            return {
                type: 'segment',
                id: segment['id'],
                name: segment["name"]
            };
        }),
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name', 'id'),
        queryTokenizer: Bloodhound.tokenizers.whitespace
    });

    var users = new Bloodhound({
        remote: {
            url: '<?= $this->url(array('module' => 'admin', 'controller' => 'users', 'action' => 'getuser'), null, true) ?>?q=%QUERY',
            filter: function (users) {
                return $.map(users, function (user) {
                    return {
                        type: 'user',
                        id: user['id'],
                        name: user["surname"] + ' ' + (user["name"] || '')
                    };
                });
            }
        },
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name', 'id'),
            queryTokenizer: Bloodhound.tokenizers.whitespace
        });

    pages.initialize();
    bulletins.initialize();
    reps.initialize();
    segments.initialize();
    users.initialize();

    $(".typeahead").typeahead({
        highlight: true,
        hint: true,
        minLength: 1
    }, {
        source: pages.ttAdapter(),
        displayKey: "name",
        templates: {
            header: "<h3><?=$this->text('pages')?></h3>",
            suggestion: function (data) {
                return '[' + data.id + '] ' + data.name;
            }
        }
    },
    {
        source: bulletins.ttAdapter(),
        displayKey: "name",
        templates: {
            header: "<h3><?=$this->text('bulletins')?></h3>",
            suggestion: function (data) {
                return '[' + data.id + '] ' + data.name;
            }
        }
    },
    {
        source: reps.ttAdapter(),
        displayKey: "name",
        templates: {
            header: "<h3><?=$this->text('representatives')?></h3>",
            suggestion: function (data) {
                return '[' + data.id + '] ' + data.name;
            }
        }
    },
    {
        source: segments.ttAdapter(),
        displayKey: "name",
        templates: {
            header: "<h3><?=$this->text('segments')?></h3>",
            suggestion: function (data) {
                return '[' + data.id + '] ' + data.name;
            }
        }
    },
    {
        source: users.ttAdapter(),
        displayKey: "name",
        templates: {
            header: "<h3><?=$this->text('users')?></h3>",
            body: '<div style="float:left"></div>',
            suggestion: function (data) {
                return '[' + data.id + '] ' + data.name;
            }
        }
    }
    ).on('typeahead:selected', function (e, datum) {
        window.location = "<?= $this->url(array('module' => 'admin', 'controller' => 'testing', 'action' => 'availablepages'),null,true) ?>" + datum.type + "/" + datum.id;
    });
    $('.typeahead').on('keyup', function (e) {
        if (e.which === 13) {
            $(".tt-suggestion:eq(0)").trigger('click');
        }
    });

</script>
<div class="row available-page-directory">
    <? if ($this->reps): ?>
        <div class="span3">
            <div class="well well-small">
                <div class="nav-header"><?=$this->text('representatives')?> (<?= count($this->reps) ?>)</div>
                <ul class="menulist">
                    <? foreach ($this->reps as $r): ?>
                        <li><a href="<?= $this->url(array('module' => 'admin', 'controller' => 'testing', 'action' => 'availablepages', 'rep' => $r['id']),null,true) ?>">[<?= $r['id'] ?>] <?= $r['surname'] ?> <?= $r['name'] ?></a>
                        <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'users', 'action' => 'edit', 'id' => $r['id']),null,true) ?>"><span class="glyphicon glyphicon-edit"></span></a></li>
                    <? endforeach; ?>   
                </ul>
            </div>
        </div>
    <? endif; ?>
    <? if ($this->segments): ?>
        <div class="span3">
            <div class="well well-small">
                <div class="nav-header"><?=$this->text('segments')?> (<?= count($this->segments) ?>)</div>
                <ul class="menulist">
                    <? foreach ($this->segments as $s): ?>
                        <li><a href="<?= $this->url(array('module' => 'admin', 'controller' => 'testing', 'action' => 'availablepages', 'segment' => $s['id']),null,true) ?>"><?= '[' . $s['id'] . '] ' . $s['name'] ?></a>
                            <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'users', 'action' => 'segmentsedit', 'id' => $s['id']),null,true) ?>"><span class="glyphicon glyphicon-edit"></span></a></li>
                    <? endforeach; ?>   
                </ul>
            </div>
        </div>
    <? endif; ?>
    <? if ($this->pages): ?>
        <div class="span3">
            <div class="well well-small">
                <div class="nav-header"><?=$this->text('pages')?> (<?= count($this->pages) ?>)</div>
                <ul class="menulist">
                    <? foreach ($this->pages as $p): ?>
                        <li><a href="<?= $this->url(array('module' => 'admin', 'controller' => 'testing', 'action' => 'availablepages', 'page' => $p['page_id']),null,true) ?>">[<?= $p['page_id'] ?>] <?= $p['name'] ?></a>
                        <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'pages', 'action' => 'edit', 'id' => $p['page_id']),null,true) ?>"><span class="glyphicon glyphicon-edit"></span></a></li>
                    <? endforeach; ?>   
                </ul>
            </div>
        </div>
    <? endif; ?>
    <? if ($this->users): ?>
        <div class="span3">
            <div class="well well-small">
                <div class="nav-header"><?=$this->text('users')?> (<?= count($this->users) ?>)</div>
                <ul class="menulist">
                    <? foreach ($this->users as $k => $u): ?>
                        <li><a href="<?= $this->url(array('module' => 'admin', 'controller' => 'testing', 'action' => 'availablepages', 'user' => $k), null, true) ?>">[<?= $k ?>] <?= $u ?></a>
                        <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'users', 'action' => 'edit', 'id' => $k),null,true) ?>"><span class="glyphicon glyphicon-edit"></span></a></li>
                    <? endforeach; ?>  
                </ul>
            </div>
        </div>
    <? endif; ?>
    <? if ($this->bulletins): ?>
        <div class="span3">
            <div class="well well-small">
                <div class="nav-header"><?=$this->text('bulletins')?> (<?= count($this->bulletins) ?>)</div>
                <ul class="menulist">
                    <? foreach ($this->bulletins as $b): ?>
                        <li><a <?=(($b['hidden']) ? 'style="color:#999"':'')?> href="<?= $this->url(array('module' => 'admin', 'controller' => 'testing', 'action' => 'availablepages', 'bulletin' => $b['id']),null,true) ?>"><?= '[' . $b['id'] . '] ' . $b['name'] ?></a>
                        <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'bulletinassembler', 'action' => 'edit', 'id' => $b['id']),null,true) ?>"><span class="glyphicon glyphicon-edit"></span></a></li>
                    <? endforeach; ?>     
                </ul>
            </div>
        </div>
    <? endif; ?>
</div>
<?= $this->render('admin_bottom.phtml') ?>