<?= $this->render('admin_top.phtml') ?>
<div class="row">
    <div class="span8">
        <form method="get" class="form-inline">
            <label><?= $this->texts->slides->select_content_label ?></label><?= $this->formSelect('id', $this->contentID, array('class' => 'selectpicker form-inline'), $this->indetail_list) ?>
            <?= $this->formSubmit('send', $this->texts->slides->content_choose, array('class' => 'btn btn-primary')) ?>
        </form>
        <? if (isset($this->contentID)): ?>
            <h3><?= $this->indetail_name ?></h3>

            <? foreach ($this->slides as $slide): ?>
                <div class="test-slide well well-small">
                    <h4><span class="badge badge-info"><?= $slide['num'] ?></span><?= $slide['name'] ?></h4>
                    <div class="slide-preview pull-left">
                        <? if (isset($this->slide_previews[$slide['num']])): ?>
                            <img src="<?= $this->slide_previews[$slide['num']] ?>"/>
                        <? else: ?>
                            <span class="muted"><?= $this->texts->slides->no_preview ?></span>
                        <? endif ?>
                    </div>
                    <div class="pull-left">
                        <span>
                            <? if ($slide['mandatory']): ?>
                                <i class="icon-ok"></i>
                            <? else: ?>
                                <i class="icon-remove"></i> 
                            <? endif ?>
                            <?= $this->texts->slides->mandatory ?></span>

                        <? if ($slide['questions']): ?>
                            <h5 class="test-slide-question-title"><?= $this->texts->slides->questions ?>:</h5>
                            <ul class="test-slide-questions">
                                <? foreach ($slide['questions'] as $q): ?>
                                    <li><span class="badge badge-inverse"><?= $q['num'] ?></span>
                                        <strong><?= $q['text'] ?></strong> [<?= $this->question_types[$q['type']] ?>]</li>
                                    <? if ($q['answers']): ?>
                                        <li>
                                            <h5 class="test-slide-answer-title"><?= $this->texts->slides->answers ?>:</h5>
                                            <ul><? foreach ($q['answers'] as $a): ?>
                                                    <li><span class="badge badge-success"><?= $a['num']; ?></span> <?= $a['text'] ?></li>
                                                <? endforeach ?>
                                            </ul>
                                        </li>
                                    <? endif ?>
                                <? endforeach; ?>
                            </ul>
                        <? endif ?>

                    </div>
                    <div class="clearfix"></div>

                </div>
            <? endforeach; ?>

            <? if (count($this->slides) == 0): ?>
                <div class="well well-small">
                    <?= $this->texts->slides->no_slides ?>
                </div>
            <? endif; ?>
        <? endif ?>
    </div>
</div>
<?=
$this->render('admin_bottom.phtml')?>