<?= $this->render('admin_top.phtml') ?>
<div class="row">
    <div class="span8">
        <?= $this->form ?>

        <? if ($this->presentationReady): ?>
            <div id="players">
                <div id="div<?= $this->playerHtmlElemId ?>">
                    <div id="<?= $this->playerHtmlElemId ?>"><!--
                                    INSERT NOTIFICATION THE JAVASCRIPT AND FLASH
                                    NEED TO BE ENABLED TO RUN THE PAGE PROPERLY.
                                    NOTIFICATION SHOULD BE HTML SNIPPET OF CODE!
                        -->
                        <p>Pro správnou funkci přehrávače musí váš prohlížeč podporovat
                            JavaScript a Flash.</p>
                        <p><a href="http://www.adobe.com/go/getflashplayer"> <img
                                    src="pub/img/admin/get_flash_player.gif" alt="Get Adobe Flash player" /> </a>
                        </p>
                    </div>           
                </div>
            </div>   
        <? endif; ?>

        <?= $this->render('filemanager.phtml') ?>	
    </div>
    <div class="span4">
        <?= $this->render('contentPreviewLinks.phtml') ?>
        <?=
        $this->collapse(
                $this->text('help'), 
                null,
                array(1)
        )
        ?>    
    </div>
</div>
<?=
$this->render('admin_bottom.phtml')?>