<?$only_one_in_cat = (count($this->annotations) == 1)?>
<?/*<ul class="vytah<?=!$this->cfg->show_article_annot ? ' vytah_bez_anotaci' : ''?>">*/?>
<?foreach($this->annotations as $annotation){?>
        <?$odkaz = $this->url($annotation['url']['params'], $annotation['url']['route']);?>
        <h3>
            <a href="<?=$odkaz?>">
                <?if(!empty($this->cfg->only_one_article_in_category_text) && $only_one_in_cat){?>
                    <?$annotation['name'] = $this->cfg->only_one_article_in_category_text?>
                <?}?>
                <?=$annotation['name']?>
            
            </a>
        </h3>
        <?if(!empty($this->cfg->only_one_article_in_category_text) && $only_one_in_cat){?>
            <p class="cist">&nbsp;</p>
        <?}elseif(!empty($this->cfg->show_article_annot)){?>
            <p><?=$annotation['annotation']?></p>
            <p class="cist"><a href="<?=$odkaz?>">číst celý článek</a></p>
        <?}?>
<?}?>

