<?=$this->render('top.phtml')?>
<?$this->cfg = $this->config->general->main_page?>
<div id="hp">
			
    <h1>Vydání: 
    <span><?=$this->bulletin_name?></span></h1>
    
    <?end($this->annotations_by_cat); $last_item = key($this->annotations_by_cat);?>
        <?foreach($this->annotations_by_cat as $key => $annot_in_cat){?>
            <?if($key == $last_item){?>
                <div class="clanek last">
            <?}else{?>
                <div class="clanek">
            <?}?>
            
            <h2><?=$annot_in_cat[0]['category']?></h2>
            
            <?if($this->cfg->show_category_annot){?>
                <p class="mar1"><?=$annot_in_cat[0]['category_annotation']?></p>
            <?}?>
            <?$this->annotations = $annot_in_cat?>
            
            <?=$this->render('bulletin/list-articles.phtml')?>
            
            </div>
        <?}?>
</div>

<?=$this->render('bottom.phtml')?>

