<?=$this->render('admin_top.phtml')?>
<div class="row">
    <div class="span8">
        <p><?=$this->description?></p>
        <?=$this->form?>
        <?=$this->grid?>
    </div>
    <div class="span4">
        <?if(Zend_Controller_Front::getInstance()->getRequest()->getActionName() == "landing"):?>
            <?=$this->collapse($this->text('help'),array('landing_url'=>array(
                'title' => $this->text('url_help_title'),
                'body' => $this->render('templates/landing_url.phtml')
            )), array(1,2))?>
        <?else:?>
            <?=$this->collapse($this->text('help'),null, array(1))?>
        <?endif;?>
    </div>
</div>
<?=$this->render('admin_bottom.phtml')?>
