<?
//seznam vstupních stránek s url

$ep = Templates::getComeInPagesTexts(Templates::getAllEntryMetohods());

$pages = array();
$regs = array('emailregister', 'register', 'emaillogin');

foreach ($ep as $k => $p) {
    $cont = 'index';
    if (in_array($k, $regs)) {
        $cont = 'register';
    }
    $u = $this->serverUrl() . $this->url(array('module' => 'default', 'controller' => $cont, 'action' => $k));
    $pages[$p] = '<a target="_blank" href="'.$u.'">'.$u.'</a>';
}
?>
<? foreach ($pages as $page => $url): ?>
    <h5><strong><?= $page ?></strong></h5>
    <p><?= $url ?></p>
<? endforeach; ?>    

 
