<?=$this->render('admin_top.phtml')?>
<h3>Testování komunikace z iPadu do inBoxu</h3>

<h4>URLS</h4>
<div id="urls"></div>
<h4>login</h4>
<div id="login"></div>
<h4>getUsers</h4>
<div id="getUsers"></div>
<h4>sendUsersData</h4>
<div id="sendData"></div>


<script type="text/javascript">
<!--

    // Barthel Jung - heslo "52c80d53d1a5f395ed8b42a75d31fbf7", login "barthel"
    var login = 'barthel';
    var passMd5 = '52c80d53d1a5f395ed8b42a75d31fbf7';
    //var params = '?login='+login+'&pass='+passMd5;
    var url = '/PHC/inDetail/www/service/static/indetail/ipad/operation/';




    $("#urls").append("<p><code>"+url+"</code></p>");
    $.post(url+'login/', {login:login, pass:passMd5}, function(data){
        $("#login").append("<p><code>"+data+"</code></p>");
        var info = $.evalJSON(data);
        var repreId = info.representant.id;
        var pres = info.presentations;

         // Provedeme ziskani uzivatelu
        $("#urls").append("<p><code>"+url+'getUsers/'+"</code></p>");
        $.post(url+'getUsers/', {login:login, pass:passMd5}, function(data){
            $("#getUsers").append("<p><code>"+data+"</code></p>");
            var users = $.evalJSON(data).users;


            // Data pro odeslani z iPadu
            var slides = {
                    slides:[
                            {
                                id:1,
                                presentationId:pres[0].id,

                                userId:users[0].id,
                                repreId:repreId,
                                timestampStart:"2011-05-22 11:45:25+02",
                                timestampSaved:"2011-05-22 11:49:56+02",
                                saveAction:"nextSlide",
                                timeSlide:220000,
                                timeTotal:220000,
                                slideOn:2,
                                points:0,
                                questions:[
                                    {
                                        id:1,
                                        type:"bool",
                                        answer:true
                                    },
                                    {
                                        id:2,
                                        type:"int",
                                        answer:235
                                    },
                                    {
                                        id:3,
                                        type:"radio",
                                        answer:3

                                    },
                                    {
                                        id:4,
                                        type:"checkbox",
                                        answer:[2,4,7]

                                    },
                                    {
                                        id:5,
                                        type:"text",
                                        answer:"Nejaky text v odpovedi 1."
                                    },
                                    {
                                        id:6,
                                        type:"float",
                                        answer:37.689
                                    }
                                ]
                            },
                            {
                                id:2,
                            presentationId:pres[0].id,

                                userId:users[0].id,
                                repreId:repreId,
                                timestampStart:"2011-05-22 11:41:25+02",
                                timestampSaved:"2011-05-25 11:47:56+02",
                                saveAction:"nextSlide",
                                timeSlide:220000,
                                timeTotal:220000,
                                slideOn:3,
                                points:0,
                                questions:[
                                    {
                                        id:1,
                                        type:"bool",

                                        answer:true
                                    },
                                    {
                                        id:2,
                                        type:"int",
                                        answer:236
                                    },
                                    {
                                        id:3,
                                        type:"radio",
                                        answer:3

                                    },
                                    {
                                        id:4,
                                        type:"checkbox",
                                        answer:[3,4,8]

                                    },
                                    {
                                        id:10,
                                        type:"text",
                                        answer:"Nejaky text v odpovedi 2."
                                    },
                                    {
                                        id:6,
                                        type:"float",
                                        answer:38.689
                                    }
                                ]
                            },

                            {
                                id:1,
                                presentationId:pres[1].id,

                                userId:users[0].id,
                                repreId:repreId,
                                timestampStart:"2011-05-22 11:10:25+02",
                                timestampSaved:"2011-05-24 11:12:56+02",
                                saveAction:"nextSlide",
                                timeSlide:220000,
                                timeTotal:220000,
                                slideOn:2,
                                points:0,
                                questions:[
                                    {
                                        id:1,
                                        type:"bool",

                                        answer:true
                                    },
                                    {
                                        id:2,
                                        type:"int",
                                        answer:237
                                    },
                                    {
                                        id:3,
                                        type:"radio",
                                        answer:5

                                    },
                                    {
                                        id:6,
                                        type:"checkbox",
                                        answer:[4,6,8]

                                    },
                                    {
                                        id:7,
                                        type:"text",
                                        answer:"Nejaky text v odpovedi 3."
                                    },
                                    {
                                        id:9,
                                        type:"float",
                                        answer:39.689
                                    }
                                ]
                            },


                            {
                                id:1,
                                presentationId:pres[1].id,

                                userId:users[1].id,
                                repreId:repreId,
                                timestampStart:"2011-05-22 11:50:25+02",
                                timestampSaved:"2011-05-22 11:55:56+02",
                                saveAction:"nextSlide",
                                timeSlide:220000,
                                timeTotal:220000,
                                slideOn:2,
                                points:0,
                                questions:[
                                    {
                                        id:1,
                                        type:"bool",
                                        answer:false
                                    },
                                    {
                                        id:2,
                                        type:"int",
                                        answer:1
                                    },
                                    {
                                        id:3,
                                        type:"radio",
                                        answer:2

                                    },
                                    {
                                        id:4,
                                        type:"checkbox",
                                        answer:[1,2,3]

                                    },
                                    {
                                        id:5,
                                        type:"text",
                                        answer:"Nejaky text v odpovedi 4."
                                    },
                                    {
                                        id:6,
                                        type:"float",
                                        answer:39.689
                                    }
                                ]
                            }

                        ]
                    };
            var sendSlides = $.toJSON(slides);

             // Provedeme ziskani uzivatelu
            $.post(url+'sendUsersData/', {login:login, pass:passMd5, 'data':sendSlides}, function(data){
                $("#sendData").append("<p><code>DONE <br/>"+data+"</code></p>");
            });

        });
    });


//-->
</script>

<?=$this->render('admin_bottom.phtml')?>
