<?$this->contentData = $this->content[$this->current_content]['data'] ?>
<div id="poradna">

	<?= eval($this->content[1]['consulting_html'])?>

	<? if (isset($this->emailErrorMessage)) { ?>
	  <p><strong><?=$this->emailErrorMessage?></strong><br/><br/></p>
    <?}?>

	<? if (isset($this->questionErrorMessage)) {?>
		<p><strong><?=$this->questionErrorMessage?></strong><br/><br/></p>
	<?}?>
	
	<? if (isset($this->questionSendInfoMessage)) {?>
		<p><strong><?=$this->questionSendInfoMessage?></strong><br/><br/></p>
	<?}?>
	
    <?if($this->action == Ibulletin_Content_Consulting::FIRST_PAGE){?>
	    <?=eval($this->content[1]['consulting_form'])?>
    <?}?>

	<div class="zdotaz">
		
		<?if (empty($this->content[1]['consulting_questions']) && 
            $this->action !== Ibulletin_Content_Consulting::REPLY) {?>
            <h2>Zodpovězené dotazy</h2>
            <div class="zdotaz-in">
			    <p>Zatím nebyly položeny žádné dotazy.</p>
		<?}elseif($this->action !== Ibulletin_Content_Consulting::REPLY){?>
                <h2>Zodpovězené dotazy</h2>
                <div class="zdotaz-in">
                
                <?if($this->action == Ibulletin_Content_Consulting::FIRST_PAGE){?>
                    <?foreach($this->content[1]['consulting_questions'] as $question) { ?>
                        <p><strong><?=$question->question?></strong><br />
                            <em><?=$question->reply?></em>
                        </p>
                    <?}?>
                <?}elseif($this->action == Ibulletin_Content_Consulting::ALL_REPLIES){?>
                    <?/*Kdyz vypisujeme vsechny dotazy, pouzivame jiny format*/?>
                    <?foreach($this->content[1]['consulting_questions'] as $question) { ?>
                        <p>
                            <em><?=$question->date?></em><br />
                            <strong><?=$question->question?></strong><br />
                            <a href="<?=$question->replyHref?>">Přečtěte si odpověď</a>
                        </p>
                    <?}?>
                    
                    <div class="pager">
                        <div class="predchozi"><a href="<?=$this->back?>" class="predchozi">Zpět</a></div>
                        <?if(!empty($this->paging)){?>
                            <p class="nasledujici">Další odpovědi: <?=$this->paging?></p>
                        <?}?>
                    </div>
                <?}?>
          <?}else{?>
              <h2>Odpověď na dotaz</h2>
              <div class="zdotaz-in">
              
               <?if (!empty($this->content[1]['consulting_question'])) {?>
                   <p>
                       <em><?=$this->content[1]['consulting_question']->date?></em><br />
                       <strong><?=$this->content[1]['consulting_question']->question?></strong><br />
                       <em><?=$this->content[1]['consulting_question']->reply?></em>
                   </p>
                <?}else{?>
                    <p><strong>Nebyl nalezen daný dotaz.</strong></p>
                <?}?>
                
                <div class="pager"><strong><div class="predchozi"><a href="<?=$this->back?>" class="predchozi">Zpět</a></div></strong></div>
          <?}?>

		</div>
		
		<div class="reset"></div>
	
	</div>
</div>
<?if(isset($this->allQuestionsHref)){?>
    <div class="pager">
        <a href="<?=$this->allQuestionsHref?>" class="nasledujici">Všechny zodpovězené dotazy</a>
    </div>
<?}?>
