<?Ibulletin_Texts::setActualContext("indetail", "content"); ?>
<?$data = $this->content[$this->current_content]['data'] ?>

<?$config = Zend_Registry::get('config');?>


<?$flashWidth = ($this->content[$this->current_content]['obj']->flashWidth ? $this->content[$this->current_content]['obj']->flashWidth : '1000'); ?>
<?$flashHeight = ($this->content[$this->current_content]['obj']->flashHeight ? $this->content[$this->current_content]['obj']->flashHeight : '550'); ?>

<?
    //v pripade, ze je v konfiguraci povoleno zobrazeni indetailu v iframe, renderujeme iframe s url na RendercontentController s parametrem iframe=1
    // Az teprve s timto parametrem se provede skutecny render contentu.
    if ($this->content[$this->current_content]['data']->renderToIframe) {
        $url = $this->url(array('controller' => 'rendercontent', 'action' => 'render', 'content' =>  $data->contentId, 'iframe' => '1'), 'default', true);
        echo "<iframe src=\"".$url."\" style=\"border:none; width: ".$flashWidth."px; height: ".$flashHeight."px;\"></iframe>";
        return;
    }
?>

<?$swfFilePath = $config->content_article->basepath.$data->contentId."/flash/runtime.swf";?>
<?$swfFilePath = Zend_Filter::filterStatic($swfFilePath, 'NormPath');?> 
<?$saverUrl = $this->url(array('contentid' => $data->contentId,'srvname' => 'save','pageviewsid' => $data->pageViewsId), 'service');?>
<?$statsUrl = $this->url(array('contentid' => $data->contentId,'srvname' => 'questionstats','pageviewsid' => $data->pageViewsId), 'service');?>
<?$certUrl = $this->url(array('contentid' => $data->contentId,'srvname' => 'certificate','pageviewsid' => $data->pageViewsId), 'service');?>
<?$currentUrl = $this->url();?>



<?$halfW = (int)$flashWidth / 2; ?>
<?$halfH = (int)$flashHeight / 2; ?>

<?$flashVersion = "8.0.0";?>

<?$noflash = $this->render('noflash.phtml');?>

<? $flashContent = <<<EOD
<script type="text/javascript">

    var flashvars = {};
    flashvars.swfFilePath = "{$swfFilePath}";
    flashvars.saver_url = "{$saverUrl}";

    var params = {};
    params.wmode = "transparent";

    var attributes = {};

    swfobject.embedSWF("{$swfFilePath}", "flashcontainer", "{$flashWidth}", "{$flashHeight}", "{$flashVersion}", false, flashvars, params, attributes);
    
</script>

<style type="text/css">
div.centered {
   position:absolute;
   left:50%;
   top:50%;
   margin-left:-{$halfW}px;
   margin-top:-{$halfH}px;
   width:{$flashWidth}px;
   height:{$flashHeight}px;
} 

body{
    min-width:{$flashWidth}px;
    min-height:{$flashHeight}px; 
}
div.vert{
    float:left;
    height:50%;
    margin-top:-{$halfH}px;/* half vertical height*/
    width:100%;
}
div.horiz {
    width:{$flashWidth}px;
    margin-left:auto;
    margin-right:auto;
    height:{$flashHeight}px;
    overflow:hidden; /* dont allow content to scroll inside element */
    text-align:left;
    clear:both;
}

</style>
<div id="vertical" class="vert"></div>
<div id="flashcontent" class="horiz">
    <div id="flashcontainer">
        <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="{$flashWidth}" height="{$flashHeight}">
            <param name="movie" value="{$swfFilePath}" />
            <param name="wmode" value="transparent" />
            <param name="flashvars" value="swfFilePath={$swfFilePath}&saver_url={$saverUrl}" />
            <!--[if !IE]>-->
            <object type="application/x-shockwave-flash" data="{$swfFilePath}" width="{$flashWidth}" height="{$flashHeight}">
                <param name="wmode" value="transparent" />
                <param name="flashvars" value="swfFilePath={$swfFilePath}&saver_url={$saverUrl}" />
                <!--<![endif]-->            
                {$noflash}
            <!--[if !IE]>-->
            </object>
            <!--<![endif]-->
        </object>        
    </div>
</div>

EOD;
?>

<?/*Flash detekovan v prohlizeci, ale nacetli jsme HTML, provedeme reload s parametrem forceVersion na flash*/?>
<?if($data->useFlashIfAvailableInBrowser){?>
    <script type="text/javascript">
    if(flmajor > 0){ <?/*flmajor je definovan v browser_info.js*/?>
        // Posleme pomoci POST forceVersion, chceme totiz zachovat URL zcela bez zasahu (vcetne GET dat)
        var form = document.createElement("form"); 
        form.setAttribute("method", "POST"); 
        form.setAttribute("action", window.location.href); 
        var hiddenField = document.createElement("input"); 
        hiddenField.setAttribute("type", "hidden"); 
        hiddenField.setAttribute("name", "forceVersion"); 
        hiddenField.setAttribute("value", "flash"); 
        form.appendChild(hiddenField);
        document.body.appendChild(form); 
        form.submit(); 
    }
    </script>
<?}?>


<?/* HTML verze */?>
<?if($data->presentationVersion == 'html'){?>
    <?=$data->htmlPresentation?>
    <?/* JS data uzivatele pro HTML prezentaci */?>
    <script type="text/javascript">
        if(typeof indetail == "undefined"){
            var indetail={};
        }
        var indetailWriteServerVars = function(indetailObj){
            indetailObj.server_vars=<?=$data->jsServerVars?>;
            indetailObj.server_vars.saver_url = '<?=$saverUrl?>';
            indetailObj.server_vars.stats_url = '<?=$statsUrl?>';
            indetailObj.server_vars.base_url = '<?=$data->baseUrl?>html5/';
            indetailObj.server_vars.certificate_url = '<?=$certUrl?>';
            indetailObj.server_vars.stats_data=<?=$data->statsData?>;
        }
        indetailWriteServerVars(indetail);
    </script>
<?}?>

<?/* FLASH verze */?>
<?if($data->presentationVersion == 'flash'){?>
    <?=eval(preg_replace(
        array('/%%width%%/',
              '/%%height%%/',          
              '/%%swffilepath%%/',
              '/%%saverurl%%/',
              '/%%currenturl%%/',
              '/%%flash%%/',
              ),
        array($flashWidth,
              $flashHeight,
              $swfFilePath,
              $saverUrl,
              $currentUrl,
              $flashContent), 
        $this->content[$this->current_content]['html']))?>
<?}?>
    
