<?/* Data urcena pro tento content */?>
<?$data = $this->content[$this->current_content]['data'] ?>


<h2><?= $this->content[$this->current_content]['title']?></h2>

<div class="opinionsMain">

<div class="pravniporadna">
    V této nové rubrice máte možnost vložit svůj komentář, a podělit se tak s námi o Vaše názory na inBulletin.

    <div class="reset"></div>
</div>





<div class="jakpostupovat">
    <h3>Postup</h3>
    <ol>
        <li>vyplňte Vaše jméno a příjmení (nepovinné)</li>
        <li>vyplňte pracoviště (nepovinné)</li>
        <li>vložte svůj komentář a klikněte na tlačítko „vložit“</li>
    </ol>
</div>

<div class="dotaz">
            <h3>Váš komentář:</h3>
            
            <?if($data->message){?>
                <div class="info"><b><?=$this->text('.info')?>: </b><?=$data->message?></div>
            <?}?>
             
            <div class="dotaz-in">
            <form action="" method="post" id="add_opinion_form_">
                <fieldset>

            <input type="hidden" id="form_id" name="form_id" value="<?=$data->form_id?>"/>
            
            <label for="name" class="jmeno">Jméno<?=in_array('name', $data->requiredFields)?'*':''?>:</label>
            <input type="text" name="opinions_name" id="name" value="<?=$data->user_data->name?>" />
            <label for="surname" class="prijmeni">Příjmení<?=in_array('surname', $data->requiredFields)?'*':''?>:</label>
            <input type="text" name="opinions_surname" id="surname" value="<?=$data->user_data->surname?>" />
            <br/><br/>
            
            <label for="employer"  class="pracoviste">Pracoviště<?=in_array('employment', $data->requiredFields)?'*':''?>:&nbsp;</label>
            <input type="text" name="opinions_employment" id="employer" value="<?=$data->user_data->employment?>" />
            <br/><br/>
            
            
            <div class="dotazLabelDiv">
            <label for="dotaz">Místo pro <br/> komentář<?=in_array('text', $data->requiredFields)?'*':''?>:</label>
            </div>
            <div class="dotazInputDiv">
            <textarea name="opinions_text" id="dotaz" rows="8" cols="65" ><?=$data->user_data->text?></textarea>
            </div>
            <div class="reset"></div>
            <input type="hidden" name="show" value="checked"/>
            <br/>
            * povinný údaj
            
            <p>
            <button type="submit" name="opinions_send">Vložit</button>
            </p>


                    
                </fieldset> 
            </form >
            </div>
</div >



      
      
      
      <div class="nazory">
        
        <h2>Vaše komentáře:</h2>
        <?$last_key = end(array_keys($data->opinions_data))?>
        <?foreach($data->opinions_data as $key => $opinion){?>
        <div class="<?= $key == $last_key ? 'last ' : ''?>nazor">
          <h3><span><?=$opinion['timestamp']?> |</span> 
              <?=$opinion['title']?> <?=$opinion['name']?> <?=$opinion['surname']?> <?=
                !empty($opinion['employment']) && 
                (!empty($opinion['name']) || !empty($opinion['surname'])) ? '-' : '' 
              ?> <?=$opinion['employment']?>
          </h3>
          <p><?=$opinion['text']?></p>
        </div>
        <?}?>
        
        
        <div class="nav">
            <?if(!empty($data->paginator)){?>
                <?= $this->paginationControl($data->paginator, 'Sliding', 'pagination_control_inline.phtml'); ?>
            <?}?>
        </div>
      </div>
</div>
