<div id="clanek">
<h2><?= $this->content[1]['title']?></h2>

<?$info_array = $this->content[1]['info']?>
<?$info_array = array($info_array['created'], $info_array['author'])?>
<?$info_array = array_filter($info_array, create_function('$elem','return empty($elem) ? false : true;'))?>
<h3><?=join(' | ', $info_array)?></h3>

<?if($this->form_saved){?>
    <p class="small_space"><?=$this->formInfoMessage?></p>
<?}?>

<?if(($this->show_form_after_save && $this->form_saved) || !$this->form_saved){?>
    <?= eval($this->content[1]['form_html'])?>
<?}?>

<?=$this->render('sheet_navigation.phtml')?>
</div>

