           <div id="<?=$this->content[$this->current_content]['data']->elemId?>" class="noResize">
                <div>
                <p>Pro správnou funkci přehrávače musí váš prohlížeč
                podporovat JavaScript a Flash.
                </p>
                <p>
                <a href="http://www.adobe.com/go/getflashplayer">
                <img src="pub/img/get_flash_player.gif"
                    alt="Get Adobe Flash player" /></a>
                </p>
                </div>
            </div>