<?
$config = Zend_Registry::get('config');
$obj = $this->content[$this->current_content]['obj'];

$vimeo_id = $obj->vimeo_id;

$player_id = 'vimeo_player_' . $obj->id . '_' .rand(10000,99999);

// 640x360 resized
//$thumb = $obj->vimeo_video['pictures']['sizes'][3]['link'];

$color = $config->video->vimeo_color;
$title = $obj->vimeo_video['body']['name'];
$reportingUrl = $this->content[$this->current_content]['data']->reportingUrl;

?>
<div class="vimeo_player" id="<?=$player_id?>"
     data-vimeo-id="<?=$vimeo_id?>"
     data-vimeo-color="<?=htmlspecialchars($color)?>"
     data-vimeo-title="<?=htmlspecialchars($title)?>"
     data-reporting-url="<?=htmlspecialchars($reportingUrl)?>"

     <?/*if($thumb){?>style="background-image: url('<?=$thumb?>');"<?}*/?>
    ></div>
