<?= $this->render('default_head.phtml') ?>
<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<? /* =$this->render('admin_top.phtml') */ ?>

<body>
    <div class="container wrap">
        <div id="content">
            <div class="row">
                <div class="span8">
                    <h1><?= $this->title ?></h1>
                    <?= $this->render('infoMessages.phtml') ?>
                    <?= $this->form ?>
                </div>
                <div class="span4">
                    <?= $this->render('contentHelp.phtml') ?>	
                    <?
                    if ($this->control == "indetail") {
                        echo $this->collapse(
                                $this->text('help'), array(
                            'links' => array('title' => $this->text('links_list.main.title'), 'body' => $this->render('contentLinks.phtml')),
                                ), array(1)
                        );
                    }
                    ?>
                </div>

            </div>
        </div>
    </div>
</div>
</body>
<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=
$this->render('admin_bottom.phtml')?>