<?php
/* FILEMANAGER */
$lang = Ibulletin_AdminAuth::getInstance()->user_data->language;
if ($lang == "cz") {
    $lang = "cs";
}
$id = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$connectorurl = $this->url(array('controller' => 'filemanager', 'action' => 'elfinder-connector', 'id' => $id));
?>

<?= $this->render('default_head.phtml') ?>

<script src="pub/scripts/elfinder/js/elfinder.full.js"></script>

<? if ($lang && $lang != 'en'): ?>
    <script src="pub/scripts/elfinder/js/i18n/elfinder.<?= $lang ?>.js"></script>
<? endif; ?>

<link rel="stylesheet" type="text/css" href="pub/scripts/elfinder/css/elfinder.min.css">
<link rel="stylesheet" type="text/css" href="pub/scripts/elfinder/css/theme.css">

<div style="font-size:14px;"><div id="elfinder"></div></div>

<script type="text/javascript" charset="utf-8">

    // Helper function to get parameters from the query string.
    function getUrlParam(paramName) {
        var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i');
        var match = window.location.search.match(reParam);
        return (match && match.length > 1) ? match[1] : '';
    }

    // Documentation for client options:
    // https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
    $(document).ready(function () {
        var funcNum = getUrlParam('CKEditorFuncNum');
        $('#elfinder').elfinder({
            url: '<?= $connectorurl ?>',
            resizable: false,
            lang: '<?= $lang ?>',
            defaultView: 'list',
            getFileCallback: function (file) {
                var url = file.url;
                //odebere baseUrl vráti jen relativni cast
                if (getUrlParam('relative') == 1) {
                    url = url.replace(file.baseUrl, '');
                }

                window.opener.CKEDITOR.tools.callFunction(funcNum, url);
                window.close();
            },
            commands: ['open', 'reload', 'home', 'up', 'getfile', 'quicklook',
                'download', 'search', 'info', 'view', 'sort']
        });

    });
</script>

<?=$this->render('admin_bottom.phtml')?>

