<?=$this->render('admin_top.phtml')?>
<div class="row">
    <div class="span8">
        <?if(isset($this->resource['path'])):?>
            <a href="<?=$this->url(array('action'=>'index','download'=>$this->resource['id']),null)?>"><?=basename($this->resource['path'])?></a>
        <?endif;?>
        <?=$this->form?>
    </div>
    <div class="span4">
        <div>
        <?if (isset($this->resource['path']) && getimagesize($this->resource['path'])):?>
            <img src="<?=$this->baseUrl()?>/<?=$this->resource['path']?>" />
         <?endif;?> 
        </div>
       <?=$this->collapse($this->text('help'))?> 
    </div>
</div>
<?=$this->render('admin_bottom.phtml')?>
