<?= $this->render('admin_top.phtml') ?>

<div class="row">
    <div class ="span8">

        <? /* Importovane atributy */ ?>
        <? if (!empty($this->importedAttribs)) { ?>
            <h4><?= $this->text('importedAttribs') ?></h4>
            <ul>
                <li><b>users:</b> <?= join(', ', $this->importedAttribs['users']) ?></li>
                <li><b>users_attribs:</b> <?= join(', ', $this->importedAttribs['usersAttribs']) ?></li>
            </ul>
            <br/><br/>
        <? } ?>

        <? /* CSV vadnych radku */ ?>
        <? if (!empty($this->dataRepair)) { ?>
            <h4><?= $this->text('to_repair') ?></h4>
            <p>
                <?= $this->dataRepair ?>
            </p>
            <br/><br/>
        <? } ?>
            <?if ($this->dry_save):?>
            <div class="well well-small">
                <h5><?= $this->text('dryRunOk') ?></h5>
                <a href="<?=$this->url()?>dr_save/1" class="btn btn-primary"><?= $this->text('submit') ?></a>
            </div>
            <?endif;?>
        <form enctype="multipart/form-data" action="" method="post"><span></span>
            <input type="hidden" name="MAX_FILE_SIZE" value="180000000" />
            <fieldset><legend>Import</legend>
                <table>
                    <tr>
                        <td><?= $this->text('pick_file') ?></td>
                        <td><input name="file[file_0]" type="file" /></td>
                    </tr>
                    <tr>
                        <td><?= $this->text('fileType') ?></td>
                        <td>
                            <select name="fileType">
                                <option value="xlsx">MS Office XLSX</option>
                                <option value="xml">MS Office XML</option>
                                <option value="windows-1250">CSV windows-1250</option>
                                <option value="utf-8">CSV utf-8</option>
                                <option value="iso-8859-2">CSV iso-8859-2</option>
                                <option value="iso-8859-1">CSV iso-8859-1</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td><?= $this->text('contactOrigin') ?></td>
                        <td><input name="contact_origin" type="text" /></td>
                    </tr>
                    <tr>
                        <td><?= $this->text('dryRun') ?></td>
                        <td><input name="dryRun" type="checkbox" checked="checked" /></td>
                    </tr>
                    <tr>
                        <td><input type="submit" name="submit" value="<?= $this->text('submit') ?>" /></td>
                    </tr>
                </table>
            </fieldset>

        </form>
        <? /* Vypisat info o principu uploadu... */ ?>
        <?= sprintf($this->text('form_help'), $this->noChangeSymbol); ?>
    </div><? /* content_left */ ?>

    <div class="span4">
        <?/* Tlacitko pro stazeni XLSX sablony */?>
        <div style="margin-bottom:10px"><a class="btn btn-mini btn-info xlsx-generate" href="#">
            <i class="glyphicon glyphicon-save icon-save"></i>&nbsp;<?=$this->text('xlsx_template')?></a>
        </div>
        <?=$this->collapse($this->text('help'), null, array(1))?>
    </div><? /* content_right */ ?>
</div>
    <?=$this->render('admin_bottom.phtml')?>