<? if(!empty($this->menu['bulletin_menu'])){ ?>
    <? foreach($this->menu['bulletin_menu'] as $item){?>
        <? if(!empty($item['url'])){ ?>
        <li class="bulletin<?=!$item['disabled']?'':' disabled'?>">
            <? if($item['disabled']){?>
                <?=$item['name']?>
            <?}else{?>
                <a href="<?=$item['url']?>"><?=$item['name']?></a>
            <?}?>
        </li>
        <? } ?>
    <? } ?>
<? } ?>
