        <?/**
           * Menu odkazujici na jednotliva vydani, pouziva se v iTriu.
           * 
           * Jednotlive polozky jsou neaktivni, pokud nebyla predana data, je proto mozne
           * pouzit toto menu i na strankach, kde nemaji byt odkazy vubec aktivni.
           * 
           * POZOR! 
           * Je nezbytne, aby bulletiny, pod kterymi jsou ulozeny jednotlive casti mely 
           * datumy zalozeni v poradi jak maji byt polozky za sebou...
           */?>
        
        <div class="menu">
        <ul>
          
          <?$valid = isset($this->all_bulletins[0]['is_valid']) && $this->all_bulletins[0]['is_valid']?>
          <li class="m1">
            <?if($valid){?><a href="<?=$this->url(array('name' => $this->all_bulletins[0]['url_name']), 'bulletin', true)?>" class="on"><?}else{?><div class="off"><?}?>
                <strong><?=$this->text('.itrio_menu_item1')?></strong><br /><?=$this->text('.itrio_menu_item1_info')?>
            <?if($valid){?></a><?}else{?></div><?}?>
          </li>
          
          <?$valid = isset($this->all_bulletins[1]['is_valid']) && $this->all_bulletins[1]['is_valid']?>
          <li class="m2">
            <?if($valid){?><a href="<?=$this->url(array('name' => $this->all_bulletins[1]['url_name']), 'bulletin', true)?>" class="on"><?}else{?><div class="off"><?}?>
                <strong><?=$this->text('.itrio_menu_item2')?></strong><br /><?=$this->text('.itrio_menu_item2_info')?>
            <?if($valid){?></a><?}else{?></div><?}?>
          </li>
          
          <?$valid = isset($this->all_bulletins[2]['is_valid']) && $this->all_bulletins[2]['is_valid']?>
          <li class="m3">
            <?if($valid){?><a href="<?=$this->url(array('name' => $this->all_bulletins[2]['url_name']), 'bulletin', true)?>" class="on"><?}else{?><div class="off"><?}?>
                <strong><?=$this->text('.itrio_menu_item3')?></strong><br /><?=$this->text('.itrio_menu_item3_info')?>
            <?if($valid){?></a><?}else{?></div><?}?>
          </li>
          
        </ul>
        <a class="spc" href="#"><?=$this->text('.itrio_menu_spc')?></a>
        
      </div>
