<div id="submenu">
<p>
    <?if(isset($this->moduleMenu)){?>
        <?$moduleMenuData = $this->moduleMenu->getRenderData()?>
        <?$first=true?>        
        <?foreach($moduleMenuData as $item){?>
            <?$url = isset($item['url']) ? $item['url'] : $this->url($item['params'], 'default', 
                !(isset($item['noreset']) && $item['noreset']))?>
            <?if(!$first){?> | <?}?>
            <a href="<?=$url?>"><?=$item['title']?></a>
            
            <?if($first){
                $first = false;   
            }?>
        <?}?>
    <?}?>
    </p>
</div><!-- id=submenu -->