<?$lang='en'?>
<div id="noflash">  
<ul>
<?if ($lang == 'cz') {?>
	<li>Bohužel nemáte nainstalovaný program potřebný pro absolvování prezentace (Flash Player).</li>
    <li>Prosím, klikněte <a href="http://www.adobe.com/go/getflashplayer" target="_blank">ZDE</a> pro bezpečnou instalaci tohoto programu. V nově otevřeném okně klikněte na tlačítko "Nainstalovat aplikaci".</li>
    <li>Po dokončení instalace zavřete okno a pokračujte v prezentaci <a href="<?=$this->url()?>">ZDE</a>.</li>
<?} elseif ($lang == 'en') {?>
	<li>Unfortunately you do not have the program necessary to complete the presentation (Flash Player).</li>
    <li>Please click <a href="http://www.adobe.com/go/getflashplayer" target="_blank">HERE</a> for the safe installation of this program. In the newly opened window, click the "Install application".</li>
    <li>After installation is complete, close the window and proceed with the presentation <a href="<?=$this->url()?>">HERE</a>.</li> 
<?} elseif ($lang == 'de') {?>
	<li>Um diese Seiten darstellen zu können, benötigen Sie einen Flash-Player.</li>
    <li>Bitte klicken Sie <a href="http://www.adobe.com/go/getflashplayer" target="_blank">HIER</a> um die sichere Installation des Plug-in vorzunehmen.</li>
    <li>Nachdem Sie die Installation beendet haben, klicken Sie bitte <a href="<?=$this->url()?>">HIER</a> um die Präsentation fortzusetzen.</li> 
<?}?>
</ul>
</div>
