<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?= $this->render('admin_top.phtml') ?>
<div class="calendar_events">
    <h2><?=$this->texts->events->available_events?></h2>
    <div style="position: fixed;right:0px;bottom:0px" class="infoMsg"></div>
    <table data-url="<?= $this->checkEventsURL ?>" data-contentid="<?= $this->contentId ?>" cellspacing="0" class="eventtable stripe cell-border" width="100%" id="availableEvents">
        <thead><tr><th><?=$this->texts->events->id?></th><th><?=$this->texts->events->title?></th><th><?=$this->texts->events->datebegin?></th><th><?=$this->texts->events->dateend?></th><th><?=$this->texts->events->specializations?></th><th><?=$this->texts->events->tags?></th><th></th></tr>
        </thead>
        <tfoot>
            <tr>
                <th class="text-search"><?= $this->texts->events->id ?></th><th class="text-search"><?= $this->texts->events->title ?></th><th></th><th></th><th></th><th></th><th></th>
            </tr>
        </tfoot>
        <tbody></tbody>
    </table>
</div>
<div class="calendar_events">
    <h2><?= $this->texts->events->saved_events ?></h2>
    <table data-url="<?= $this->getEventsURL ?>" data-contentid="<?= $this->contentId ?>" cellspacing="0" class="eventtable stripe cell-border" width="100%" id="events">
        <thead><tr><th><?= $this->texts->events->id ?></th><th><?= $this->texts->events->title ?></th><th><?= $this->texts->events->datebegin ?></th><th><?= $this->texts->events->dateend ?></th><th><?= $this->texts->events->specializations ?></th><th><?= $this->texts->events->tags ?></th><th></th></tr>
        </thead>
        <tfoot>
            <tr>
                <th class="text-search"><?= $this->texts->events->id ?></th><th class="text-search"><?= $this->texts->events->title ?></th><th></th><th></th><th></th><th></th><th></th>
            </tr>
        </tfoot>
        <tbody></tbody>
    </table>
</div>

<!-- Modal detail udalosti kalendare -->
<div id="eventDetail" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="eventDetailLabel"></h3>
    </div>
    <div  id="eventDetailInfo" class="modal-body">
        <div style="margin-right: 10px;margin-bottom:10px;width:35%;" class="pull-left"><img class="img" src="" /></div>
        <div style="width:60%" class="pull-left">
            <ul style="list-style: none;margin:0;padding:0;">
                <li class="desc"><div class="well well-small"></div></li>
                <li class="date"><strong><?= $this->texts->events->date ?>: </strong><span></span></li>
                <li class="place"><strong><?= $this->texts->events->place ?>: </strong><span></span></li>
                <li class="address"><strong><?= $this->texts->events->address ?>: </strong><span></span></li>
                <li class="url_action"><strong><?= $this->texts->events->url_action ?>: </strong><span></span></li>
                <li class="specs"><strong><?= $this->texts->events->specializations ?>: </strong><span></span></li>
                <li class="tags"><strong><?= $this->texts->events->tags ?>: </strong><span></span></li>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-inverse" data-dismiss="modal" aria-hidden="true"><?= $this->texts->events->close ?></button>
    </div>
</div>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?= $this->render('admin_bottom.phtml') ?>


