<?=$this->render('head.phtml')?>

<?
$isError = Zend_Controller_Front::getInstance()->getRequest()->getParam('email') !== null && !empty($this->loginError);

?>

<body id="info" class="incampaign">
<div id="page">

<div id="head">
    <h3><?=$this->text('title')?></h3>
</div><!--end.head-->

<div id="content">
    <p><?=$this->main?></p>
    <form action="" method="post">
        <fieldset>
            <div class="email input">
                <label for="email"><?=$this->text('email')?></label>
                <input type="text" name="email" id="email" title="<?=$this->text('email_title')?>" value="<?=!empty($this->input['email']) ? $this->input['email'] : ''?>"/>
            </div>
            <? if($isError){?>        
                <p class="error"><?=$this->loginError?></p>
            <?} ?>    
            <p><?=$this->rights?></p>                   
            <div class="agreement">
                <input type="checkbox" name="agreement" id="agreement" title="<?=$this->text('agreement_title')?>" />
               <label for="agreement"><?=$this->text('agreement')?></label>
            </div>                     
            <button class="button w140" type="submit" value="<?=$this->text('submit')?>" title="<?=$this->text('submit')?>"><?=$this->text('submit')?></button>
        </fieldset>
    </form>
</div><!--end.content-->

<?=$this->render('bottom_login.phtml')?>
