<?
$session = Zend_Registry::get('session');
$db = Zend_Registry::get('db');

// Najdeme seznam reprezentantu
$sel = new Zend_Db_Select($db);
$sel->from('users', array('name', 'surname', 'id'))
    ->where('is_rep')
    ->where('deleted IS NULL')
    ->where('unsubscribed IS NULL')
    ->order(array('surname', 'name', 'id'));
$reps = $db->fetchAll($sel);
$repsSel = array('' => '- vyberte -');
foreach($reps as $rep){
    $repsSel[$rep['id']] = join(' ', array($rep['name'], $rep['surname']));
}

$povolani = array('','Lékař','Lékárník','Student medicíny','Student farmacie','Nelékařské profese');
$states = array('','Česká republika','Slovenská republika');
$specializations = array('','Alergolog','Androlog','Anesteziolog','Angiolog','Biochemik','Chirurg','Dermatovenerolog','Dětský lékař','Diabetolog',
	'Diagnostik','Endokrinolog','Epidemiolog','Foniatrie','Gastroenterolog','Genetik','Geriatr', 'Gynekolog','Hematolog','Infektolog', 'Internista','Kardiolog','Klinická farmakologie',
	'Lékař urgentní medicíny','Mikrobiolog','Nefrolog', 'Neonatolog','Neurolog','Nutriční specialista', 'Obezitolog','Oční lékař','Onkolog','Ortoped','Patolog','Plicní lékař',
	'Pracovní lékař','Psychiatr','Psychosomatika','Radiolog','Rehabilitační lékař','Revmatolog','Sexuolog','Stomatolog','Urolog','Ušní, nosní, krční (ORL)','Všeobecný praktický lékař pro dospělé');
$odbornost = array('','Nemocniční lékárník','Klinický farmaceut','Lékárník ve veřejné lékárně','jiné');
$fakulty = array('','1. lékařská faktulta Univerzity Karlovy','2. lékařská fakulta Univerzity Karlovy','3. lékařská fakulta Univerzity Karlovy','Lékařská fakulta Masarykovy univerzity',
    'Lékařská fakulta Univerzity Karlovy v Hradci Králové','Lékařská fakulta Univerzity Karlovy v Plzni','Lékařská fakulta Univerzity Palackého v Olomouci','Jesseniova lekárska fakulta v Martine Univerzity Komenského',
    'Lekárska fakulta Univerzity Komenského v Bratislave', 'Lekárska fakulta Univerzity Pavla Jozefa Šafárika v Košiciach', 'Lekárska fakulta Slovenskej zdravotníckej univerzity','Fakulta vojenského zdravotnictví Univerzity obrany');

$profese = array('','Asistent ochrany veřejného zdraví','Asistent zubního technika','Autoptický laborant','Biomedicíncký inženýr','Biomedicíncký technik','Dentální hygienistka','Dezinfektor','Ergoterapeut',
	'Farmaceutický asistent','Fyzioterapeut','Klinický logoped','Laboratorní asistent','Laboratorní pracovník','Masér/nevidomý a slabozraký masér','Nutriční asistent','Nutriční terapeut',
	'Odborný pracovník v laboratorních metodách a v přípravě léčivých přípravků','Odborný pracovník v ochraně veřejného zdraví','Optometrista','Ortoptista','Ortoticko-protetický technik','Ortotik-protetik',
	'Ošetřovatel','Porodní asistentka','Psycholog ve zdravotnictví/klinický psycholog','Radiologický asistent','Radiologický fyzik','Radiologický technik','Řidič dopravy nemocných a raněných',
	'Řidič vozidla zdravotnické záchranné služby','Sanitář','Všeobecná sestra','Zdravotně-sociální pracovník','Zdravotnický asistent','Zdravotnický záchranář','Zdravotní laborant','Zubní instrumentářka','Zubní technik'
);
$fakulty_farmacie = array('','Farmaceutická fakulta Univerzity Karlovy Hradec Králové','Farmaceutická fakulta Veterinární a farmaceutické univerzity Brno','Univerzita veterinárskeho lekárstva a farmácie v Košiciach',
                        'Farmaceutická fakulta Univerzity Komenského v Bratislave');


$currentDate = Zend_Date::now();

// Pokud byl formular jiz odeslan, dostali jsme jej z controlleru a je nevalidni
if(!empty($this->form)){
    $form = $this->form;
}
else{
    // Potrebujeme random string generator
    $rsg = new Ibulletin_RandomStringGenerator();

    // Definice formulare kvuli validaci v controlleru bez znalosti formulare v controlleru
    // formular jde do controlleru ulozeny v session
    $form = new Form();
    $form->addElement('text', 'name', array(
                'required' => true,
                'label' => 'Jméno *',
                'validators' => array(
                    array('NotEmpty', true,
                         array('messages' => array('isEmpty' => "Pole nesmí být prázdné."))),
                    array('StringLength', true,
                        array(2, 'messages' => array('stringLengthTooShort' => "Jméno musí mít alespoň 2 znaky.")))
                )
        ));

    $form->addElement('text', 'surname', array(
                'required' => true,
                'label' => 'Příjmení *',
                'validators' => array(
                    array('NotEmpty', true,
                         array('messages' => array('isEmpty' => "Pole nesmí být prázdné."))),
                    array('StringLength', true,
                        array(2, 'messages' => array('stringLengthTooShort' => "Příjmení musí mít alespoň 2 znaky.")))
                )
        ));

	$form->addElement('checkbox', 'gdpr_email',array(
	    'label' => 'na mou e-mailovou adresu',
	    'value' => 1,
		'checkedValue' => '1',
        'uncheckedValue' => null
	));
	$form->addElement('hidden', 'gdpr_email_timestamp',array(
	    'value' => $currentDate->toString('YYYY-MM-dd')
	));
	
	$form->addElement('checkbox', 'gdpr_postal_address',array(
	    'label' => 'na mou doručovací poštovní adresu',
	    'value' => 1,
		'checkedValue' => '1',
        'uncheckedValue' => null
	));
	$form->addElement('hidden', 'gdpr_postal_address_timestamp',array(
	    'value' => $currentDate->toString('YYYY-MM-dd')
	));
	
	$form->addElement('checkbox', 'gdpr_billing_address',array(
	    'label' => 'na mou fakturační adresu',
	    'value' => 1,
		'checkedValue' => '1',
        'uncheckedValue' => null
	));
	$form->addElement('hidden', 'gdpr_billing_address_timestamp',array(
        'value' => $currentDate->toString('YYYY-MM-dd')
	));
	
	$form->addElement('checkbox', 'gdpr_phone',array(
	    'label' => 'telefonicky',
	    'value' => 1,
		'checkedValue' => '1',
        'uncheckedValue' => null
	));
	$form->addElement('hidden', 'gdpr_phone_timestamp',array(
        'value' => $currentDate->toString('YYYY-MM-dd')	
	));

	$checkboxDecorator = array(
		'ViewHelper',
		array('SimpleLabel',array('placement'=>'append')),
		'Errors'
	);

	$form->getElement('gdpr_email')->setDecorators($checkboxDecorator);
	$form->getElement('gdpr_postal_address')->setDecorators($checkboxDecorator);
	$form->getElement('gdpr_billing_address')->setDecorators($checkboxDecorator);
	$form->getElement('gdpr_phone')->setDecorators($checkboxDecorator);
	
	$form->addElement('text', 'email', array(
	    'label' => 'Email *',
		'required' => true,
		'validators' => array(
			array('NotEmpty', true,
				array('messages' => array('isEmpty' => "Zadejte e-mail"))),
			array('EmailAddress', true,
				array('messages' => array(Zend_Validate_EmailAddress::INVALID_FORMAT => 'Byl zadán neplatný e-mail'))),
		)
	));
	$form->addElement('text', 'degree_before', array(
		'required' => false,
        'label' => 'Titul před'
	));
	$form->addElement('text', 'degree_after', array(
		'required' => false,
        'label' => 'Titul za'
	));
		$form->addElement('text', 'phone', array(
		'required' => false,
        'label' => 'Telefon'
	));


    // Najdeme nepouzity hash pro formular
    while(1){
        $hash = $rsg->get(15);
        if(!isset($session->existingForms[$hash])){
            break;
        }
    }
    $form->addElement('hidden', 'hash', array('value' => $hash));


    // Ulozime formular do session s pomoci hashe
    if(!isset($session->existingForms)){
        $session->existingForms = array();
    }
    // Ukladame serializovane, protoze jinak se vytvori podivna vazba na View Helper Text
    // a vse kolabuje pri spusteni session
    $session->existingForms[$hash] = serialize($form);

}

$texts = Ibulletin_Texts::getSet('register');

// ==============================================================================================//
?>

<?=$this->render('head.phtml')?>

<body class="gdpr">
<div id="page">
    <h1>SOUHLAS SE ZPRACOVÁNÍM OSOBNÍCH ÚDAJŮ pro správce dat NextForce,&nbsp;a.s.</h1>
    <p>Ctíme nařízení EU a chceme, abyste se cítili bezpečně, prosím, potvrďte Vaše souhlasy a pojďte si s námi dále zvyšovat kvalifikaci.</p>
    <p>
        Souhlasím s tím, aby společnost 
                        <span style="text-decoration: underline" data-tooltip="Správce osobních údajů je společnost NextForce a.s.,<br>
                        IČ: 28855523, se sídlem Fibichova 41, 537 01 Chrudim, zastoupená statutární ředitelem MVDr. Zdeňkem Vičíkem, MBA.<br>
                        Kontakt na pověřence pro ochranu osobních údajů: <a href='mailto:dpo@nextforce.cz'>dpo@nextforce.cz</a>.<br>
                        Více informací na <a href='http://www.nextforce.cz' target='_blank'>www.nextforce.cz</a>.">NextForce a.s.</span>
                        (dále jen „správce“) zpracovávala a používala mé osobní údaje tj. jméno, příjmení, titul, doručovací a fakturační poštovní adresu, emailovou adresu, telefonní číslo na pevnou linku nebo mobilní telefon, za účelem předávání a získávání odborných a dalších informací správce z oblasti zdravotnických prostředků, kosmetiky a léčiv:
    </p>
	<? if ( ! empty($this->loginError)) { ?>
        <p class="error"><?= $this->loginError ?></p>
	<? } ?>
    <form class="incampaign-register-form" action="" method="post">
		<?= $form->getElement('hash') ?>
            <div class="checkbox">
				<?= $form->getElement('gdpr_email') ?>
				<?= $form->getElement('gdpr_email_timestamp') ?>
            </div>
            <div class="checkbox">
				<?= $form->getElement('gdpr_postal_address') ?>
				<?= $form->getElement('gdpr_postal_address_timestamp') ?>
            </div>
            <div class="checkbox">
				<?= $form->getElement('gdpr_billing_address') ?>
				<?= $form->getElement('gdpr_billing_address_timestamp') ?>
            </div>
            <div class="checkbox">
				<?= $form->getElement('gdpr_phone') ?>
				<?= $form->getElement('gdpr_phone_timestamp') ?>
            </div>
            <div class="input input-fl" style="padding-right:15px">
				<?= $form->getElement('degree_before') ?>
            </div>
            <div class="input input-fl">
				<?= $form->getElement('degree_after') ?>
            </div>
            <div class="cr"></div>
            <div class="input input-fl" style="padding-right:15px">
				<?= $form->getElement('name') ?>
            </div>
            <div class="input input-fl">
				<?= $form->getElement('surname') ?>
            </div>
            <div class="cr"></div>
            <div class="email input">
				<?= $form->getElement('email') ?>
            </div>
             <div class="input">
				<?= $form->getElement('phone') ?>
            </div>
            <p>
                Poskytnutí výše uvedených osobních údajů je dobrovolné, souhlas mohu kdykoli odvolat, aniž je tím dotčena zákonnost zpracování, založeného na souhlasu uděleném před jeho odvoláním, mám přístup ke svým osobním údajům, mám právo na jejich opravu, mám právo požadovat od správce osobních údajů vysvětlení v případě podezření, že ke zpracování osobních údajů dochází v rozporu s ochranou soukromého a osobního života uživatele nebo v rozporu se zákonem, mám právo požadovat odstranění protiprávního stavu, mám právo vznést námitku proti zpracování, jakož i právo na přenositelnost údajů, mám právo obrátit se v případě uvedeného podezření či odmítnutí odstranění uvedeného protiprávního stavu na Úřad pro ochranu osobních údajů. Souhlas se zasíláním informačních emailů mohu kdykoli odvolat.
            </p>
            <p class="rights">
                Pro zobrazení bližších informací a poučení o zpracování Vašich osobních údajů prosím klikněte <a
                        href="javascript:inpopup.showPopup()">ZDE</a>.
            </p>
            <button class="button" type="submit" name="submit" value="Odeslat" title="Odeslat">Souhlasím a odeslat
            </button>
        <!-- POPUPY -->
        <div id="inpopup" data-show-onload="false">
            <div>
                <h1>Informace a poučení o zpracování Vašich osobních údajů</h1>
                <p>
                Posláním společnosti NextForce je poskytnout lékařům, farmaceutům a střednímu zdravotnickému personálu ve zdravotnictví moderní zdravotnické prostředky, kosmetiku a léčiva a tím umožnit, aby jejich pacienti a zákazníci měli možnost používat moderní přístup v řešení jejich obtíží.Pro předávání klíčových informací z oblasti farmacie je pro nás nezbytná komunikace s Vámi, našimi zákazníky z řad lékařů a pracovníků lékáren. Proto je klíčové, abychom Vás dokázali jasně a srozumitelně informovat, jak nakládáme s Vašimi daty, jaká data shromažďujeme a jak je používáme. Před použitím našich Služeb budete vyzvání k souhlasu s tím, abychom vaše data používali v souladu s těmito Zásadami ochrany osobních údajů.
                </p>
                <p>
                 Společnost NextForce zastupuje významné a tradiční výrobce zdravotnických prostředků a kosmetiky.<br>
V našem portfoliu najdete:   
                </p>
<ul>
<li>Aloclair brand - péče o dutinu ústní, afty, dásně, dětské zoubky</li>
<li>Herpclair - léčba oparů</li>
<li>Sebclair - léčba seboreické dermatitidy, lupů</li>
<li>Atopiclair - nesteroidní přípravek na atopický ekzém</li>
<li>Rejuvasil a ScarEsthetique - péče o jizvy</li>  
</ul>
<p>
V roce 2016 jsme uvedli na trh první vlastní kosmetický přípravek Zitenax krémpastu, určenou k léčbě opruzenin u dětí i dospělých. Doufáme, že v budoucnu rozšíříme počet vlastních přípravku o další.     
</p>
<p>
Kromě nabídky výše uvedených přípravků pro Vaše pacienty se současně snažíme nabídnout odbornou službu, která Vám napomůže se orientovat v řešeních pro zdraví včetně prevence a pro Váš odborný rozvoj. Abychom v tomto našem poslání byli opravdu jedineční, přijali jsme Zásady ochrany osobních údajů vztahující se na jakéhokoli zákazníka nebo partnera.
</p>
<p>
Poskytnutí výše uvedených osobních údajů je dobrovolné, souhlas mohu kdykoli odvolat, aniž je tím dotčena zákonnost zpracování, založeného na souhlasu uděleném před jeho odvoláním, mám přístup ke svým osobním údajům, mám právo na jejich opravu,  mám právo požadovat od správce osobních údajů vysvětlení v případě podezření, že ke zpracování osobních údajů dochází v rozporu s ochranou soukromého a osobního života uživatele nebo v rozporu se zákonem, mám právo požadovat odstranění protiprávního stavu, mám právo vznést námitku proti zpracování, jakož i právo na přenositelnost údajů, mám právo obrátit se v případě uvedeného podezření či odmítnutí odstranění uvedeného protiprávního stavu na Úřad pro ochranu osobních údajů. Souhlas se zasíláním informačních emailů mohu kdykoli odvolat.
</p>
<p>
Správce se zavazuje, že mé osobní údaje mohou být z databáze vymazány na základě mé žádosti odeslané na adresu <a href="delete@nextforce.cz">delete@nextforce.cz</a> a následným potvrzením vymazání kliknutím na příslušný o
odkaz v potvrzovacím emailu.
</p>
<p>
V případě žádosti o bližší informace týkající se správy a zpracování vašich osobních údajů kontaktujte <a href="dpo@nextforce.cz">dpo@nextforce.cz</a>. Správce bude s osobními údaji nakládat pouze v souladu se zákonem. Detaily postupů, jak mohu uplatnit výše uvedená práva, jsou dostupné na <a target="_blank" href="http://www.nextforce.cz/osobni-udaje">www.nextforce.cz/osobni_udaje</a>.
</p>
                <p class="text-center">
                    <a class="btn" href="javascript:inpopup.closePopup();">Zpět</a>
                </p>
            </div>
        </div>
    </form>
</div>
    <script type="text/javascript">

		var inpopup = new InPopup({id: 'inpopup'});

		$(document).on('change', '[name="gdpr_email"],[name="gdpr_phone"],[name="gdpr_postal_address"],[name="gdpr_billing_address"]', function () {
			var date = "<?=$currentDate->toString('YYYY-MM-dd');?>";
			var name = $(this).attr('name') + '_timestamp';
			$("[name='" + name + "']").val(date);
		});

		//TOOLTIP
		$(document).on('click', '[data-tooltip]', function (e) {
            e.stopPropagation();
			showTooltip($(this), false);
		});

		$(document).on('mouseenter', '[data-tooltip]', function (e) {
			showTooltip($(this), true);
		});

		$(document).on('mouseleave', '[data-tooltip]', function (e) {
			closeTooltip($(this), true);
		});

		$(document).on('click', function (e) {
			closeTooltip($(this), false);
		});

		//Tooltip
		var showTooltip = function (el, delay) {

			var tooltip = el.find('.tooltip');

			if (tooltip.length == 0) {
				tooltip = $('<span class="tooltip">' + el.data('tooltip') + '</span>');
				var marginBottom = el.outerHeight(true)*1.25;
				var elOffset = el.offset();
				tooltip.appendTo(el);

                var tooltipWidth = tooltip.outerWidth(true);
                var tooltipHeight = tooltip.outerHeight(true);

				tooltip.css('position','absolute');
				tooltip.css('z-index','100');

				var shiftLeft = 20;

				if((elOffset.left - (tooltipWidth/2)) < 0) {
					shiftLeft = -1 * (elOffset.left - (tooltipWidth/2));
                } else if ((elOffset.left + (tooltipWidth/2) - $(window).width()) > 0) {
					shiftLeft = -1 * (elOffset.left + (tooltipWidth/2) - $(window).width());
                }

				tooltip.css('left',elOffset.left + shiftLeft);
				tooltip.css('top',elOffset.top-tooltipHeight);
				tooltip.css('height',tooltipHeight);

			}

			if (tooltip.hasClass('active')) {
				tooltip.clearQueue();
				return true;
			}

			tooltip.css('overflow','visible');

			if (delay) {
				tooltip.delay(800).queue(function(next){
					tooltip.addClass('active');
					next();
				});
				tooltip.fadeIn();
			} else {
				tooltip.addClass('active').fadeIn()
			}

		};

		var closeTooltip = function (el, delay) {

			var tooltip = $('body').find('.tooltip');

			if (!tooltip.hasClass('active')) {
				tooltip.clearQueue();
				return true;
			}

			if (delay) {
				tooltip.delay(800).fadeOut(400, function(){
					tooltip.detach();
				});
			} else {
				tooltip.fadeOut(400, function(){
					tooltip.detach();
				});
			}
		};

    </script>

	<?= $this->render('bottom_login.phtml') ?>
