<?=$this->render('head.phtml')?>

<body>
  <div class="page">
    <div class="head">
      <div class="head-in">
        <div class="logo">
          <a href="<?=$this->url(array('controller' => ''), 'default', true)?>"><img src="<?=$this->skin('img/phc.png')?>" alt="" title="domů" /></a>
        </div>
      </div>
      <div class="menu">
        <ul>
          <li class="m1"><div class="off"><strong>Průzkum</strong><br />Lorem ipsum dolor</div></li>
          <li class="m2"><div class="off"><strong>Komentované výsledky</strong><br />Typi non habent clarita</div></li>
          <li class="m3"><div class="off"><strong>Virtuální pacient</strong><br />Claritas est etiam procus</div></li>
        </ul>
        <a class="spc" href="#">spc</a>
        
      </div>
      <div class="reset"></div>

    </div>
    
    <div class="content"><div class="noslide">
      <div class="registrace">
        <h1>Registrace emailem</h1>
        <div class="souhlas-in"><div class="souhlasTop"><div class="souhlasBottom">
        <p>
            <?if(empty($this->loginError)){?>
                Vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
            <?}else{?>
                <br />
                <?=$this->loginError?>
                <br /><br /><br />
            <?}?>
        </p>
        
        <form action="" method="post">
        <table rules="none" cellspacing="0" cellpadding="0" border="0">
          <tr>
            <td><input type="text" class="text" name="email" id="email" value="<?=!empty($this->input['email']) ? $this->input['email'] : '@'?>" /></td>
            <td><input type="submit" class="submit" name="" value="Odeslat" /></td>
          </tr>
        </table>
        </form>
        </div></div></div>
      </div>

    </div></div>



<?=$this->render('bottom_login.phtml')?>
