<?= $this->render('default_head.phtml') ?>
<body>
    <div id="login-view">
        <div id="login_content">
            <img class="logo" src="pub/img/admin/newlogo.png" alt="Pears Health Cyber, s.r.o." />
           
            <?foreach($this->loginMessages as $msg):?>
             <div class="alert alert-error"><?=$msg?></div>
            <?endforeach?>
             <div style="width:220px;margin:0 auto 15px auto;"><a id="goalogin" class="btn btn-block btn-info" href="<?=$this->config->login->google->authservice->url?>/?r=<?=$this->urlHash?>">
                     Sign in with Google</a>
             </div>
             <label style="width:200px;margin:0 auto" class="optional checkbox" for="keepsign">
                <input type="checkbox" name="keepsign" id="keepsign" value="1">Keep me signed in
             </label>
             <hr>
            <?=$this->form?>  
        </div>
        <script type="text/javascript">
            var set_keepsign_url = function() {
                if ($('#keepsign').prop('checked')) {
                   var href = $('#goalogin').attr('href'); 
                   $('#goalogin').attr('href',href+'&keepsign=1');
               } else {
                    var href = $('#goalogin').attr('href'); 
                    $('#goalogin').attr('href',href.replace('&keepsign=1',''));
               }
            };
            set_keepsign_url();
            $('#keepsign').change(function(){
               set_keepsign_url();
            });
            
            
            
        </script>
    </div>
