<?=$this->render('head.phtml')?>

<body>
  <div class="pageLogin">
    <div class="login">
				<div class="logo">
				  <a href="<?=$this->url(array('controller' => ''), 'default', true)?>" title="Hlavní strana"><img src="pub/img/logo.gif" alt="inDetail" /></a>
				</div>
				<form action="" method="post">
				  <fieldset>
				    <label for="mail">Prosím zadejte Váš email pro obdržení inBulletin newsletteru.</label>
				    <input type="text" name="mail" id="mail" />
				    <div class="tc"><button type="submit">odeslat</button></div>
				  </fieldset>
				</form>
    </div>
    <p class="footLogin">
        &copy;2015 Pears Health Cyber, s.r.o. Powered by <a href="http://www.pearshealthcyber.com">Pears Health Cyber, s.r.o.</a><br />
Všechna práva vyhrazena. Tyto stránky jsou určené výhradně pro lékařskou veřejnost.
    </p>
  </div>
</body>
</html>
