<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<div class="statistics">

<!--?=$this->render('statsmenu.phtml')?-->

<form class="form-inline" action="" method="get">
<select name='bulletin-page'>
<?php
foreach($this->menu_array as $menu_key => $menu_item) {
	if(isset($this->formData["bulletin-page"]) && $this->formData["bulletin-page"] == $menu_key) {
        $current_menu_key = $menu_key;
		echo "<option value='{$menu_key}' selected>{$menu_item}</option>";
    } else {
    echo "<option value='{$menu_key}'>{$menu_item}</option>";
    }
}
?>
</select>
<input class="btn btn-primary" type="submit" value="<?=$this->text('submit')?>" />
</form>
<br/>

<div data-title="<?=$this->text('week_graph')?>" id="graf1" class="graph graph-bar">
<?=json_encode($this->daysInWeekChartData)?>
</div>

<div data-title="<?=$this->text('hours_graph')?>" id="graf2" class="graph graph-bar">
<?=json_encode($this->hoursInDayChartData)?>
</div>

<a id="chart"></a>
<div data-angle="-50" data-title="<?=sprintf($this->text('progression_graph'), $this->visitsRange);?> (<?=$this->text('progression_graph_note').$this->visitsProgressChartDataLimit?>)" id="graf3" class="graph graph-line graph-hack">
<?=json_encode($this->visitsProgressChartData)?>
</div>

<form method="GET" action="#chart" class="form-inline">
    <input type="text" name="visits_range" value="<?=$this->visitsRange?>" class="span1" />
    <input type="hidden" name="bulletin-page" value="<?=$current_menu_key?>"/>
    <input type="submit" class="btn btn-primary" value="<?=$this->text('change_range')?>" />
</form>
<br/><br/><br/>


</td>
</tr>


</table>

</div>


<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>
