<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<h3>Statistiky -> Jednotlivá vydání</h3>

<div id="submenu"><a
	href="<?=$this->url(array('controller' => 'stats',
    'action' => 'index'));?>">Celkové statistiky</a> | <b><a
	href="<?= $this->url(array('controller' => 'stats',
    'action' => 'bulletins')); ?>">Statistiky pro jednotlivá vydání</a></b> | <a
    href="<?= $this->url(array('controller' => 'stats',
    'action' => 'video')); ?>">Statistiky videí</a></div>



<!-- a href="<?= $this->url(array('controller' => 'stats',
    'action' => 'users')); ?>">Jmenný seznam</a --></div>

<?=isset($this->message) ? "<b>$this->message</b>" : '' ?>

<br />
&nbsp;

<?
if (isset($this->bulletinsStats) && !empty($this->bulletinsStats))
{?>
<table class="stat">
	<tr>
		<th>&nbsp;</th>
		<th>Bulletin</th>
		<th>Subscribers</th>
		<th>Readers</th>
		<th>Návštěvy</th>
		<th>Response rate</th>
		<th>Emaily</th>
		<th>Return rate</th>
		<th>Articles</th>
		<th>% ze všech článků</th>
	</tr>
	<?
	$i = 1;
	foreach ($this->bulletinsStats as $id => $bulletin)
	{?>
	<tr>
		<td class="blue"><?=$i++.'.'?></td>
		<td class="blue"><?=$bulletin['name']?></td>
		<td class="blue"><?
		$tmp = $bulletin['subscribers'];
		if(Admin_StatsController::TEST_STATS) $tmp = "<a href=\"".$this->url(array(
						'controller' => 'stats',
						'action' => 'bulletins',
						'what' => Admin_StatsController::BULLETIN_SUBSCRIBERS,
						'bulletinid' => $id
		))."\">$tmp</a>";
		echo $tmp;
		?>&nbsp;
		<?if(Ibulletin_AdminAuth::hasPermission('privilege_stats_can_export_xls')){?>
		<a
			href="<?=$this->url(array(
    						'controller' => 'stats',
    						'action' => 'export',
    						'what' => Admin_StatsController::BULLETIN_SUBSCRIBERS,
    						'bulletinid' => $id
    					))?>"><img src="pub/img/admin/icon-xls.png" style="border: none" /></a>
		</td>
		<?}?>
		<td class="blue"><?=$bulletin['readers']?>&nbsp;
		<?if(Ibulletin_AdminAuth::hasPermission('privilege_stats_can_export_xls')){?>
		<a
			href="<?=$this->url(array(
    						'controller' => 'stats',
    						'action' => 'export',
    						'what' => Admin_StatsController::BULLETIN_READERS,
    						'bulletinid' => $id
    					))?>"><img src="pub/img/admin/icon-xls.png" style="border: none" /></a>
		</td>
		<?}?>
		<td class="blue"><?=$bulletin['visits']?></td>
		<td class="blue"><?=isset($bulletin['response_rate']) ?
		$bulletin['response_rate'].'%' : '-' ?></td>
		<td class="blue"><a
			href="<?=$this->url(array('controller' =>
					'stats', 'action' => 'emails', 'bulletinid' => $id))?>">emaily</a></td>
		<td class="blue"><?=isset($bulletin['return_rate']) ? $bulletin['return_rate'].'%' : '-' ?></td>
		<td class="blue"><?=$bulletin['articles']?></td>
		<td class="blue"><?=$bulletin['articles_percent']?>%</td>
	</tr>
	<?}?>
</table>
	<?}

	if (isset($this->bulletinsStatsDetailSubs) && !empty($this->bulletinsStatsDetailSubs))
	echo "<h3>Detail</h3>".$this->bulletinsStatsDetailSubs;

	?>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
	<?=$this->render('admin_bottom.phtml')?>
