<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?$this->actionTitle .= ' &rarr; ' . $this->bulletinName?>
<?=$this->render('admin_top.phtml')?>

<div class="statistics">

<a href="<?=$this->url(array('controller' => 'stats', 'action' => 'campaign', 'bulletinId' => NULL))?>" ><?=$this->text('go_back')?></a>
<br/><br/>

<h3><?=$this->text('label')?></h3>

<?
/**
 * prehledova tabulka mailu na dany bulletin
 */
if ($this->rrPerBulletin) {?>
	<table data-table-colopt="1" data-table-export="1" id="campaign_mail" class="table table-striped table-hover table-bordered table-stats">
    <thead>
      <tr>
    	<th><?=$this->text('id')?></th>
        <th><?=$this->text('email')?></th>
        <th><?=$this->text('sent_date')?></th>
        <th><?=$this->text('sent')?></th>
        <th data-table-export-colspan="2" colspan="3"><?=$this->text('delivered')?></th>
        <th data-table-export-colspan="2" colspan="3"><?=$this->text('undelivered')?></th>
        <th data-table-export-colspan="2" colspan="3"><?=$this->text('open')?></th>
        <th colspan="2"><?=$this->text('open_online')?></th>
		<th data-table-export-colspan="2" colspan="3"><?=$this->text('click')?></th>
        <th data-table-export-colspan="2" colspan="3"><?=$this->text('click_late')?></th>
        <th data-table-export-colspan="2" colspan="3"><?=$this->text('min_open')?></th>
        <th class="no-data"><?=$this->text('users_summary')?></th>
        <th class="no-data">&nbsp;</th>
      </tr>
    </thead>
    <tbody>
	<?foreach ($this->rrPerBulletin as $bulletin) {?>
		<tr>
			<td><?=$bulletin['email_id']?></td>
            <td class="al"><?=$bulletin['name']?></td>
                <?
                //jazyk pro locale, hack cz prevadime na cs, vse kvuli nazvum dnu
                $lang = Ibulletin_Texts::getLangs();
                if ($lang[0] == "cz") {
                    $lang[0] = "cs";
                }
                $d = new Zend_Date($bulletin['send_date']);
                ?>
            <td data-table-export-format="m/d/yy h:mm" data-table-export-value="<?=$d->getIso()?>"><?=$d->toString("dd.MM.yyyy HH:mm (EEEE)",null,$lang[0]);?></td>
            <td><span class="svalue"><?=($bulletin['send'] + $bulletin['undelivered'])?></span></td>
            <td data-table-export-format="0%"><span class="svalue"><?=(($bulletin['send']+$bulletin['undelivered']) ? round(100*$bulletin['send']/($bulletin['send']+$bulletin['undelivered'])) : 0)?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['send']?></span></td>
            <td class="no-data"><?=Admin_StatsController::getExportButton(array('emailId' => $bulletin['email_id']),'email_send')?></td>
            <td data-table-export-format="0%"><span class="svalue"><?=(($bulletin['send']+$bulletin['undelivered']) ? round(100*$bulletin['undelivered']/($bulletin['send']+$bulletin['undelivered'])) : 0)?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['undelivered']?></span></td>
            <td class="no-data"><?=Admin_StatsController::getExportButton(array('emailId' => $bulletin['email_id']),'email_undelivered')?></td>
            <td data-table-export-format="0%"><span class="svalue"><?=($bulletin['send'] ? round(100*$bulletin['read']/$bulletin['send']) : 0)?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['read']?></span></td>
            <td class="no-data"><?=Admin_StatsController::getExportButton(array('emailId' => $bulletin['email_id']),'email_read')?></td>
            <td data-table-export-format="0%"><span class="svalue"><?=($bulletin['read'] ? round(100*$bulletin['read_online']/$bulletin['read']) : 0)?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['read_online']?></span></td>
            <td data-table-export-format="0%"><span class="svalue"><?=($bulletin['send'] ? round(100*$bulletin['response']/$bulletin['send']) : 0)?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['response']?></span></td>
            <td class="no-data"><?=Admin_StatsController::getExportButton(array('emailId' => $bulletin['email_id']),'email_response')?></td>
            <td data-table-export-format="0%"><span class="svalue"><?=($bulletin['send'] ? round(100*$bulletin['response_late']/$bulletin['send']) : 0)?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['response_late']?></span></td>
            <td class="no-data"><?=Admin_StatsController::getExportButton(array('emailId' => $bulletin['email_id']),'email_response_late')?></td>
            <td data-table-export-format="0%"><span class="svalue"><?=($bulletin['send'] ? round(100*$bulletin['read_prob']/$bulletin['send']) : 0)?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['read_prob']?></span></td>
            <td class="no-data"><?=Admin_StatsController::getExportButton(array('emailId' => $bulletin['email_id']),'email_read_prob')?></td>
            <td class="no-data"><?=Admin_StatsController::getExportButton(array('emailId' => $bulletin['email_id']),'users_summary_by_email')?></td>
            <td class="no-data"><a class="btn btn-mini btn-info" href="<?=$this->url(array('controller' => 'stats', 'action' => 'campaign_links', 'emailId' => $bulletin['email_id']))?>"><?=$this->text('email_detail')?></a></td>        
		</tr>
    <?}?>
    </tbody>
    </table>
<?}?>

</div>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>