<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?$this->actionTitle .= ' &rarr; ' . $this->bulletinName.' &rarr; '.$this->emailName .' &rarr; '. $this->linkName?>
<?=$this->render('admin_top.phtml')?>

<div class="statistics">

<a href="<?=$this->url(array('controller' => 'stats', 'action' => 'campaign_links', 'linkId' => NULL))?>"><?=$this->text('go_back')?></a>
<br/><br/> 

<h3><?=$this->text('label')?></h3>

<?
/**
 * prehledova tabulka mailu na dany bulletin
 */
if ($this->rrPerLink) {?>
    
    <table data-table-colopt="1" data-table-export="1" id="campaign_linksdetail" class="table table-striped table-hover table-bordered table-stats">
        <thead>
        <tr>
    	<th><?=$this->text('name')?></th>
        <th><?=$this->text('unique_clicks')?></th>
		<th><?=$this->text('total_clicks')?></th>        
    </tr>
        </thead>
        <tbody>
    <?foreach ($this->rrPerLink as $linkdetail) {?>    	
    <tr>
        <td class="al"><?=$linkdetail['name']?></td>        
        <td><span class="svalue"><?=$linkdetail['proklik_un']?></span></td>
        <td><span class="svalue"><?=$linkdetail['proklik']?></span></td>
    </tr>
    <?}?>
        </tbody>
    </table>
<?}?>

</div>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>