<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<div class="statistics">
<?if($this->responsePerBulletin){?>
	<table data-table-colopt="1" data-table-export="1" id="campaign" class="table table-striped table-hover table-bordered table-stats">
    <thead>
	<tr>
		<th><?=$this->text('order')?></th>
		<th><?=$this->text('issue')?></th>
		<th><?=$this->text('sent')?></th>
		<th data-table-export-colspan="2" colspan="3"><?=$this->text('delivered')?></th>
		<th data-table-export-colspan="2" colspan="3"><?=$this->text('undelivered')?></th>
		<th data-table-export-colspan="2" colspan="3"><?=$this->text('open')?></th>
		<th data-table-export-colspan="2" colspan="3"><?=$this->text('click')?></th>
		<th data-table-export-colspan="2" colspan="3"><?=$this->text('click_late')?></th>
		<th data-table-export-colspan="2" colspan="3"><?=$this->text('min_open')?></th>
        <th class="no-data"><?=$this->text('users_summary')?></th>
		<th class="no-data">&nbsp;</th>
        <th class="no-data aux-data"></th>
	</tr>
   </thead>
   <tbody>
	<?foreach ($this->responsePerBulletin as $bulletin) {?>
	<tr>
		<td><?=$bulletin['poradi']?></td>
		<td class="al"><?=$bulletin['name']?></td>
        <td><span class="svalue"><?=($bulletin['send'] + $bulletin['undelivered'])?></span></td>
        <td data-table-export-format="0%"><span class="svalue"><?=($bulletin['send']==0?'0':round(100*$bulletin['send']/($bulletin['send'] + $bulletin['undelivered'])))?>&nbsp%</span></td>
            <td><span class="svalue muted"><?=$bulletin['send']?></span></td>
		<td class="no-data"><?=Admin_StatsController::getExportButton(array('bulletinId' => $bulletin['bulletin_id']),'email_send')?></td>
        <td data-table-export-format="0%"><span class="svalue"><?=($bulletin['undelivered']== 0 ? '0':round(100*$bulletin['undelivered']/($bulletin['send'] + $bulletin['undelivered'])))?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['undelivered']?></span></td>
		<td class="no-data"><?=Admin_StatsController::getExportButton(array('bulletinId' => $bulletin['bulletin_id']),'email_undelivered')?></td>		
        <td data-table-export-format="0%"><span class="svalue"><?=($bulletin['send']==0?'0':round(100*$bulletin['read']/$bulletin['send']))?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['read']?></span></td>
        <td class="no-data"><?=Admin_StatsController::getExportButton(array('bulletinId' => $bulletin['bulletin_id']),'email_read')?></td>
        <td data-table-export-format="0%"><span class="svalue"><?=($bulletin['send']==0?'0':round(100*$bulletin['response']/$bulletin['send']))?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['response']?></span></td>
		<td class="no-data"><?=Admin_StatsController::getExportButton(array('bulletinId' => $bulletin['bulletin_id']),'email_response')?></td>
        <td><span class="svalue"><?=($bulletin['send']==0?'0':round(100*$bulletin['response_late']/$bulletin['send']))?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['response_late']?></span></td>
		<td class="no-data"><?=Admin_StatsController::getExportButton(array('bulletinId' => $bulletin['bulletin_id']),'email_response_late')?></td>
        <td><span class="svalue"><?=($bulletin['send']==0?'0':round(100*$bulletin['read_prob']/$bulletin['send']))?>&nbsp;%</span></td>
            <td><span class="svalue muted"><?=$bulletin['read_prob']?></span></td>
	    <td class="no-data"><?=Admin_StatsController::getExportButton(array('bulletinId' => $bulletin['bulletin_id']),'email_read_prob')?></td>
        <td class="no-data"><?=Admin_StatsController::getExportButton(array('bulletinId' => $bulletin['bulletin_id']),'users_summary_by_issue')?></td>
        <td class="no-data"><a class="btn btn-mini btn-info" href="<?=$this->url(array('module'=>'admin','controller' => 'stats', 'action' => 'campaign_mails', 'bulletinId' => $bulletin['bulletin_id']),null,true)?>"><?=$this->text('email_detail')?></a></td>
        <td class="no-data aux-data"><?=$bulletin['response_all']?></td>
	</tr>
	<?}?>
   </tbody>
	</table>
<?}?>

<?if($this->bul_more):?>
     <a class="btn btn-success tip" data-original-title="<?=$this->texts->tooltip->show_all?>" href="<?=$this->url()?>showall/1"><?=$this->texts->show_all?></a>   
<?endif;?>
    
<div data-col-label="1" data-angle="-50" data-title="<?=$this->text('chart_label')?>" data-table="campaign" data-col="13" data-relative="4" id="graf1" class="graph graph-bar"></div>

</div>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>