<?=$this->render('admin_top.phtml')?>

<div class="statistics">

<form class="form-inline" action="" method="get">
    <select name='bulletin_id'>
        <?/*<--option value='1'>Nespec<--/option>*/?>
        <?
        foreach($this->bulletins_v as $bulletin_v){
          if(isset($this->formData["bulletin_id"])&&$this->formData["bulletin_id"] == $bulletin_v['id'])
            echo "<option value='{$bulletin_v['id']}' selected>{$bulletin_v['name']}</option>";
          else
            echo "<option value='{$bulletin_v['id']}'>{$bulletin_v['name']}</option>";
        }?>
    </select>
    <input class="btn btn-primary" type="submit" value="<?=$this->text('submit')?>" />
    <p/>
</form>

<?
    /**
     * instance statistik
     * @var Statistics
     */

     $this->statistics = Statistics::getInstance();
?>

<?
/**
 * prehledova tabulka ctenaru na dany bulletin
 */
/*
echo 'formData_bulletin: '.$this->formData["bulletin"].'***';
echo 'bulletin_v_id: '.$bulletin_v['id'].'***';
echo 'bulletin_v_name: '.$bulletin_v['name'].'***';
  */
 if ( !empty($this->articles) ) {

    echo '<table data-table-colopt="1" data-table-export="1" id="categories" class="table table-striped table-hover table-bordered table-stats">';
    echo '<thead><tr>
            <th>'.$this->text('category_name').'</th>
            <th class="no-data">'.$this->text('impressions').'</th>
            <th data-table-export-colspan="1" colspan="2">'.$this->text('readers_with_email').'</th>
            <th>'.$this->text('readers_without_email').'</th>
            <th class="tip" data-original-title="'.$this->text('readers_percentage_tooltip').'" >'.$this->text('readers_percentage').'</th>
            <th class="no-data">'.$this->text('graph').'</th>
    </tr></thead>';

    //maxprocento je ponekud zbytecne, kdyz posilame procento do 100
    $maxprocento=0;
    $i = 1;
    foreach ($this->articles as $bulletin) {
        $procento =  round(100*$bulletin['ctenaru']/$this->usersCount);
        $maxprocento = ($maxprocento < $procento ? $procento : $maxprocento);
        echo '<tbody><tr>';
        echo '<td class="al">'.$bulletin['name_c'].'</td>';
        echo '<td><span class="svalue">'.$bulletin['zobrazeni'].'</span></td>';
        echo '<td><span class="svalue">'.$bulletin['ctenaru'].'</span></td>';
        echo '<td class="no-data">'.Admin_StatsController::getExportButton(array('bulletinId' => $bulletin['bulletin_id'], 'categoryId' => $bulletin['category_id']),'category_view').'</td>';
        echo '<td><span class="svalue">'.$bulletin['ctenaru_bez'].'</span></td>';
        echo '<td data-table-export-format="0%"><span class="svalue">'.$procento.'&nbsp;%</span></td>';
        echo '<td class="no-data">';
        echo '<div style="height:60px; width:200px;margin:auto;" data-max="'.((ceil($maxprocento/10))*10).'" data-unit="%" id="graf'.$i.'" class="graph graph-horizontal-bar">'.json_encode(array('data'=>array($procento=>1))).'</div>';   
        echo '</td>';
        echo '</tr></tbody>';
        $i++;
    }
    echo '</table>';
}
?>


</div>

<?=$this->render('admin_bottom.phtml')?>
