<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<div class="statistics">

<?=$this->render('statsmenu.phtml')?>
<td>
  <h5>Počet kontaktů v jednotlivých regionech</h5>

<table id="stat-main" class="stat">
    <tr>
        <th>region</th>
        <th>počet</th>
        <th>%</th>
    </tr>
<?php 
$totalCount = 0;
foreach ($this->regions as $region) {
    $totalCount += $region['count'];  
?>

    <tr>
        <td><?=$region['name'] ?></td>
        <td><?=$region['count'] ?> <img src="/pub/img/admin/icon-xls.png"></td>
        <td><?=$region['percents'] ?></td>
    </tr>
<?php 
}
?>
    <tr>
        <th>všechny regiony</th>
        <th><?=$totalCount ?></th>
        <th><?php 
            $percentage = bcdiv($totalCount, $this->usersCount);
            $percentage = bcmul($percentage, 100);
            echo $percentage.'%';
        ?></th>
    </tr>
</table>
        
</td>
<td>
	<?php 
	if ( !empty($this->regionChart) ) {	    
	    echo '<img src="'.$this->url(array('action' => 'getchart', 'controller' => 'service', 'module' => 'default')).'?'.$this->regionChart.'" />';
	}
	?>
</td>
</tr>

<?php 
if ( !empty($this->timeChart) ) {        
    echo '<tr>
        <td></td>
        <td colspan="2">
            <h5>Počet kontaktů v jednotlivých regionech</h5>
            <img src="'.$this->url(array('action' => 'getchart', 'controller' => 'service', 'module' => 'default')).'?'.$this->timeChart.'" />
         </td></tr>
    ';
}
?>
<?php
if ( !empty($this->overview) ) {
        
$regionsCount = $this->regionsCount;
$overview = $this->overview;

?>
<tr>
<td></td>
<td colspan="2">
    <table class="stat">
        <th>vydání</th>
        <?php        
        /**
         * nadpisy tabulky
         */
        for ($i = 0; $i < $regionsCount; $i++) {                      
            echo '<th>'.$overview[$i]['region'].'</th>';
        }
        ?>
        <th>všechny regiony</th>
        
        <?php 
        /**
         * data
         */
       $counter = 0;
       $i = 0;
       $cols = $regionsCount + 2;       
       
       //pocet uzivatelu celkem
       $totalUsers = array();
       $_tu = 0;       
       
       foreach ($overview as $line) {           
           $_tu += $line['count'];           
           $counter++;                     
           if ( ($counter == $regionsCount) ) {                  
                array_push($totalUsers, $_tu);
                $counter = 0;
                $_tu = 0;               
           }                      
       }
       
       // vypis data       
       for ($i = 0; $i < $this->bulletinsCount; $i++) {
           echo '<tr>';
           echo '<td>'.$overview[$i*$regionsCount]['bulletin'].'</td>';
           $from = $i*$regionsCount;           
           $to = $i*$regionsCount+$regionsCount;
           
           for ($ii = $from; $ii < $to; $ii++) {               
               $division = intval(bcdiv($overview[$ii]['count'], $totalUsers[$i])*100);
               echo '<td>'.$overview[$ii]['count'];
               echo ' ('.$division.'%)';                              
               echo '</td>';                 
           }
           echo '<td>'.$totalUsers[$i].'</td>';
           echo '</tr>';       
       }                     
       ?>

    </table>
</td>
</tr>
<?php
    
}
?>

</table>

</div>


<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>
