<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<h4><?=$this->bulletinName?></h4>

<?=isset($this->message) ? "<b>$this->message</b>" : '' ?>

<div id="submenu"><a
	href="<?=$this->url(array('controller' => 'stats',
	'action' => 'bulletins', 'bulletinid' => null));?>">zpět</a></div>
<!-- id=submenu -->

	<?
	if (isset($this->emails) && !empty($this->emails))
	{?>
<table class=stat>
	<tr>
		<th>&nbsp;</th>
		<th>Název emailu</th>
		<th>Odesláno</th>
		<th>Kolik kliklo</th>
		<th>% prokliků</th>
	</tr>
	<?
	$i = 1;
	foreach ($this->emails as $id => $email)
	{?>
	<tr>
		<td><?=$i++.'.'?></td>
		<td><?=$email['name']?></td>
		<td class=cislo><?=$email['sents']?></td>
		<td class=cislo><?=$email['clicks']?></td>
		<td class=cislo><?=$email['percent']?>%</td>
	</tr>
	<?}?>
</table>
	<?}?>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
	<?=$this->render('admin_bottom.phtml')?>
