<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?= $this->render('admin_top.phtml') ?>

<?= $this->form ?>

<div class="statistics">

    <table data-table-export="1" id="entrymethodschannels" class="table table-striped table-hover table-bordered table-stats">
        <thead>
        <th><?=$this->texts->entrymethodschannels->channel?></th><th><?=$this->texts->entrymethodschannels->first_entry?></th>
        <th><?=$this->texts->entrymethodschannels->unique_users?></th><th><?=$this->texts->entrymethodschannels->all_usages?></th>
        </thead>
        <tbody>
            <? $moduleNames = Ibulletin_Texts::getSet('admin.templates'); ?>
            <? foreach ($this->entryMethods as $method): ?>
                <?if($method == 'wave'){continue;}?>
                <tr>
                    <td><?= $moduleNames->{$method} ?></td>
                    <td><span class="svalue"><?= ($this->entries[$method]['first_entry'] ? $this->entries[$method]['first_entry'] : 0) ?></span></td>
                    <td><span class="svalue"><?= ($this->entries[$method]['unique_users'] ? $this->entries[$method]['unique_users'] : 0) ?></span></td>
                    <td><span class="svalue"><?= ($this->entries[$method]['all_usages'] ? $this->entries[$method]['all_usages'] : 0) ?></span></td>
                </tr>
            <? endforeach ?>
            <? foreach ($this->entries['wave'] as $wave): ?>
                <tr>
                    <td><?= $moduleNames->{'wave'} ?>: <?=$wave['invitation_wave']?> (<?=$this->invitationWaveTypes[$wave['invitation_type']]?>)</td>
                    <td><span class="svalue"><?= ($wave['first_entry'] ? $wave['first_entry'] : 0) ?></span></td>
                    <td><span class="svalue"><?= ($wave['unique_users'] ? $wave['unique_users'] : 0) ?></span></td>
                    <td><span class="svalue"><?= ($wave['all_usages'] ? $wave['all_usages'] : 0) ?></span></td>
                </tr>
            <? endforeach ?>      
        </tbody>

    </table>

</div>


<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>