<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<div class="statistics">

<table data-table-export="1" id="entrymethods" class="table table-striped table-hover table-bordered table-stats">
    <thead>
        <tr>
            <th>
                <span data-toggle="tooltip" title="<?=$this->text('all_visits_tip')?>">
                <?=$this->text('wave_id')?></span>
            </th>
            <th><?=$this->text('wave_name')?></th>
            <th><span data-toggle="tooltip" title="<?=$this->text('invited_tip')?>">
                <?=$this->text('invited')?></span></th>
            <th><span data-toggle="tooltip" title="<?=$this->text('sessions_tip')?>">
                <?=$this->text('sessions')?></span></th>
            <th colspan="2"><span data-toggle="tooltip" title="<?=$this->text('users_tip')?>">
                <?=$this->text('users')?></span></th>
        </tr>
    </thead>
    <tbody>
        <?foreach($this->wavesData as $row){?>
            <tr>
                <td><?=$row['id']?></td>
                <td><?=$row['name']?></td>
                <td><span class="svalue"><?=$row['invited']?></span></td>
                <td><span class="svalue"><?=$row['sessions']?></span></td>
                
                    <?if ($row['invited'] > 0)  {?>
                <td data-table-export-format="0%"><span class="svalue"><?=round($row['users'] / $row['invited'] * 100, 0)?>&nbsp;%</span></td>
                <td><span class="svalue muted"><?=$row['users']?></span></td>
                    <?} else {?>
                <td colspan="2"><span class="svalue"><?=$row['users']?></span></td>
                    <?}?>
                </td>
            </tr>
        <?}?>
    </tbody>
</table>
<?if($this->bul_more):?>
     <a class="btn btn-success tip" data-original-title="<?=$this->texts->tooltip->show_all?>" href="<?=$this->url()?>showall/1"><?=$this->texts->show_all?></a> 
     <br />
<?endif;?>


</div><?/* class statistics END */?>


<script language="JavaScript">
    $('[data-toggle=tooltip]').tooltip();
</script>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>