<?=$this->render('admin_top.phtml')?>

<div class="statistics">
<?=$this->render('stats/indetail_filters.phtml')?>


<?/* Shlednutych prezentaci */?>
<h3><?=$this->text('visitedPresentationsHeading')?></h3>
<table data-table-name="<?=$this->stattablename1?>" data-table-colopt="1" data-table-export="1" id="indetails_connections1" style="width:auto;" class="table table-striped table-hover table-bordered table-stats">
    <thead>
        <tr>
            <th><?=$this->text('visitedPresentations')?></th>
            <th data-table-export-colspan="1" colspan="2"><?=$this->text('physiciansCount')?></th>
        </tr>
    </thead>
    <tbody>
        <?foreach($this->seen as $seen){?>
        <tr>
            <td><?=$this->text('exactly')?> <?=$seen['content_count']?></td>
            <td><span class="svalue"><?=$seen['user_count']?></span></td>
            <td class="no-data"><?=Admin_StatsController::getExportButton(array('content_count'=>$seen['content_count'],'from_iso'=>$this->fromIso,'to_iso'=>$this->toIso,'repre_id' => $this->repreId),'indetail_connections_views')?></td>
        </tr>
        <?}?>
    </tbody>
</table>

<table data-table-name="<?=$this->stattablename3?>" data-table-colopt="1" data-table-export="1" id="indetails_connections3" style="width:auto;" class="table table-striped table-hover table-bordered table-stats">
    <thead>
        <tr>
            <th><?=$this->text('combinationPresentations')?></th>
            <th data-table-export-colspan="1" colspan="2"><?=$this->text('combinationAtLeastOne')?></th>
            <th data-table-export-colspan="1" colspan="2"><?=$this->text('combinationExactly')?></th>
        </tr>
    </thead>
    <tbody>
        <? foreach ($this->combinations as $c): ?>
            <tr>
            <td><?= $c['name'] ?></td>
            <td><span class="svalue"><?= $c['count_least'] ?></span></td>
            <td class="no-data"><?=Admin_StatsController::getExportButton(array('contents_id'=>implode('|',$c['contentsId']),'from_iso'=>$this->fromIso,'to_iso'=>$this->toIso,'repre_id' => $this->repreId),'indetail_connections_combination_at_least')?></td>
            <td><span class="svalue"><?= $c['count_exactly'] ?></span></td>
            <td class="no-data"><?=Admin_StatsController::getExportButton(array('contents_id'=>implode('|',$c['contentsId']),'from_iso'=>$this->fromIso,'to_iso'=>$this->toIso,'repre_id' => $this->repreId),'indetail_connections_combination_exactly')?></td>
            </tr>
        <? endforeach ?>
    </tbody>
</table>

<?/* Poradi shlednuti prezentaci */?>
<h3><?=$this->text('visitOrderHeading')?></h3>
<table data-table-name="<?=$this->stattablename2?>" data-table-colopt="1" data-table-export="1" id="indetails_connections2" style="background-color: #eee;" class="table table-striped table-hover table-bordered table-stats">
    <thead>
        <tr>
            <th colspan="2"><?=$this->text('presentation')?></th>
            <th colspan="<?=2*$this->connectionsMaxOrder?>"><?=$this->text('orderOfView')?></th>
        </tr>
        <tr>
            <th><?=$this->text('id')?></th>
            <th><?=$this->text('name')?></th>
            <?for($i = 1; $i <= $this->connectionsMaxOrder; $i++){?>
                <th data-table-export-colspan="1" colspan="2"><?=$i?></th>
            <?}?>
        </tr>
    </thead>
    <tbody>
        <?foreach($this->connections as $id => $c):?>
            <tr>
                <td><?=$id?></td><td><?=$c['name']?></td>
                <?for($i=1; $i <= $this->connectionsMaxOrder; $i++):?>
                    <?if (isset($c[$i])):?>
                        <td><span class="svalue"><?=$c[$i]?></span></td>
                        <td class="no-data"><?=Admin_StatsController::getExportButton(array('content_id'=>$id,'order'=>$i,'from_iso'=>$this->fromIso,'to_iso'=>$this->toIso,'repre_id'=>$this->repreId),'indetail_connections_order')?></td>
                    <?else:?>
                        <td></td><td></td>
                    <?endif;?>
                <?endfor;?>
        </tr>
        <?endforeach;?>
    </tbody>
</table>

</div><?/*statistics end*/?>

<?=$this->render('admin_bottom.phtml')?>