<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<div class="statistics">

<!--?=$this->render('statsmenu.phtml')?-->


<?if(empty($this->noExports)){?>
    <a href="<?=$this->url(array('content' => $this->formData["content"], 'export' => 'visits'))?>">
        <img src="pub/img/admin/icon-xls.png" style="border: none"/> <?=$this->text('export_visits')?></a><br/><br/>
<?}?>

<form action="" method="get">

<label><?=$this->text('slider_label')?>:</label>
<div id="slider-range"></div>
<br/>

<input type="hidden" name="last_content" value="<?=$this->formData["content"]?>"/>
<select name='content' id="contentSel">
<?php

foreach($this->contents as $key => $content) {
	if(isset($this->formData["content"]) && $this->formData["content"] == $content['id']){
		echo "<option value='{$content['id']}' title='{$this->contentFirstUsed[$content['id']]}' selected='selected'>".
		  "{$content['id']} - {$content['object']->name}</option>";
    }
    else{
        echo "<option value='{$content['id']}' title='{$this->contentFirstUsed[$content['id']]}'>".
            "{$content['id']} - {$content['object']->name}</option>";
    }
}
?>
</select>
<label><?=$this->text('date_from')?>:</label><input type="text" class="datepicker" id="datepickFrom" name="from" value="<?=$this->dateFrom?>" size="15"/>
<label><?=$this->text('date_to')?>:</label><input type="text" class="datepicker" id="datepickTo" name="to" value="<?=$this->dateTo?>" size="15"/>
<input type="submit" value="<?=$this->text('submit')?>" />
<p><label><?=$this->text('form_description')?></label></p>
</form>


<br/><br/>
<h2><?=$this->text('presentation_results')?></h2><br/>
<table class="stat">
  <tr>
    <th><?=$this->text('invitation_chanel')?></th>
    <th><?=$this->text('invited')?></th>
    <th><?=$this->text('come')?></th>
    <th><?=$this->text('started')?></th>
    <th><?=$this->text('finished')?></th>
  </tr>
<?
$firstMail = true;
$firstWave = true;
foreach ($this->report_emails as $email){
    // Vypiseme nadpis radku pro maily a vlny
    if($email['email_id'] && $firstMail){
        ?><tr><th colspan="5"><?=$this->text('emails')?></th></tr><?
        $firstMail = false;
    }
    if($email['wave_id'] && $firstWave){
        ?><th><td colspan="5"><?=$this->text('waves')?></th></tr><?
        $firstWave = false;
    }
?>
<?
	echo "<tr>";
	echo "<td>".(($email['name']=="other" && $email['email_id']==0 && $email['wave_id']==0) ? $this->text('other') : $email['name'])."</td>";
	echo "<td>".$email['invited'].
		(($email['email_id']>0 && $email['invited']>0) ? Admin_StatsController::getExportButton(array('what' => 'indetail_invited', 'contentId' => $this->formData["content"], 'emailId' => $email['email_id'], 'waveId' => $email['wave_id'])) : '').
		"</td>";
	echo "<td>".$email['come'].
		Admin_StatsController::getExportButton(array('what' => 'indetail_come', 'contentId' => $this->formData["content"], 'emailId' => $email['email_id'], 'waveId' => $email['wave_id'])).
		', '.$email['come%']."%</td>";
	echo "<td>".$email['started'].
		Admin_StatsController::getExportButton(array('what' => 'indetail_started', 'contentId' => $this->formData["content"], 'emailId' => $email['email_id'], 'waveId' => $email['wave_id'])).
		', '.$email['started%']."%</td>";
	echo "<td>".$email['finished'].', '.$email['finished%']."%</td>";
	echo "</tr>";
}
if (isset($this->report_content)) {
	echo "<tr>";
	echo "<td>".$this->report_content['name']."</td>";
	echo "<td>".$this->report_content['invited'].
		Admin_StatsController::getExportButton(array('what' => 'indetail_invited', 'contentId' => $this->formData["content"])).
		"</td>";
	echo "<td>".$this->report_content['come'].
		Admin_StatsController::getExportButton(array('what' => 'indetail_come', 'contentId' => $this->formData["content"])).
		', '.$this->report_content['come%']."%</td>";
	echo "<td>".$this->report_content['started'].
		Admin_StatsController::getExportButton(array('what' => 'indetail_started', 'contentId' => $this->formData["content"])).
		', '.$this->report_content['started%']."%</td>";
	echo "<td>".$this->report_content['finished'].', '.$this->report_content['finished%']."%</td>";
	echo "</tr>";
}
?>
</table>

<br/><br/>
<h2><?=$this->text('slides_visited')?></h2><br/>
<?=sprintf($this->text('average_time_is'), $this->average, $this->median)?><br/><br/>
<table class="tablesorter">
  <thead>
  <tr>
    <th><?=$this->text('slide')?></th>
    <th><?=$this->text('visited_by')?></th>
    <th><?=$this->text('percentage_from_last_slide')?></th>
    <th><?=$this->text('average_time_on_slide')?></th>
  </tr>
  </thead>
  <tbody>
<?
/**
 * tabulka propustnosti slidy
 */
if (empty($this->slideVisitors)){
echo "<tr><td colspan=\"5\" style=\"text-align:center\">empty</td></tr>";
}
foreach ($this->slideVisitors as $slide){
	echo "<tr ".($slide['mandatory'] ? 'style="background-color:#99ff99;"' : '').">";
	echo "<td>".$slide['slide']."</td>";
	echo "<td>".$slide['pocet']."</td>";
	echo "<td>".$slide['procent']."%</td>";
	echo "<td>{$slide['avg']} s / ({$slide['median']} s) </td>";
	echo "</tr>";
}
?>
  </tbody>
</table>

<?
/**
 * graf propustnosti slidy
 */
if ( !empty($this->slideVisitorsChart) ) {
    echo '<img src="'.$this->url(array('action' => 'getchart', 'controller' => 'service', 'module' => 'default')).'?'.$this->slideVisitorsChart.'" />';
    echo "<br/><br/><br/>";
}
?>

<br/><br/>
<table class="stat">
<tr><th rowspan="2"><?=$this->text('presentation_ID')?></th><th colspan="<?=$this->inDetailVisitorsMaxPoradi;?>"><?=$this->text('order')?></th></tr>
<?php
$is_header = false;
foreach ($this->inDetailVisitorsInOrder as $c_id => $row) {
    if (!$is_header) {
        foreach ($row as $poradi => $pocet) {
            echo "<th>".$poradi."</th>";
        }
        echo "</tr>";
        $is_header = true;
    }
}
reset($this->inDetailVisitorsInOrder);
foreach ($this->inDetailVisitorsInOrder as $c_id => $row) {
    echo "<tr><th>".$c_id."</th>";
    foreach ($row as $poradi => $pocet) {
        echo "<td>".$pocet."</td>";
    }
    echo "</tr>";
}
?>
</table>


</div>


<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>
