<?=$this->render('admin_top.phtml')?>

<div class="statistics">
<?=$this->render('stats/indetailpresentations_navigation.phtml')?>
<?=$this->render('stats/indetail_filters.phtml')?>


<table data-table-name="<?=$this->stattablename?>" data-table-colopt="1" data-table-export="1" id="indetails_resources" class="table table-striped table-bordered table-hover table-stats">
    <thead>
        <tr>
            <th><?=$this->text('id')?></th>
            <th><?=$this->text('name')?></th>
            <th><?=$this->text('viewed')?></th>
            <th><?=$this->text('viewedUniqueSession')?></th>
            <th><?=$this->text('viewedUniquePhysician')?></th>
            <th><?=$this->text('avgSesTime')?></th>
            <th><?=$this->text('medSesTime')?></th>
            <th><?=$this->text('avgUsrTime')?></th>
            <th><?=$this->text('medUsrTime')?></th>
        </tr>
    </thead>
    <tbody>
        <?foreach($this->resources as $resource){?>
            <tr>
                <td><?=$resource['resource_id']?></td>
                <td><?=$resource['name']?></td>
                <td><span class="svalue"><?=$resource['view_count']?></span></td>
                <td><span class="svalue"><?=$resource['session_count']?></span></td>
                <td><span class="svalue"><?=$resource['user_count']?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$resource['avg_ses_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($resource['avg_ses_time'])?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$resource['med_ses_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($resource['med_ses_time'])?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$resource['avg_usr_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($resource['avg_usr_time'])?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$resource['med_usr_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($resource['med_usr_time'])?></span></td>
            </tr>
        <?}?>
    </tbody>
</table>


</div><?/*statistics end*/?>

<?=$this->render('admin_bottom.phtml')?>