<?=$this->render('admin_top.phtml')?>

<div class="statistics">
<?=$this->render('stats/indetail_filters.phtml')?>


<table data-table-name="<?=$this->stattablename?>" id="indetails" data-table-export="1" data-table-colopt="1" class="table table-striped table-hover table-bordered table-stats">
    <thead>
        <tr>
            <th><?=$this->text('id')?></th>
            <th><?=$this->text('name')?></th>
            <th><?=$this->text('viewed')?></th>
            <th><?=$this->text('viewedUniqueSession')?></th>
            <th><?=$this->text('viewedUniquePhysician')?></th>
            <th><?=$this->text('finished')?></th>
            <th><?=$this->text('percent')?></th>
            <th><?=$this->text('avgSesTime')?></th>
            <th><?=$this->text('medSesTime')?></th>
            <th><?=$this->text('avgUsrTime')?></th>
            <th><?=$this->text('medUsrTime')?></th>
            <th class="no-data"></th>
        </tr>
    </thead>
    <tbody>
        <?foreach($this->presentations as $presentation){?>
            <tr>
                <td><?=$presentation['content_id']?></td>
                <td><?=$presentation['name']?></a></td>
                <td><span class="svalue"><?=$presentation['view_count']?></span></td>
                <td><span class="svalue"><?=$presentation['session_count']?></span></td>
                <td><span class="svalue"><?=$presentation['user_count']?></span></td>
                <td><span class="svalue"><?=($presentation['slides_mandatory'] == 0) ? '-' : $presentation['finished']?></span></td>
                <td data-table-export-format="0%"><span class="svalue"><?=($presentation['slides_mandatory'] == 0) ? '-' : ($presentation['user_count'] ? round($presentation['finished']/$presentation['user_count'] * 100).'&nbsp;%' : '')?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$presentation['avg_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($presentation['avg_time']).$presentation['avg_ses_time']?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$presentation['med_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($presentation['med_time'])?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$presentation['avg_usr_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($presentation['avg_usr_time'])?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$presentation['med_usr_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($presentation['med_usr_time'])?></span></td>
                <td class="no-data">
                    <div class="btn-group-stats">
                    <a class="btn btn-mini btn-info" href="<?=$this->url(array('action' => 'indetailpresentationsslides')).'?content='.$presentation['content_id']?>">
                        <?=$this->text('slides')?>
                    </a>
                    <a class="btn btn-mini btn-info tip" data-title="<?=$this->text('resources_tooltip')?>" href="<?=$this->url(array('action' => 'indetailpresentationsresources')).'?content='.(int)$presentation['content_id']?>">
                        <?=$this->text('resources')?>
                    </a>
                    <a class="btn btn-mini btn-info" href="<?=$this->url(array('action' => 'indetailpresentationschannels')).'?content='.(int)$presentation['content_id']?>">
                        <?=$this->text('channels')?>
                    </a>
                    <a class="btn btn-mini btn-info" href="<?=$this->url(array('action' => 'indetailpresentationsqa', 'indetailpresentaions' => 1, 'operation' => 'showdata')).'?content='.(int)$presentation['content_id']?>">
                        <?=$this->text('questions')?>
                    </a>
                    </div>
                </td>
            </tr>
        <?}?>
    </tbody>
</table>

<?if($this->bul_more):?>
    <a class="btn btn-success tip" data-original-title="<?=$this->texts->indetailpresentations->tooltip_show_all?>" href="<?=$this->url()?>showall/1"><?=$this->texts->indetailpresentations->show_all?></a>
<?endif;?>


</div><?/*statistics end*/?>

<?=$this->render('admin_bottom.phtml')?>