<?=$this->render('admin_top.phtml')?>

<div class="statistics">
<?=$this->render('stats/indetail_filters.phtml')?>

<?/* Export */?>
<?=Admin_StatsController::getExportButton(
    array_merge(array('total' => '1'), (array)$this->filtersData, array('filename'=>$this->stattablename)),
    'indetail_globalresources', $this->text('export'),'btn')?>


<table data-table-name="<?=$this->stattablename?>" data-table-colopt="1" data-table-export="1" id="indetails_resources" class="table table-striped table-hover table-bordered table-stats">
    <thead>
        <tr>
            <th><?=$this->text('id')?></th>
            <th><?=$this->text('name')?></th>
            <th><?=$this->text('contentId')?></th>
            <th><?=$this->text('contentName')?></th>
            <th><?=$this->text('viewed')?></th>
            <th><?=$this->text('viewedUniqueSession')?></th>
            <th><?=$this->text('viewedUniquePhysician')?></th>
            <th><?=$this->text('avgSesTime')?></th>
            <th><?=$this->text('medSesTime')?></th>
            <th><?=$this->text('avgUsrTime')?></th>
            <th><?=$this->text('medUsrTime')?></th>
        </tr>
    </thead>
    <tbody>
        <?foreach($this->resources as $resource){?>
            <tr>
                <td><?=$resource['resource_id']?></td>
                <td><?=$resource['name']?></td>
                <td><?=$resource['content_id']?></td>
                <td><?=$resource['content_name']?></td>
                <td><span class="svalue"><?=$resource['view_count']?></span></td>
                <td><span class="svalue"><?=$resource['session_count']?></span></td>
                <td><span class="svalue"><?=$resource['user_count']?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$resource['avg_ses_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($resource['avg_ses_time'])?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$resource['med_ses_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($resource['med_ses_time'])?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$resource['avg_usr_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($resource['avg_usr_time'])?></span></td>
                <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$resource['med_usr_time']?>"><span class="svalue"><?=Utils::ms_to_timestring($resource['med_usr_time'])?></span></td>
            </tr>
        <?}?>
    </tbody>
</table>
<?if($this->bul_more):?>
    <a class="btn btn-success tip" data-original-title="<?=$this->texts->tooltip->show_all?>" href="<?=$this->url()?>showall/1"><?=$this->texts->show_all?></a>
<?endif;?>

</div><?/*statistics end*/?>

<?=$this->render('admin_bottom.phtml')?>