<?=$this->render('admin_top.phtml')?>

<div class="statistics">
<?=$this->render('stats/indetailpresentations_navigation.phtml')?>  
<?=$this->render('stats/indetail_filters.phtml')?>

<table data-table-name="<?=$this->stattablename?>" data-table-colopt="1" data-table-export="1" id="indetails_channels" class="table table-striped table-hover table-bordered table-stats">
    <thead>
        <tr>
            <th><?=$this->text('type')?></th>
            <th><?=$this->text('id')?></th>
            <th><?=$this->text('name')?></th>
            <th data-table-export-colspan="1" colspan="2"><?=$this->text('invited')?></th>
            <th data-table-export-colspan="2" colspan="3"><?=$this->text('come')?></th>
            <th data-table-export-colspan="2" colspan="3"><?=$this->text('started')?></th>
            <th data-table-export-colspan="2" colspan="3"><?=$this->text('finished')?></th>
        </tr>
    </thead>
    <tbody>
        <?foreach($this->channels as $channel){?>
            <tr>
                <td><?=$channel['email_id'] ? $this->text('typeEmail') : ($channel['wave_id'] ? $this->text('typeWave') : $this->text('typeOther'))?></td>
                <td><?=$channel['email_id'] ? $channel['email_id'] : ($channel['wave_id'] ? $channel['wave_id'] : '')?></td>
                <td><?=$channel['name']?></td>
                <td><span class="svalue"><?=$channel['invited']?></span></td>
                <td class="no-data">
                    <?=$channel['invited'] && $channel['email_id'] ?
                        Admin_StatsController::getExportButton(
                            array_merge(array('emailId' => $channel['email_id']), (array)$this->filtersData), 
                            'indetail_invited')
                    : ''?>
                </td>
                <td data-table-export-format="0%"><span class="svalue"><?=$channel['invited'] ? round($channel['come']/$channel['invited'] * 100).'&nbsp;%' : 'n/a'?></span></td><td><span class="svalue muted"><?=$channel['come']?></span></td>
                <td class="no-data">
                    <?=$channel['come'] ?
                        Admin_StatsController::getExportButton(
                            array_merge(array('emailId' => $channel['email_id'], 'wave' => $channel['wave_id']), (array)$this->filtersData), 
                            'indetail_come')
                    : ''?>
                </td>
                <td data-table-export-format="0%"><span class="svalue"><?=$channel['come'] ? round($channel['started']/$channel['come'] * 100).'&nbsp;%' : 'n/a'?></span></td><td><span class="svalue muted"><?=$channel['started']?></span></td>
                <td class="no-data">
                    <?=$channel['started'] ?
                        Admin_StatsController::getExportButton(
                            array_merge(array('emailId' => $channel['email_id'], 'wave' => $channel['wave_id']), (array)$this->filtersData), 
                            'indetail_started')
                    : ''?>
                </td>
                <td data-table-export-format="0%"><span class="svalue"><?=$channel['started'] ? round($channel['finished']/$channel['started'] * 100).'&nbsp;%' : 'n/a'?></span></td><td><span class="svalue muted"><?=$channel['finished']?></span></td>
                <td class="no-data">
                    <?=$channel['finished'] ?
                        Admin_StatsController::getExportButton(
                            array_merge(array('emailId' => $channel['email_id'], 'wave' => $channel['wave_id']), (array)$this->filtersData), 
                            'indetail_finished')
                    : ''?>
                </td>
            </tr>
        <?}?>
        <tr class="info">
            <?$sums = $this->channelsTotals?>
            <td></td>
            <td></td>
            <td><strong><?=$this->text('total')?></strong></td>
            <td><span class="svalue"><?=$sums['invited'] ? $sums['invited']:'n/a'?></span></td>
            <td class="no-data">
                <?=$sums['invited'] ?
                    Admin_StatsController::getExportButton(
                        (array)$this->filtersData, 
                        'indetail_invited')
                : ''?>
            </td>
            <td data-table-export-format="0%"><span class="svalue"><?=$sums['invited'] ? round($sums['come']/$sums['invited'] * 100).'&nbsp;%' : 'n/a'?></span></td><td><span class="svalue muted"><?=$sums['come']?></span></td>
            <td class="no-data">
                <?=$sums['come'] ?
                    Admin_StatsController::getExportButton(
                        array_merge(array('total' => '1'), (array)$this->filtersData), 
                        'indetail_come')
                : ''?>
            </td>
            <td data-table-export-format="0%"><span class="svalue"><?=$sums['come'] ? round($sums['started']/$sums['come'] * 100).'&nbsp;%' : 'n/a'?></span></td><td><span class="svalue muted"><?=$sums['started']?></span></td>
            <td class="no-data">
                <?=$sums['started'] ?
                    Admin_StatsController::getExportButton(
                        array_merge(array('total' => '1'), (array)$this->filtersData), 
                        'indetail_started')
                : ''?>
            </td>
            <td data-table-export-format="0%"><span class="svalue"><?=$sums['started'] ? round($sums['finished']/$sums['started'] * 100).'&nbsp;%' : 'n/a'?></span></td><td><span class="svalue muted"><?=$sums['finished']?></span></td>
             <td class="no-data">
                <?=$sums['finished'] ?
                    Admin_StatsController::getExportButton(
                        array_merge(array('total' => '1'), (array)$this->filtersData), 
                        'indetail_finished')
                : ''?>
            </td>
        </tr>
    </tbody>
</table>


</div><?/*statistics end*/?>

<?=$this->render('admin_bottom.phtml')?>