<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<h4><?=$this->areaType?></h4>

<div class="statistics">

<!--?=$this->render('statsmenu.phtml')?-->

<td>
  <h5>Počet čtenářů dle jednotlivých <?=$this->areaTypeL2?></h5>

<table id="stat-main" class="stat">
    <tr>
        <th><?=$this->areaType?></th>
        <th>počet</th>
        <th>%</th>
    </tr>
<?php 
$totalCount = 0;
foreach ($this->areas as $area) {
    $totalCount += $area['count'];  
?>

    <tr>
        <td><?=$area['name'] ?></td>
        <td><?=$area['count'] ?> <img src="/pub/img/admin/icon-xls.png"></td>
        <td><?=$area['percents'] ?></td>
    </tr>
<?php 
}
?>
    <tr>
        <th><?=$this->areaTypeL?></th>
        <th><?=$totalCount ?></th>
        <th><?php 
            $percentage = ceil(100*$totalCount/$this->usersCount);
//            $percentage = bcmul($percentage, 100);
            echo $percentage.'%';
        ?></th>
    </tr>
</table>
        
</td>
<td>
    <?php 
    if ( !empty($this->areaChart) ) {        
        echo '<img src="'.$this->url(array('action' => 'getchart', 'controller' => 'service', 'module' => 'default')).'?'.$this->areaChart.'" />';
    }
    ?>
</td>
</tr>

<?php 
if ( !empty($this->timeChart) ) {        
    echo '<tr>
        <td></td>
        <td colspan="2">
            <h5>Počet čtenářů dle jednotlivých '.$this->areaTypeL2.'</h5>
            <img src="'.$this->url(array('action' => 'getchart', 'controller' => 'service', 'module' => 'default')).'?'.$this->timeChart.'" />
         </td></tr>
    ';
}
?>
<?php
if ( !empty($this->overview) ) {
        
$areasCount = $this->areasCount;
$overview = $this->overview;
 //print_r($overview);
?>
<tr>
<td></td>
<td colspan="2">
    <table class="stat">
        <th>vydání</th>
        <?php        
        /**
         * nadpisy tabulky
         */
        for ($i = 0; $i < $areasCount; $i++) {                      
            echo '<th>'.$overview[$i][$this->area].'</th>';
        }
        ?>
        <th><?=$this->areaTypeL?></th>
        
        <?php 
        /**
         * data
         */
       $counter = 0;
       $i = 0;
       $cols = $areasCount + 2;       
       
       //pocet uzivatelu celkem
       $totalUsers = array();
       $_tu = 0;       
       
       foreach ($overview as $line) {           
           $_tu += $line['count'];           
           $counter++;                     
           if ( ($counter == $areasCount) ) {                  
                array_push($totalUsers, $_tu);
                $counter = 0;
                $_tu = 0;               
           }                      
       }
       
       // vypis data  
       for ($i = 0; $i < $this->bulletinsCount; $i++) {
           echo '<tr>';
           echo '<td>'.$overview[$i*$areasCount]['bulletin'].'</td>';
           $from = $i*$areasCount;           
           $to = $i*$areasCount+$areasCount;
           for ($ii = $from; $ii < $to; $ii++) {               
               $division = intval(bcdiv($overview[$ii]['count'], $totalUsers[$i])*100);
               echo '<td>'.$overview[$ii]['count'];
               echo ' ('.$division.'%)';                              
               echo '</td>';                 
           }
           echo '<td>'.$totalUsers[$i].'</td>';
           echo '</tr>';       
       }                     
       ?>

    </table>
</td>
</tr>
<?php
    
}
?>

</table>

</div>


<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>
