<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<div class="statistics">

    <?=$this->form?>
    
    <table data-table-colopt="1" data-table-export="1" id="links_mail" class="table table-striped table-bordered table-hover table-stats">
        <thead>
        <tr>
            <th><?=$this->text('mail_title')?></th>                    
            <th data-table-export-colspan="1" colspan="2"><?=$this->text('mail_total_users')?></th>
            <th><?=$this->text('mail_total_clicks')?></th>
        </tr>
        </thead>
        <tbody>

        <?foreach ($this->links as $area) {?>
            <tr>
                <td><?=$area['title']?></td>                            
                <td><span class="svalue"><?=$area['users']?></span></td>
                <td class="no-data"><?=Admin_StatsController::getExportButton(array('link_title'=>$area['title'],'bulletin_id'=>$this->bulletinId),'links_unique_mail')?></td>
                <td><span class="svalue"><?=$area['clicks']?></span></td>
            </tr>
            
        <?}?>
        </tbody>
    </table>
    
</div>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>
