<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?= $this->render('admin_top.phtml') ?>

<div class="statistics">

        <?= $this->form ?>

        <table data-table-colopt="1" data-table-export="1" id="links" class="table table-striped table-bordered table-hover table-stats">
            <thead>
                <tr>
                    <th><?= $this->text('link_id') ?></th>
                    <th><?= $this->text('name') ?></th>
                    <th data-table-export-colspan="1" colspan="2"><?= $this->text('unique_clicks') ?></th>
                    <th><?= $this->text('total_clicks') ?></th>
                </tr>
            </thead>
            <tbody>
                <? foreach ($this->links as $link) { ?>
                    <tr>
                        <td><?= $link['link_id'] ?></td>
                        <td><?= $link['name'] ?></td>
                        <td><span class="svalue"><?= $link['count_users'] ?></span></td>
                        <td class="no-data"><?=Admin_StatsController::getExportButton(array('link_id' => $link['link_id'],'bulletin_id'=>$this->bulletinId),'links_unique')?></td>
                        <td><span class="svalue"><?= $link['used_times'] ?></span></td>
                    </tr>
                <? } ?>
            </tbody>
        </table>

</div>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=
$this->render('admin_bottom.phtml')?>