<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?= $this->render('admin_top.phtml') ?>

<div class="statistics">

        <table data-table-colopt="1" data-table-export="1" id="resources" class="table table-striped table-bordered table-hover table-stats">
            <thead>
                <tr>
                    <th><?= $this->text('id') ?></th>
                    <th><?= $this->text('name') ?></th>
                    <th data-table-export-colspan="1" colspan="2"><?= $this->text('unique_clicks') ?></th>
                    <th><?= $this->text('total_clicks') ?></th>
                </tr>
            </thead>
            <tbody>
                <? foreach ($this->resources as $r) { ?>
                    <tr>
                        <td><?= $r['id'] ?></td>
                        <td><?= $r['name'] ?></td>
                        <td><span class="svalue"><?= $r['unique_clicks'] ?></span></td>
                        <td class="no-data"><?=Admin_StatsController::getExportButton(array('resource_id' => $r['id']),'resources_unique')?></td>
                        <td><span class="svalue"><?= $r['total_clicks'] ?></span></td>
                    </tr>
                <? } ?>
            </tbody>
        </table>

</div>

<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=
$this->render('admin_bottom.phtml')?>