<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?=$this->render('admin_top.phtml')?>

<div class="statistics">

<!--?=$this->render('statsmenu.phtml')?-->

<div data-col-label="1" data-col="2" data-angle="-50" data-title="<?=$this->text('chart_label')?>" data-unit="%" data-table="returnrate" id="graf1" class="graph graph-bar"></div>    

<div data-col-label="1" data-col="3" data-angle="-50" data-title="<?=$this->text('chart_all_label')?>" data-unit="%" data-table="returnrate" id="graf2" class="graph graph-bar"></div>    

<?php
/**
 * prehledova tabulka vrativsichse ctenaru na dany bulletin
 */
//if ( !empty($this->rrPerBulletin ) ) {
    
    echo '<table data-table-colopt="1" data-table-export="1" id="returnrate" class="table table-striped table-hover table-bordered table-stats">';
    echo '<thead><tr>';
    echo '<th>'.$this->text('order').'</th>';
    echo '<th>'.$this->text('issue').'</th>';
    //echo '<th>RR cislo</th>';
    echo '<th colspan="2">'.$this->text('return_rate_valid').'</th>';
    echo '<th colspan="2">'.$this->text('return_rate_all').'</th>';
    echo '</tr></thead>';
    echo '<tbody>';
    foreach ($this->rrPerBulletin as $bulletin) {
        $procento =  $bulletin['readers_last']==0?'0':round(100*$bulletin['rr']/$bulletin['readers_last']);
        $procento_all =  $bulletin['readers_last_all']==0?'0':round(100*$bulletin['rr_all']/$bulletin['readers_last_all']);
         
        echo '<tr>';
        echo '<td>'.$bulletin['poradi'].'</td>';
        echo '<td>'.$bulletin['name'].'</td>';
/*        echo '<td>'.$bulletin['rr']
        .Admin_StatsController::getExportButton(array('what' => 'returnrate', 'bulletinId' => $bulletin['bulletin_id']))
        .'</td>';
*/
        if($bulletin['poradi'] == 1) {
            echo '<td data-table-export-format="0%"><span class="svalue">0&nbsp;%</span></td><td></td>';
            echo '<td data-table-export-format="0%"><span class="svalue">0&nbsp;%</span></td><td></td>';
        }
        else {
            echo '<td data-table-export-format="0%"><span class="svalue">'.$procento.'&nbsp;%</span></td><td><span class="svalue muted">'.$bulletin['rr'].'</span></td>';
            echo '<td data-table-export-format="0%"><span class="svalue">'.$procento_all.'&nbsp;%</span></td><td><span class="svalue muted">'.$bulletin['rr_all'].'</span></td>';
        }
        echo '</tr>';
    }
    echo '</tbody></table>';
//}
?>    

</div>


<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>
