<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?= $this->render('admin_top.phtml') ?>

<?= isset($this->message) ? "<b>$this->message</b>" : '' ?>


<? if (is_array($this->videosTable)):?>
    <table data-table-colopt="1" data-table-export="1" id="video" class="table table-striped table-hover table-bordered table-stats">
        <thead>
            <tr>
                <th><?= $this->text('videoList_id') ?></th>
                <th><?= $this->text('videoList_num') ?></th>
                <th><?= $this->text('videoList_video') ?></th>
                <th data-table-export-colspan="1" colspan="2"><?= $this->text('videoList_visited') ?></th>
                <th colspan="2"><?= $this->text('videoList_average_visited') ?></th>
                <th colspan="2"><?= $this->text('videoList_median_visited') ?></th>
                <th><?= $this->text('videoList_average_rating') ?></th>
                <th><?= $this->text('videoList_median_rating') ?></th>
                <th class="no-data">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->videosTable as $video):?>
                <tr>
                    <td>
                        <?= $video['content_id'] ?>
                    </td>
                    <td>
                        <?= $video['video_num'] ?>
                    </td>
                    <td>
                        <?= $video['name'] ?>
                    </td>
                    <td>
                        <span class="svalue"><?= $video['watchers'] ?></span>
                    </td>
                    <td class="no-data">
                        <?=Admin_StatsController::getExportButton(array('videoId' => $video['content_id']),'video_watchers')?>
                     </td>
                    <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$video['positiontime']?>">
                        <span class="svalue muted"><?=Utils::ms_to_timestring($video['positiontime'])?></span>
                    </td>
                    <td data-table-export-format="0%">
                        <?if(round($video['position'] > 0)): ?>
                        <span class="svalue"><?= round($video['position']) ?> %</span>&nbsp;    
                        <?endif;?>
                    </td>
                    <td data-table-export-format="[h]:mm:ss" data-table-export-value="<?=$video['position_median']?>">
                         <span class="svalue muted"><?=Utils::ms_to_timestring($video['position_median'])?></span>
                    </td>
                    <td data-table-export-format="0%">
                        <?if(round($video['position_median_percent'] > 0)):?>
                        <span class="svalue"><?= round($video['position_median_percent']) ?> %</span>&nbsp;  
                        <?endif;?>
                    </td>
                    <td>
                        <span class="svalue"><?= round($video['rating'], 2) ?></span>
                    </td>
                    <td>
                        <span class="svalue"><?= round($video['rating_median'], 2) ?></span>
                    </td>
                    <td class="no-data">
                        <a class="btn btn-mini btn-export tip btn-info" data-original-title="<?=$this->text('admin.stats.tooltip.export_xls')?>" href="<?= $this->url(array('videoId' => $video['content_id'], 'videoNum' => $video['video_num'])) ?>"> 
                           <?= $this->text('videoList_detail') ?>&nbsp;<span class="glyphicon glyphicon-download-alt"></span>
                        </a>
                        
                    </td>
                </tr>
    <?  endforeach; ?>
        </tbody>
    </table>
<?endif;?>



<!-- Vsechen html kod adminu za obsahem teto stranky --> 
<?=$this->render('admin_bottom.phtml')?>