<?=$this->render('admin_top.phtml')?>
<?=$this->form?>

	<?
	if (isset($this->updatedRows))// odeslan formular, zkouselo se nastavit stav
{
		if ($this->updatedRows != 0 || $this->updatedRows == "bad"){
			if ($this->updatedRows == "bad"){
				echo $this->text('badaddr');
			}
			else{
				echo $this->text('undelivered');
			}
		}
		else{
			echo $this->text('notfound');
		}
	}
	?>


<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=$this->render('admin_bottom.phtml')?>
