<!-- Vsechen html kod adminu pred obsahem teto stranky -->
<?= $this->render('admin_top.phtml') ?>
<div class="row">
    <div class="span8">
        <p><?= $this->description?></p>
        <?= $this->form ?>
    </div>
    <div class="span4">
        <?=$this->collapse($this->text('help'),null,array(1))?>
    </div>
</div>
<!-- Vsechen html kod adminu za obsahem teto stranky -->
<?=
$this->render('admin_bottom.phtml')?>