<?= $this->render('admin_top.phtml') ?>
<div class="row">
    <div class="span8">
        <?= $this->form ?>	
        <?= $this->partial('filemanager.phtml',array('cpath'=>$this->path)) ?>
    </div>
    <div class="span4">	
        <?=
        $this->collapse(
                $this->text('help'), array(
                    'links' => array('title' => $this->text('links_list.main.title'), 'body' => $this->render('contentLinks.phtml'))),
                    array(1)
                
        )
        ?>   
    </div>
</div>
<?=
$this->render('admin_bottom.phtml')?>