<?=$this->render('admin_top.phtml')?>

<h3>Výpis odpovědí na dotazník <?=$this->content_name?></h3>

<?if(!empty($this->content_not_found)){?>
Požadovaný dotazník nebyl nalezen.
<?}else{?>
<table class="std">
	<tr>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		<th colspan="<?=count($this->questionsHead)?>">Číslo otázky</th>
	</tr>
	<tr>
		<th>Id</th>
		<th>Příjmení</th>
		<th>Jméno</th>
		<th>E-mail</th>
		<?foreach($this->questionsHead as $col){?>
		<th><?=$col?></th>
		<?}?>
	</tr>
	<?foreach($this->answersTable as $d){?>
	<?='<tr><td>'.join('</td><td>', $d).'</td></tr>'?>
	<?}?>
</table>
	<?}?>

	<?=$this->render('admin_bottom.phtml')?>